import test from "node:test";
import assert from "node:assert/strict";
import { checkoutAmounts } from "../src/utils/checkoutAmounts.ts";
import { paymentReadinessMessage,postalCodeError } from "../src/utils/checkoutValidation.ts";
import { orderSuccessCopy } from "../src/utils/orderSuccess.ts";
import { cityDistrictMismatch } from "../src/utils/delivery.ts";
import { orderSchema } from "../api/_shared.ts";

test("LKR 1600 plus LKR 400 produces LKR 2000",()=>{assert.deepEqual(checkoutAmounts(1600,400,true),{ready:true,subtotal:1600,discountAmount:0,deliveryFee:400,total:2000});});
test("LKR 1600 plus LKR 500 produces LKR 2100",()=>{assert.equal(checkoutAmounts(1600,500,true).total,2100);});
test("free delivery keeps the transfer amount at the subtotal",()=>{assert.deepEqual(checkoutAmounts(1600,0,true),{ready:true,subtotal:1600,discountAmount:0,deliveryFee:0,total:1600});});
test("an unresolved delivery quote has no final transfer amount",()=>{assert.deepEqual(checkoutAmounts(1600,0,false),{ready:false,subtotal:1600,discountAmount:0,deliveryFee:0,total:undefined});});
test("recomputes immediately when cart or delivery values change",()=>{assert.equal(checkoutAmounts(1600,500,true).total,2100);assert.equal(checkoutAmounts(3200,0,true).total,3200);});
test("postal validation requires a five-digit numeric code",()=>{assert.equal(postalCodeError("0150"),"Postal code must be exactly 5 digits.");assert.equal(postalCodeError("10A50"),"Postal code must contain numbers only.");assert.equal(postalCodeError("10250"),"");assert.equal(postalCodeError(""),"Enter your postal code.");});
test("payment readiness explains the actual delivery blocker",()=>{assert.equal(paymentReadinessMessage({city:"",district:"",postalError:"",deliveryEnabled:true,quoteReady:false}),"Complete your delivery details to continue.");assert.equal(paymentReadinessMessage({city:"Colombo",district:"Colombo",postalError:"Enter your postal code.",deliveryEnabled:true,quoteReady:false}),"Enter your postal code to continue.");assert.equal(paymentReadinessMessage({city:"Colombo",district:"Colombo",postalError:"bad",deliveryEnabled:true,quoteReady:false}),"Fix the postal code above to continue.");assert.equal(paymentReadinessMessage({city:"Unknown",district:"Colombo",postalError:"",deliveryEnabled:true,quoteReady:false}),"Check your delivery address above to continue.");assert.equal(paymentReadinessMessage({city:"Colombo",district:"Colombo",postalError:"",deliveryEnabled:true,quoteReady:true}),"");});
test("success copy distinguishes COD and bank verification",()=>{assert.equal(orderSuccessCopy("cod","LKR 2,000").detail,"Pay LKR 2,000 when your order arrives.");assert.equal(orderSuccessCopy("bank","LKR 2,000").title,"Payment verification pending");});
test("city mismatch uses configured delivery rates only",()=>{const rates=[{courierProviderId:"c1",fee:400,active:true,districts:["Colombo"],cities:["Nugegoda"],postalCodes:[],fallback:false,sortOrder:1}];assert.equal(cityDistrictMismatch(rates,{city:"Nugegoda",district:"Kandy"},"c1"),true);assert.equal(cityDistrictMismatch(rates,{city:"Nugegoda",district:"Colombo"},"c1"),false);assert.equal(cityDistrictMismatch(rates,{city:"Unknown",district:"Kandy"},"c1"),false);});
test("pickup checkout accepts empty delivery address fields",()=>assert.equal(orderSchema.safeParse({customerName:"Browser Customer",phone:"0772222222",email:"browser@example.com",fulfillmentMethod:"pickup",pickupLocationId:"test-branch",address1:"",city:"",district:"",postalCode:"",paymentMethod:"cod",items:[{productId:"product",variantId:"variant",quantity:1}]}).success,true));
