import test from "node:test";
import assert from "node:assert/strict";
import {buildPublicCheckoutConfig} from "../api/_data/public-checkout.ts";
const base=[{key:"codEnabled",value:true},{key:"deliveryEnabled",value:true},{key:"deliveryFlatFee",value:450},{key:"freeDeliveryThreshold",value:5000},{key:"defaultCourierProviderId",value:"courier-1"},{key:"currency",value:"LKR"},{key:"storeOpen",value:true},{key:"ordersEnabled",value:true},{key:"bankName",value:"Private Bank"},{key:"bankAccountName",value:"ZEVENRA"},{key:"bankAccountNumber",value:"123456"},{key:"bankBranch",value:"Colombo"},{key:"bankInstructions",value:"Reference order"}],couriers=[{id:"courier-1",name:"Internal Courier",phone:"private",notes:"internal",pricingMode:"zone",flatRate:0,active:true}],rates=[{id:"zone-1",name:"Colombo Central",courierProviderId:"courier-1",fee:450,active:true,districts:["Colombo"],cities:[],postalCodes:[],fallback:true,sortOrder:1}];
const settings=(result:ReturnType<typeof buildPublicCheckoutConfig>)=>Object.fromEntries(result.settings.map(row=>[row.key,row.value]));
test("bank disabled excludes every bank account field",()=>{const result=buildPublicCheckoutConfig([...base,{key:"bankTransferEnabled",value:false}],couriers,rates),keys=result.settings.map(row=>row.key);for(const key of ["bankName","bankAccountName","accountName","bankAccountNumber","accountNumber","bankBranch","branch","bankInstructions"])assert.equal(keys.includes(key),false);assert.equal(settings(result).codEnabled,true);});
test("bank enabled returns only canonical customer-facing bank fields",()=>{const result=buildPublicCheckoutConfig([...base,{key:"bankTransferEnabled",value:true}],couriers,rates),values=settings(result);assert.equal(values.bankEnabled,true);assert.equal(values.bankName,"Private Bank");assert.equal(values.accountName,"ZEVENRA");assert.equal(values.accountNumber,"123456");assert.equal(values.branch,"Colombo");assert.equal(values.bankInstructions,"Reference order");assert.equal("bankAccountNumber" in values,false);});
test("COD-only configuration remains enabled without bank details",()=>{const values=settings(buildPublicCheckoutConfig([...base,{key:"bankEnabled",value:false}],couriers,rates));assert.equal(values.codEnabled,true);assert.equal(values.bankEnabled,false);assert.equal("accountNumber" in values,false);});
test("public courier payload exposes only checkout-safe fields including selectable area identity",()=>{const result=buildPublicCheckoutConfig([...base,{key:"bankEnabled",value:false}],couriers,rates);assert.deepEqual(Object.keys(result.couriers[0]).sort(),["active","flatRate","id","pricingMode"]);assert.deepEqual(Object.keys(result.deliveryRates[0]).sort(),["active","cities","courierProviderId","districts","fallback","fee","id","name","postalCodes","sortOrder"]);const courier=result.couriers.find(item=>item.id==="courier-1"&&item.active),zone=result.deliveryRates.find(item=>item.id==="zone-1"&&item.active&&item.courierProviderId===courier?.id);assert.equal(zone?.name,"Colombo Central");assert.equal(zone?.fee,450);});
