import {createContext,useContext,useMemo,useState,type ReactNode} from 'react';
import {initialStoreData} from '../../data/demo';
import type {Category,Collection,ContentPage,HomepageSection,NavigationItem,Product,SiteSettings,SizeChart,StoreData} from '../../types';
type Entity='products'|'categories'|'collections'|'navigation'|'homepageSections'|'sizeCharts'|'pages';type EntityValue=Product|Category|Collection|NavigationItem|HomepageSection|SizeChart|ContentPage;
type Value={data:StoreData;save:<T extends EntityValue>(entity:Entity,value:T)=>void;remove:(entity:Entity,id:string)=>void;duplicate:(entity:Entity,id:string)=>void;reorder:(entity:Entity,id:string,direction:-1|1)=>void;saveSettings:(patch:Partial<SiteSettings>)=>void;resetDemo:()=>void};
const storageKey='zevenra-admin-data-v2';const Context=createContext<Value|null>(null);
function load():StoreData{try{const raw=localStorage.getItem(storageKey);if(raw)return {...initialStoreData,...JSON.parse(raw) as StoreData}}catch{return initialStoreData}return initialStoreData}
export function StoreProvider({children}:{children:ReactNode}){const [data,setData]=useState(load);const commit=(next:StoreData)=>{setData(next);localStorage.setItem(storageKey,JSON.stringify(next))};const value=useMemo<Value>(()=>({data,save:(entity,item)=>{const list=data[entity] as EntityValue[];commit({...data,[entity]:list.some(x=>x.id===item.id)?list.map(x=>x.id===item.id?item:x):[...list,item]})},remove:(entity,id)=>commit({...data,[entity]:(data[entity] as EntityValue[]).filter(x=>x.id!==id)}),duplicate:(entity,id)=>{const list=data[entity] as EntityValue[],source=list.find(x=>x.id===id);if(!source)return;const copy={...source,id:`${entity.slice(0,2)}-${crypto.randomUUID()}`,name:'name'in source?`${String(source.name)} Copy`:undefined,label:'label'in source?`${String(source.label)} Copy`:undefined,slug:'slug'in source?`${String(source.slug)}-copy`:undefined,sortOrder:list.length+1} as EntityValue;commit({...data,[entity]:[...list,copy]})},reorder:(entity,id,direction)=>{const list=[...(data[entity] as EntityValue[])],index=list.findIndex(x=>x.id===id),target=index+direction;if(index<0||target<0||target>=list.length)return;[list[index],list[target]]=[list[target],list[index]];commit({...data,[entity]:list.map((x,i)=>({...x,sortOrder:i+1}))})},saveSettings:patch=>commit({...data,settings:{...data.settings,...patch,hero:{...data.settings.hero,...patch.hero}}}),resetDemo:()=>{localStorage.removeItem(storageKey);setData(initialStoreData)}}),[data]);return <Context.Provider value={value}>{children}</Context.Provider>}
export function useStore(){const value=useContext(Context);if(!value)throw new Error('StoreProvider required');return value}
export function navigationHref(item:NavigationItem){if(item.linkType==='category'||item.linkType==='collection')return `/collections/${item.target}`;return item.target.startsWith('/')?item.target:`/${item.target}`}
