import {createContext,useCallback,useContext,useEffect,useMemo,useRef,useState,type ReactNode} from 'react';
import {initialStoreData} from '../../data/demo';
import {adminApi} from '../../services/adminApi';
import type {Category,Collection,ContentPage,DashboardData,DeliveryRate,HomepageSection,NavigationItem,Order,Product,SiteSettings,SizeChart,StoreData} from '../../types';

type Entity='products'|'categories'|'collections'|'navigation'|'homepageSections'|'sizeCharts'|'pages';
type EntityValue=Product|Category|Collection|NavigationItem|HomepageSection|SizeChart|ContentPage;
type AdminState={dashboard:DashboardData|null;orders:Order[];deliveryRates:DeliveryRate[]};
type Value={data:StoreData;loading:boolean;error:string;adminLoading:boolean;adminError:string;admin:AdminState;live:boolean;loadAdmin:()=>Promise<void>;retry:()=>void;save:<T extends EntityValue>(entity:Entity,value:T)=>void;remove:(entity:Entity,id:string)=>void;duplicate:(entity:Entity,id:string)=>void;reorder:(entity:Entity,id:string,direction:-1|1)=>void;saveSettings:(patch:Partial<SiteSettings>)=>void;saveDeliveryRates:(rates:DeliveryRate[])=>void;updateOrder:(patch:Partial<Order>&{orderId:string})=>void;resetDemo:()=>void};
type SettingsRow={key:string;value:unknown};
type PublicPayload={products:unknown[];categories:unknown[];collections:unknown[];sizeCharts:unknown[];settings:SettingsRow[]|Record<string,unknown>};

const demo=import.meta.env.VITE_DEMO_MODE!=='false',loginRoute=location.pathname==='/admin/login',storageKey='zevenra-admin-data-v2',Context=createContext<Value|null>(null);
const emptyAdmin:AdminState={dashboard:null,orders:[],deliveryRates:[]};
const bool=(value:unknown)=>value===true||String(value).toLowerCase()==='true';
const number=(value:unknown)=>Number(value)||0;
const json=<T,>(value:unknown,fallback:T):T=>{if(Array.isArray(value)||value&&typeof value==='object')return value as T;try{return JSON.parse(String(value||'')) as T}catch{return fallback}};
const normalizeCategory=(row:unknown):Category=>{const x=row as Record<string,unknown>;return{...x,active:bool(x.active),featured:bool(x.featured),showInNavigation:bool(x.showInNavigation),showOnHomepage:bool(x.showOnHomepage),sortOrder:number(x.sortOrder)} as Category};
const normalizeCollection=(row:unknown):Collection=>{const x=row as Record<string,unknown>;return{...x,active:bool(x.active),showInNavigation:bool(x.showInNavigation),showOnHomepage:bool(x.showOnHomepage),sortOrder:number(x.sortOrder)} as Collection};
const normalizeSizeChart=(row:unknown):SizeChart=>{const x=row as Record<string,unknown>;return{...x,columns:json(x.columns??x.columnsJson,[]),rows:json(x.rows??x.rowsJson,[])} as unknown as SizeChart};
const normalizeProduct=(row:unknown):Product=>{const x=row as Record<string,unknown>,variants=json<Record<string,unknown>[]>(x.variants,[]).map(v=>({...v,stock:number(v.stock),lowStockThreshold:number(v.lowStockThreshold),active:bool(v.active)}));return{...x,price:number(x.price),compareAtPrice:x.compareAtPrice===''||x.compareAtPrice==null?undefined:number(x.compareAtPrice),media:json(x.media??x.mediaJson,[]),tags:Array.isArray(x.tags)?x.tags:String(x.tags||'').split(',').filter(Boolean),collectionIds:json(x.collectionIds,[]),featured:bool(x.featured),newArrival:bool(x.newArrival),sortOrder:number(x.sortOrder),variants} as unknown as Product};
function normalizeSettings(source:SettingsRow[]|Record<string,unknown>):SiteSettings{const raw=Array.isArray(source)?Object.fromEntries(source.map(row=>[row.key,row.value])):source;const mapped:Record<string,unknown>={...raw,deliveryFee:raw.deliveryFee??raw.deliveryFlatFee,bankEnabled:raw.bankEnabled??raw.bankTransferEnabled,accountName:raw.accountName??raw.bankAccountName,accountNumber:raw.accountNumber??raw.bankAccountNumber,branch:raw.branch??raw.bankBranch};const result=structuredClone(initialStoreData.settings) as unknown as Record<string,unknown>;for(const[key,defaultValue]of Object.entries(result)){if(mapped[key]===undefined)continue;if(typeof defaultValue==='boolean')result[key]=bool(mapped[key]);else if(typeof defaultValue==='number')result[key]=number(mapped[key]);else if(key==='hero')result[key]={...(defaultValue as object),...json(mapped[key],{})};else result[key]=mapped[key]}return result as unknown as SiteSettings}
function settingsPayload(patch:Partial<SiteSettings>){const payload:Record<string,unknown>={...patch};if(patch.deliveryFee!==undefined){payload.deliveryFlatFee=patch.deliveryFee;delete payload.deliveryFee}if(patch.bankEnabled!==undefined){payload.bankTransferEnabled=patch.bankEnabled;delete payload.bankEnabled}if(patch.accountName!==undefined){payload.bankAccountName=patch.accountName;delete payload.accountName}if(patch.accountNumber!==undefined){payload.bankAccountNumber=patch.accountNumber;delete payload.accountNumber}if(patch.branch!==undefined){payload.bankBranch=patch.branch;delete payload.branch}return payload}
function demoLoad():StoreData{try{const saved=localStorage.getItem(storageKey);return saved?{...initialStoreData,...JSON.parse(saved) as StoreData}:initialStoreData}catch{return initialStoreData}}
function message(error:unknown){return error instanceof Error?error.message:'The operation could not be completed.'}

export function StoreProvider({children}:{children:ReactNode}){const[data,setData]=useState<StoreData>(()=>demo?demoLoad():initialStoreData),[loading,setLoading]=useState(!demo&&!loginRoute),[error,setError]=useState(''),[adminLoading,setAdminLoading]=useState(!demo),[adminError,setAdminError]=useState(''),[admin,setAdmin]=useState<AdminState>(emptyAdmin),timers=useRef<Record<string,ReturnType<typeof setTimeout>>>({});
 const applyPublic=useCallback((payload:PublicPayload)=>setData(current=>({...current,products:payload.products.map(normalizeProduct),categories:payload.categories.map(normalizeCategory),collections:payload.collections.map(normalizeCollection),sizeCharts:payload.sizeCharts.map(normalizeSizeChart),settings:normalizeSettings(payload.settings),navigation:[],homepageSections:[]})),[]);
 const loadPublic=useCallback(async()=>{if(demo||loginRoute)return;setLoading(true);setError('');try{const response=await fetch(`${import.meta.env.VITE_API_BASE||'/api'}/store`),payload=await response.json() as PublicPayload&{error?:string};if(!response.ok)throw new Error(payload.error||'Live store data could not be loaded.');applyPublic(payload)}catch(reason){setError(message(reason))}finally{setLoading(false)}},[applyPublic]);
 useEffect(()=>{const pending=timers.current;void loadPublic();return()=>Object.values(pending).forEach(clearTimeout)},[loadPublic]);
 const refreshEntity=useCallback(async(entity:Entity)=>{if(entity==='products'){const rows=await adminApi.get<unknown[]>('listProducts');setData(x=>({...x,products:rows.map(normalizeProduct)}))}else if(entity==='categories'){const rows=await adminApi.get<unknown[]>('listCategories');setData(x=>({...x,categories:rows.map(normalizeCategory)}))}else if(entity==='collections'){const rows=await adminApi.get<unknown[]>('listCollections');setData(x=>({...x,collections:rows.map(normalizeCollection)}))}else if(entity==='sizeCharts'){const rows=await adminApi.get<unknown[]>('listSizeCharts');setData(x=>({...x,sizeCharts:rows.map(normalizeSizeChart)}))}},[]);
 const loadAdmin=useCallback(async()=>{if(demo)return;setAdminLoading(true);setAdminError('');try{const[dashboard,products,categories,collections,sizeCharts,orders,settings,deliveryRates]=await Promise.all([adminApi.get<DashboardData>('dashboard'),adminApi.get<unknown[]>('listProducts'),adminApi.get<unknown[]>('listCategories'),adminApi.get<unknown[]>('listCollections'),adminApi.get<unknown[]>('listSizeCharts'),adminApi.get<Order[]>('listOrders'),adminApi.get<SettingsRow[]>('getSettings'),adminApi.get<DeliveryRate[]>('listDeliveryRates')]);setData(x=>({...x,products:products.map(normalizeProduct),categories:categories.map(normalizeCategory),collections:collections.map(normalizeCollection),sizeCharts:sizeCharts.map(normalizeSizeChart),settings:normalizeSettings(settings),navigation:[],homepageSections:[]}));setAdmin({dashboard,orders,deliveryRates:deliveryRates.map(rate=>({...rate,fee:number(rate.fee),active:bool(rate.active)}))})}catch(reason){setAdminError(message(reason))}finally{setAdminLoading(false)}},[]);
 const demoCommit=(next:StoreData)=>{setData(next);localStorage.setItem(storageKey,JSON.stringify(next))};
 const queue=useCallback((key:string,work:()=>Promise<void>)=>{clearTimeout(timers.current[key]);timers.current[key]=setTimeout(()=>{void work().catch(reason=>setAdminError(message(reason)))},450)},[]);
 const save=useCallback(<T extends EntityValue>(entity:Entity,item:T)=>{const update=(current:StoreData)=>{const list=current[entity] as EntityValue[];return{...current,[entity]:list.some(x=>x.id===item.id)?list.map(x=>x.id===item.id?item:x):[...list,item]} as StoreData};if(demo){demoCommit(update(data));return}setData(update);const actions:Partial<Record<Entity,string>>={products:'saveProduct',categories:'saveCategory',collections:'saveCollection',sizeCharts:'saveSizeChart'},action=actions[entity];if(!action){setAdminError(`${entity} is not available in the live backend.`);return}setAdminError('');queue(`${entity}:${item.id}`,async()=>{await adminApi.post(action,item);await refreshEntity(entity)})},[data,queue,refreshEntity]);
 const remove=useCallback((entity:Entity,id:string)=>{if(demo){demoCommit({...data,[entity]:(data[entity] as EntityValue[]).filter(x=>x.id!==id)});return}if(entity!=='products'){setAdminError(`Deleting ${entity} is not supported by the current backend.`);return}setAdminError('');void adminApi.post('deleteProduct',{id}).then(()=>refreshEntity('products')).catch(reason=>setAdminError(message(reason)))},[data,refreshEntity]);
 const duplicate=useCallback((entity:Entity,id:string)=>{const list=data[entity] as EntityValue[],source=list.find(x=>x.id===id);if(!source)return;const copy={...structuredClone(source),id:crypto.randomUUID(),name:'name'in source?`${String(source.name)} Copy`:undefined,label:'label'in source?`${String(source.label)} Copy`:undefined,slug:'slug'in source?`${String(source.slug)}-copy`:undefined,sortOrder:list.length+1} as EntityValue;save(entity,copy)},[data,save]);
 const reorder=useCallback((entity:Entity,id:string,direction:-1|1)=>{const list=[...(data[entity] as EntityValue[])],index=list.findIndex(x=>x.id===id),target=index+direction;if(index<0||target<0||target>=list.length)return;[list[index],list[target]]=[list[target],list[index]];list.map((item,i)=>({...item,sortOrder:i+1}) as EntityValue).forEach(item=>save(entity,item))},[data,save]);
 const saveSettings=useCallback((patch:Partial<SiteSettings>)=>{const next={...data.settings,...patch,hero:{...data.settings.hero,...patch.hero}};if(demo){demoCommit({...data,settings:next});return}setData(x=>({...x,settings:next}));setAdminError('');queue('settings',async()=>{await adminApi.post('saveSettings',settingsPayload(patch));const rows=await adminApi.get<SettingsRow[]>('getSettings');setData(x=>({...x,settings:normalizeSettings(rows)}))})},[data,queue]);
 const saveDeliveryRates=useCallback((rates:DeliveryRate[])=>{if(demo){setAdmin(x=>({...x,deliveryRates:rates}));return}setAdmin(x=>({...x,deliveryRates:rates}));void adminApi.post<DeliveryRate[]>('saveDeliveryRates',{rates}).then(rows=>setAdmin(x=>({...x,deliveryRates:rows}))).catch(reason=>setAdminError(message(reason)))},[]);
 const updateOrder=useCallback((patch:Partial<Order>&{orderId:string})=>{if(demo)return;void adminApi.post<Order>('updateOrder',patch).then(()=>loadAdmin()).catch(reason=>setAdminError(message(reason)))},[loadAdmin]);
 const resetDemo=()=>{if(!demo)return;localStorage.removeItem(storageKey);setData(initialStoreData)};
 const value=useMemo<Value>(()=>({data,loading,error,adminLoading,adminError,admin,live:!demo,loadAdmin,retry:loadPublic,save,remove,duplicate,reorder,saveSettings,saveDeliveryRates,updateOrder,resetDemo}),[data,loading,error,adminLoading,adminError,admin,loadAdmin,loadPublic,save,remove,duplicate,reorder,saveSettings,saveDeliveryRates,updateOrder]);
 if(loading)return <div className="grid min-h-dvh place-content-center bg-paper text-center"><p className="eyebrow">Loading live store data…</p></div>;
 if(error)return <div className="grid min-h-dvh place-content-center bg-paper px-6 text-center"><h1 className="display text-4xl">Store data unavailable.</h1><p className="mt-3 text-sm text-black/55">{error}</p><button className="btn btn-dark mx-auto mt-6" onClick={()=>void loadPublic()}>Try again</button></div>;
 return <Context.Provider value={value}>{children}</Context.Provider>}

export function useStore(){const value=useContext(Context);if(!value)throw new Error('StoreProvider required');return value}
export function navigationHref(item:NavigationItem){if(item.linkType==='category'||item.linkType==='collection')return `/collections/${item.target}`;return item.target.startsWith('/')?item.target:`/${item.target}`}
