import { useCallback, useEffect, useState } from "react";
import { FileSpreadsheet, Upload, X } from "lucide-react";
import { adminApi } from "../../services/adminApi";
import type { CourierProvider } from "../../types";

type Card = { id:string; courierProviderId:string; courierName:string; version:number; status:string; fileName:string; importedAt:string; activatedAt:string; total:number; valid:number; invalid:number; duplicate:number; new:number; changed:number };
type UploadResult = { id:string;version:number;fileName:string;headers:string[];suggestions:Record<string,string>;totalRows:number;preview:Array<{rowNumber:number;raw:Record<string,unknown>}> };
type Validation = { valid:number;invalid:number;duplicate:number;new:number;changed:number;total:number;preview:Array<{rowNumber:number;fromBranch:string;destinationDistrict:string;destinationCity:string;firstKgCharge:number|null;additionalKgCharge:number|null;errors:string[];status:string;changeKind:string}> };
const required = [
  ["fromBranch","From branch"], ["destinationDistrict","Destination district"], ["destinationCity","Destination city / area"],
  ["firstKgCharge","First kg charge"], ["additionalKgCharge","Additional kg charge"],
] as const;

async function base64(file:File){const bytes=new Uint8Array(await file.arrayBuffer());let binary="";for(let offset=0;offset<bytes.length;offset+=0x8000)binary+=String.fromCharCode(...bytes.subarray(offset,offset+0x8000));return btoa(binary);}

export function CourierRateSheetImport({couriers}:{couriers:CourierProvider[]}){
  const [open,setOpen]=useState(false),[cards,setCards]=useState<Card[]>([]),[courierId,setCourierId]=useState(""),[file,setFile]=useState<File|null>(null),[upload,setUpload]=useState<UploadResult|null>(null),[mapping,setMapping]=useState<Record<string,string>>({}),[validation,setValidation]=useState<Validation|null>(null),[review,setReview]=useState<{id:string;rows:Record<string,unknown>[]} | null>(null),[busy,setBusy]=useState(false),[error,setError]=useState("");
  const load=useCallback(async()=>{try{setCards(await adminApi.get<Card[]>("listCourierRateCards"));}catch(reason){setError(reason instanceof Error?reason.message:"Could not load rate cards.");}},[]);
  useEffect(()=>{void load();},[load]);
  const reset=()=>{setOpen(false);setFile(null);setUpload(null);setMapping({});setValidation(null);setError("");};
  async function uploadFile(){if(!file||!courierId)return setError("Choose a courier and .xlsx or .csv file.");setBusy(true);setError("");try{const result=await adminApi.post<UploadResult>("importCourierRateSheet",{courierProviderId:courierId,fileName:file.name,base64:await base64(file)});setUpload(result);setMapping(Object.fromEntries(Object.entries(result.suggestions).map(([header,field])=>[field,header])));await load();}catch(reason){setError(reason instanceof Error?reason.message:"Could not upload rate sheet.");}finally{setBusy(false);}}
  async function validate(){if(!upload)return;setBusy(true);setError("");try{setValidation(await adminApi.post<Validation>("validateCourierRateSheet",{id:upload.id,mapping}));await load();}catch(reason){setError(reason instanceof Error?reason.message:"Could not validate rate sheet.");}finally{setBusy(false);}}
  async function confirm(){if(!upload||!validation)return;setBusy(true);setError("");try{await adminApi.post("confirmCourierRateSheet",{id:upload.id});await load();reset();}catch(reason){setError(reason instanceof Error?reason.message:"Could not confirm rate sheet.");}finally{setBusy(false);}}
  async function status(card:Card,active:boolean){setBusy(true);setError("");try{await adminApi.post("setCourierRateCardStatus",{id:card.id,active});await load();}catch(reason){setError(reason instanceof Error?reason.message:"Could not update rate card.");}finally{setBusy(false);}}
  async function preview(card:Card){setBusy(true);try{const result=await adminApi.get<{rows:Record<string,unknown>[]}>("previewCourierRateCard",{id:card.id,page:"1"});setReview({id:card.id,rows:result.rows});}catch(reason){setError(reason instanceof Error?reason.message:"Could not load preview.");}finally{setBusy(false);}}
  return <section className="mt-5 rounded-2xl border border-black/[.07] bg-white p-5 shadow-[0_10px_40px_rgba(17,17,15,.035)] sm:p-7">
    <div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-[10px] font-semibold uppercase tracking-[.16em] text-black/40">Versioned pricing library</p><h2 className="mt-2 text-xl font-medium">Courier rate sheets</h2><p className="mt-2 max-w-2xl text-xs leading-5 text-black/45">Import large XLSX or CSV files as drafts. Review and activate a version without replacing manually managed delivery zones.</p></div><button type="button" className="btn btn-dark" onClick={()=>setOpen(true)}><Upload size={15}/> Import rate sheet</button></div>
    <div className="mt-5 grid gap-3">{cards.map(card=><article key={card.id} className="grid gap-3 rounded-xl border border-black/[.07] bg-[#faf9f6] p-4 md:grid-cols-[minmax(0,1fr)_auto_auto] md:items-center"><div><div className="flex flex-wrap items-center gap-2"><b className="text-sm">{card.courierName} · Version {card.version}</b><span className={`admin-status ${card.status==="active"?"admin-status--success":card.status==="draft"?"admin-status--warning":""}`}>{card.status}</span></div><p className="mt-1 text-[10px] text-black/45">{card.fileName} · imported {new Date(card.importedAt).toLocaleString()} · {card.total.toLocaleString()} rows</p><p className="mt-2 text-[10px] text-black/45">Valid {card.valid} · Invalid {card.invalid} · Duplicate {card.duplicate} · New {card.new} · Changed {card.changed}</p></div><button type="button" className="btn" disabled={busy} onClick={()=>void preview(card)}>Review</button>{card.status==="ready"||card.status==="inactive"?<button type="button" className="btn btn-dark" disabled={busy} onClick={()=>void status(card,true)}>Activate</button>:card.status==="active"?<button type="button" className="btn" disabled={busy} onClick={()=>void status(card,false)}>Deactivate</button>:<span/>}</article>)}{!cards.length&&<p className="rounded-xl border border-dashed border-black/10 p-6 text-center text-xs text-black/40">No imported rate cards yet.</p>}</div>
    <div className="mt-5 rounded-xl bg-amber-900/[.05] p-4 text-xs leading-5 text-amber-950/70"><b>Architecture only:</b> checkout still uses the existing flat-rate or delivery-zone configuration. Automatic additional-kilogram pricing requires a future product or variant shipping-weight field.</div>
    {error&&<p className="mt-4 text-xs text-red-800" role="alert">{error}</p>}
    {open&&<div className="fixed inset-0 z-[130] grid place-items-center bg-black/40 p-4"><section role="dialog" aria-modal="true" aria-label="Import courier rate sheet" className="max-h-[92vh] w-full max-w-5xl overflow-y-auto rounded-2xl bg-[#f8f6f1] shadow-2xl"><header className="sticky top-0 z-10 flex items-center justify-between border-b border-black/10 bg-[#f8f6f1]/95 p-5 backdrop-blur"><div><p className="admin-kicker">Server-side import</p><h2 className="mt-1 text-xl font-medium">Import rate sheet</h2></div><button type="button" className="grid h-11 w-11 place-items-center" onClick={reset} aria-label="Close"><X/></button></header><div className="space-y-5 p-5 sm:p-7">
      {!upload&&<div className="grid gap-4 md:grid-cols-2"><label className="text-xs">Courier provider<select className="field mt-2" value={courierId} onChange={event=>setCourierId(event.target.value)}><option value="">Choose courier</option>{couriers.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label className="text-xs">Rate sheet<input className="field mt-2" type="file" accept=".xlsx,.csv,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet,text/csv" onChange={event=>setFile(event.target.files?.[0]||null)}/></label><button type="button" className="btn btn-dark md:col-span-2" disabled={busy} onClick={()=>void uploadFile()}><FileSpreadsheet size={15}/>{busy?"Uploading and reading…":"Detect headers"}</button></div>}
      {upload&&!validation&&<><div className="grid grid-cols-2 gap-3 sm:grid-cols-3"><Metric label="Rows" value={upload.totalRows}/><Metric label="Headers" value={upload.headers.length}/><Metric label="Version" value={upload.version}/></div><div className="grid gap-3 md:grid-cols-2">{required.map(([field,label])=><label key={field} className="text-xs">{label}<select className="field mt-2" value={mapping[field]||""} onChange={event=>setMapping(current=>({...current,[field]:event.target.value}))}><option value="">Choose source column</option>{upload.headers.map(header=><option key={header}>{header}</option>)}</select></label>)}</div><div className="overflow-x-auto rounded-xl border border-black/10"><table className="min-w-full text-left text-xs"><thead><tr>{upload.headers.map(header=><th key={header} className="whitespace-nowrap border-b p-3">{header}</th>)}</tr></thead><tbody>{upload.preview.slice(0,5).map(row=><tr key={row.rowNumber}>{upload.headers.map(header=><td key={header} className="whitespace-nowrap border-b p-3 text-black/55">{String(row.raw[header]??"")}</td>)}</tr>)}</tbody></table></div><button type="button" className="btn btn-dark" disabled={busy} onClick={()=>void validate()}>{busy?"Validating on server…":"Validate mapped rows"}</button></>}
      {validation&&<><div className="grid grid-cols-2 gap-3 sm:grid-cols-5"><Metric label="Valid" value={validation.valid}/><Metric label="Invalid" value={validation.invalid}/><Metric label="Duplicate" value={validation.duplicate}/><Metric label="New" value={validation.new}/><Metric label="Changed" value={validation.changed}/></div><div className="overflow-x-auto rounded-xl border border-black/10"><table className="min-w-full text-left text-xs"><thead><tr>{["Row","State","District","City / area","First kg","Additional kg","Notes"].map(value=><th key={value} className="whitespace-nowrap border-b p-3">{value}</th>)}</tr></thead><tbody>{validation.preview.map(row=><tr key={row.rowNumber}><td className="p-3">{row.rowNumber}</td><td className="p-3 uppercase">{row.status}</td><td className="p-3">{row.destinationDistrict}</td><td className="p-3">{row.destinationCity}</td><td className="p-3">{row.firstKgCharge??"—"}</td><td className="p-3">{row.additionalKgCharge??"—"}</td><td className="p-3 text-red-800">{row.errors.join(" ")||row.changeKind}</td></tr>)}</tbody></table></div>{validation.invalid||validation.duplicate?<p className="rounded-xl bg-red-950/[.06] p-4 text-xs text-red-900">Correct the source file and import it again. Conflicting rows are retained in this draft and are never silently discarded.</p>:<div className="rounded-xl border border-black/10 bg-white p-4"><p className="text-sm font-medium">Ready to create draft rate card?</p><p className="mt-1 text-xs leading-5 text-black/45">This explicit confirmation stores the validated rows in the version. It will not affect checkout until separately activated—and activation still does not enable weight pricing.</p><button type="button" className="btn btn-dark mt-4" disabled={busy} onClick={()=>void confirm()}>{busy?"Confirming…":"Confirm imported draft"}</button></div>}</>}
    </div></section></div>}
    {review&&<div className="fixed inset-0 z-[130] grid place-items-center bg-black/40 p-4"><section className="max-h-[90vh] w-full max-w-5xl overflow-auto rounded-2xl bg-[#f8f6f1] p-5"><div className="flex justify-between"><h2 className="text-xl">Rate-card preview</h2><button onClick={()=>setReview(null)}><X/></button></div><pre className="mt-5 overflow-auto rounded-xl bg-black p-4 text-[10px] text-white">{JSON.stringify(review.rows,null,2)}</pre></section></div>}
  </section>;
}
function Metric({label,value}:{label:string;value:number}){return <div className="rounded-xl border border-black/[.07] bg-white p-4"><p className="text-[9px] uppercase tracking-[.12em] text-black/40">{label}</p><p className="mt-2 text-2xl">{value.toLocaleString()}</p></div>}
