import { useCallback, useEffect, useState } from "react";
import { FileSpreadsheet, Upload, X } from "lucide-react";
import { adminApi } from "../../services/adminApi";
import { initialCourierSelection } from "../../services/deliverySettings";
import type { CourierProvider } from "../../types";

type Card = { id:string; courierProviderId:string; courierName:string; version:number; status:string; fileName:string; importedAt:string; activatedAt:string; total:number; valid:number; invalid:number; duplicate:number; new:number; changed:number };
type UploadResult = { id:string;version:number;fileName:string;headers:string[];suggestions:Record<string,string>;totalRows:number;headerRowNumber:number;preview:Array<{rowNumber:number;raw:Record<string,unknown>}> };
type Validation = { valid:number;invalid:number;duplicate:number;new:number;changed:number;total:number;preview:Array<{rowNumber:number;errors:string[];status:string}> };
const required = [["fromBranch","From branch"],["destinationDistrict","Destination district"],["destinationCity","Destination city / area"],["firstKgCharge","First kg charge"],["additionalKgCharge","Additional kg charge"]] as const;
const steps=["Select file","Detect headers","Map columns","Validate","Review counts","Confirm draft"];
async function base64(file:File){const bytes=new Uint8Array(await file.arrayBuffer());let binary="";for(let offset=0;offset<bytes.length;offset+=0x8000)binary+=String.fromCharCode(...bytes.subarray(offset,offset+0x8000));return btoa(binary);}
export function CourierRateSheetImport({couriers,courierId:initialCourierId=""}:{couriers:CourierProvider[];courierId?:string}){
  const preferredCourier=initialCourierSelection(couriers,initialCourierId);
  const scopedCourier=couriers.find(courier=>courier.id===initialCourierId);
  const [open,setOpen]=useState(false),[cards,setCards]=useState<Card[]>([]),[courierId,setCourierId]=useState(preferredCourier),[file,setFile]=useState<File|null>(null),[upload,setUpload]=useState<UploadResult|null>(null),[mapping,setMapping]=useState<Record<string,string>>({}),[validation,setValidation]=useState<Validation|null>(null),[review,setReview]=useState<{rows:Record<string,unknown>[]} | null>(null),[busy,setBusy]=useState(false),[progress,setProgress]=useState(""),[error,setError]=useState("");
  const visibleCards=initialCourierId?cards.filter(card=>card.courierProviderId===initialCourierId):cards;
  const load=useCallback(async()=>{try{setCards(await adminApi.get<Card[]>("listCourierRateCards",initialCourierId?{courierProviderId:initialCourierId}:{}));}catch{setError("Rate cards could not be loaded. Please try again.");}},[initialCourierId]);
  useEffect(()=>{void load();},[load]);
  useEffect(()=>{if(initialCourierId&&couriers.some(c=>c.id===initialCourierId)&&courierId!==initialCourierId)setCourierId(initialCourierId);else if(courierId&&!couriers.some(c=>c.id===courierId))setCourierId("");},[courierId,couriers,initialCourierId]);
  const reset=()=>{setOpen(false);setFile(null);setUpload(null);setMapping({});setValidation(null);setProgress("");setError("");};
  async function uploadFile(){if(!file||!courierId)return setError("Choose a courier and .xlsx or .csv file.");setBusy(true);setProgress("Uploading…");setError("");try{const encoded=await base64(file);setProgress("Reading sheet…");const result=await adminApi.post<UploadResult>("importCourierRateSheet",{courierProviderId:courierId,fileName:file.name,base64:encoded});setUpload(result);setMapping(Object.fromEntries(Object.entries(result.suggestions).map(([header,field])=>[field,header])));setProgress("Headers detected");await load();}catch(reason){setError(reason instanceof Error?reason.message:"Rate sheet import failed. Please review the file and try again.");setProgress("");}finally{setBusy(false);}}
  async function validate(){if(!upload)return;setBusy(true);setProgress(`Validating ${upload.totalRows.toLocaleString()} rows…`);setError("");try{setValidation(await adminApi.post<Validation>("validateCourierRateSheet",{id:upload.id,mapping}));setProgress("Ready for review");await load();}catch{setError("Rate sheet validation failed. Please review the mapping and try again.");setProgress("");}finally{setBusy(false);}}
  async function confirmDraft(){if(!upload||!validation||validation.invalid>0)return;setBusy(true);setError("");try{await adminApi.post("confirmCourierRateSheet",{id:upload.id});await load();reset();}catch(reason){setError(reason instanceof Error?reason.message:"The draft could not be confirmed. Please try again.");}finally{setBusy(false);}}
  async function status(card:Card,active:boolean){setBusy(true);setError("");try{await adminApi.post("setCourierRateCardStatus",{id:card.id,active});await load();}catch(reason){setError(reason instanceof Error?reason.message:"The rate-card status could not be updated.");}finally{setBusy(false);}}
  async function preview(card:Card){setBusy(true);try{const result=await adminApi.get<{rows:Record<string,unknown>[]}>("previewCourierRateCard",{id:card.id,page:"1"});setReview({rows:result.rows});}catch(reason){setError(reason instanceof Error?reason.message:"The rate-card preview could not be loaded.");}finally{setBusy(false);}}
  return <section className="rounded-2xl border border-black/[.07] bg-white p-5 sm:p-7">
    <div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-[10px] font-semibold uppercase tracking-[.16em] text-black/40">Rate template</p><h2 className="mt-2 text-xl font-medium">{scopedCourier?.name ? `${scopedCourier.name} rate sheets` : "Imported pricing"}</h2><p className="mt-2 text-xs text-black/45">Versioned rate sheets stay with this courier and are not activated automatically.</p></div><button type="button" className="btn btn-dark" onClick={()=>setOpen(true)}><Upload size={15}/> Import rate sheet</button></div>
    <div className="mt-5 grid gap-3">{visibleCards.map(card=><article key={card.id} className="rounded-xl border border-black/[.07] bg-[#faf9f6] p-4"><div className="flex flex-wrap items-center gap-2"><b className="text-sm">Version {card.version}</b><span className={`admin-status ${card.status==="active"?"admin-status--success":card.status==="draft"?"admin-status--warning":""}`}>{card.status}</span></div><p className="mt-2 text-[10px] text-black/45">Imported {new Date(card.importedAt).toLocaleString()} · {card.total.toLocaleString()} source rows</p>{(card.invalid>0||card.duplicate>0)&&<p className="mt-2 text-[10px] text-black/50">{card.invalid.toLocaleString()} invalid · {card.duplicate.toLocaleString()} ignored duplicate/ambiguous rows</p>}<div className="mt-3 flex flex-wrap gap-2"><button type="button" className="btn" disabled={busy} onClick={()=>void preview(card)}>View rate card</button>{card.status==="ready"||card.status==="inactive"?<button type="button" className="btn btn-dark" disabled={busy} onClick={()=>void status(card,true)}>Activate</button>:card.status==="active"?<button type="button" className="btn" disabled={busy} onClick={()=>void status(card,false)}>Deactivate</button>:null}</div></article>)}{!visibleCards.length&&<p className="rounded-xl border border-dashed border-black/10 p-6 text-center text-xs text-black/40">No imported rate cards yet.</p>}</div>
    {error&&<p className="mt-4 text-xs text-red-800" role="alert">{error}</p>}
    {open&&<div className="fixed inset-0 z-[150] flex justify-end bg-black/40" onMouseDown={reset}><section role="dialog" aria-modal="true" aria-label="Import courier rate sheet" className="h-full w-full max-w-3xl overflow-y-auto bg-[#f8f6f1] shadow-2xl" onMouseDown={event=>event.stopPropagation()}><header className="sticky top-0 z-10 flex items-center justify-between border-b border-black/10 bg-[#f8f6f1]/95 p-5 backdrop-blur"><div><p className="admin-kicker">Guided import</p><h2 className="mt-1 text-xl font-medium">Import rate sheet</h2></div><button type="button" className="grid h-11 w-11 place-items-center" onClick={reset} aria-label="Close"><X/></button></header><div className="space-y-5 p-5 sm:p-7">
      <ol className="grid grid-cols-2 gap-2 text-[9px] uppercase tracking-[.1em] text-black/45 sm:grid-cols-3">{steps.map((step,index)=><li key={step} className="rounded-lg border border-black/[.07] bg-white px-2 py-3"><b className="mr-1 text-black">{index+1}</b>{step}</li>)}</ol>{progress&&<p className="rounded-xl bg-black px-4 py-3 text-xs text-white" role="status">{progress}</p>}
      {!upload&&<div className="grid gap-4 md:grid-cols-2">{initialCourierId?<div className="text-xs">Courier provider<p className="field mt-2 flex items-center">{scopedCourier?.name || "Selected courier"}</p></div>:<label className="text-xs">Courier provider<select className="field mt-2" value={courierId} onChange={event=>setCourierId(event.target.value)}><option value="">Choose courier</option>{couriers.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label>}<label className="text-xs">Rate sheet<input className="field mt-2" type="file" accept=".xlsx,.csv,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet,text/csv" onChange={event=>setFile(event.target.files?.[0]||null)}/></label><button type="button" className="btn btn-dark md:col-span-2" disabled={busy} onClick={()=>void uploadFile()}><FileSpreadsheet size={15}/>{busy?progress||"Working…":"Detect headers"}</button></div>}
      {upload&&!validation&&<><div className="grid grid-cols-2 gap-3 sm:grid-cols-4"><Metric label="Detected header row" value={upload.headerRowNumber}/><Metric label="Data rows" value={upload.totalRows}/><Metric label="Headers" value={upload.headers.length}/><Metric label="Version" value={upload.version}/></div><div className="rounded-xl border border-black/[.07] bg-white p-4"><p className="text-[10px] font-semibold uppercase tracking-[.14em] text-black/40">Detected mappings</p><div className="mt-3 grid gap-2 sm:grid-cols-2">{required.map(([field,label])=><p key={field} className="text-xs"><span className="text-black/45">{label}</span><b className="ml-2">{mapping[field]||"Not detected"}</b></p>)}</div></div><div className="grid gap-3 md:grid-cols-2">{required.map(([field,label])=><label key={field} className="text-xs">{label}<select className="field mt-2" value={mapping[field]||""} onChange={event=>setMapping(current=>({...current,[field]:event.target.value}))}><option value="">Choose source column</option>{upload.headers.map(header=><option key={header}>{header}</option>)}</select></label>)}</div><button type="button" className="btn btn-dark" disabled={busy} onClick={()=>void validate()}>{busy?progress:"Validate mapped rows"}</button></>}
      {validation&&<><div className="grid grid-cols-2 gap-3 sm:grid-cols-5"><Metric label="Usable" value={validation.valid}/><Metric label="Invalid" value={validation.invalid}/><Metric label="Ignored" value={validation.duplicate}/><Metric label="New" value={validation.new}/><Metric label="Changed" value={validation.changed}/></div>{validation.invalid>0?<p className="rounded-xl bg-red-950/[.06] p-4 text-xs text-red-900">{validation.invalid.toLocaleString()} invalid rows need to be corrected in the source file before this draft can be confirmed.</p>:<>{validation.duplicate>0&&<p className="rounded-xl bg-amber-950/[.06] p-4 text-xs text-amber-950">{validation.duplicate.toLocaleString()} duplicate, blank, or ambiguous rows will be safely ignored. Exact usable destinations remain available; unmatched addresses use the courier's configured fallback delivery area.</p>}<button type="button" className="btn btn-dark" disabled={busy} onClick={()=>void confirmDraft()}>{busy?"Confirming…":"Confirm imported draft"}</button></>}</>}
    </div></section></div>}
    {review&&<div className="fixed inset-0 z-[160] grid place-items-center bg-black/40 p-4"><section className="max-h-[90vh] w-full max-w-5xl overflow-auto rounded-2xl bg-[#f8f6f1] p-5"><div className="flex justify-between"><h2 className="text-xl">Rate-card preview</h2><button onClick={()=>setReview(null)} aria-label="Close preview"><X/></button></div><pre className="mt-5 overflow-auto rounded-xl bg-black p-4 text-[10px] text-white">{JSON.stringify(review.rows,null,2)}</pre></section></div>}
  </section>;
}
function Metric({label,value}:{label:string;value:number}){return <div className="rounded-xl border border-black/[.07] bg-white p-4"><p className="text-[9px] uppercase tracking-[.12em] text-black/40">{label}</p><p className="mt-2 text-2xl">{value.toLocaleString()}</p></div>}
