import { useCallback,useEffect,useRef,useState } from "react";
import type { HomepageData,Product,ProductSummary,ShopResponse,SizeChart } from "../types";
const base=import.meta.env.VITE_API_BASE||"/api";
function useRequest<T>(path:string){const [data,setData]=useState<T|null>(null),[loading,setLoading]=useState(Boolean(path)),[error,setError]=useState(""),controller=useRef<AbortController>();const load=useCallback(async()=>{if(!path){setLoading(false);return;}controller.current?.abort();const request=new AbortController();controller.current=request;setLoading(true);setError("");try{const response=await fetch(base+path,{signal:request.signal}),payload=await response.json() as T&{error?:string};if(!response.ok)throw new Error(payload.error||"Content temporarily unavailable");if(!request.signal.aborted)setData(payload);}catch(reason){if(!(reason instanceof DOMException&&reason.name==="AbortError"))setError(reason instanceof Error?reason.message:"Content temporarily unavailable");}finally{if(!request.signal.aborted)setLoading(false);}},[path]);useEffect(()=>{void load();return()=>controller.current?.abort();},[load]);return{data,loading,error,retry:load};}
export const useHomepageData=()=>useRequest<Pick<HomepageData,"products">>("/home");
export const useProduct=(slug:string)=>useRequest<{product:Product}>(`/products/${encodeURIComponent(slug)}`);
export const useRecommendations=(categoryId:string,productId:string)=>useRequest<ProductSummary[]>(categoryId&&productId?`/recommendations?category=${encodeURIComponent(categoryId)}&exclude=${encodeURIComponent(productId)}`:"");
export async function getSizeChart(id:string){const response=await fetch(`${base}/size-chart?id=${encodeURIComponent(id)}`),payload=await response.json() as SizeChart&{error?:string};if(!response.ok)throw new Error(payload.error||"Size guide temporarily unavailable");return payload;}
export const useShopProducts=(query:string)=>useRequest<ShopResponse>(`/products?${query}`);
export type PublicCourier={id:string;pricingMode:"zone"|"flat";flatRate:number;active:boolean};
export type PublicDeliveryRate={courierProviderId?:string;fee:number;active:boolean;districts:string[];cities:string[];postalCodes:string[];fallback:boolean;sortOrder:number};
export const useCheckoutConfig=()=>useRequest<{settings:Array<{key:string;value:unknown}>;couriers:PublicCourier[];deliveryRates:PublicDeliveryRate[]}>("/checkout-config");
