import { useCallback,useEffect,useRef,useState } from "react";
import type { HomepageData,Product,ProductSummary,ShopResponse,SizeChart } from "../types";
import { fetchPublic,getCachedPublic,revalidatePublic,subscribePublic } from "../services/publicDataCache";
import { shopSearchPolicy } from "../services/shopSearchPolicy";
type RequestOptions<T>={ttlMs?:number;persist?:boolean;maxEntries?:number;revalidateFresh?:boolean;loadingWhileRevalidate?:(cached:T)=>boolean;noStore?:boolean};
function useRequest<T>(path:string,options:RequestOptions<T>={}){const cached=path&&!options.noStore?getCachedPublic<T>(path,options):undefined,[data,setData]=useState<T|null>(cached??null),[loading,setLoading]=useState(Boolean(path&&(!cached||options.noStore||(options.revalidateFresh&&options.loadingWhileRevalidate?.(cached))))),[error,setError]=useState(""),requestId=useRef(0),renderedPath=useRef(path);const {ttlMs,persist,maxEntries,revalidateFresh,loadingWhileRevalidate,noStore}=options;
  const load=useCallback(async(force=false)=>{const id=++requestId.current;if(!path){setLoading(false);return;}const current=noStore?undefined:getCachedPublic<T>(path,{persist});if(noStore||!current||(force&&loadingWhileRevalidate?.(current)))setLoading(true);setError("");try{const payload=noStore?await fetchPublic<T>(path,{noStore:true}):force?await revalidatePublic<T>(path,{ttlMs,persist,maxEntries}):await fetchPublic<T>(path,{ttlMs,persist,maxEntries});if(id===requestId.current)setData(payload);}catch(reason){if(id===requestId.current)setError(reason instanceof Error?reason.message:"Content temporarily unavailable");}finally{if(id===requestId.current)setLoading(false);}},[loadingWhileRevalidate,maxEntries,noStore,path,persist,ttlMs]);
  useEffect(()=>{requestId.current+=1;renderedPath.current=path;if(!path){setData(null);setLoading(false);return;}const current=noStore?undefined:getCachedPublic<T>(path,{persist});setData(current??null);setLoading(Boolean(noStore||!current||(current&&revalidateFresh&&loadingWhileRevalidate?.(current))));const unsubscribe=noStore?()=>{}:subscribePublic<T>(path,next=>{setData(next);setLoading(false);setError("");});void load(Boolean(current&&revalidateFresh));return unsubscribe;},[load,loadingWhileRevalidate,noStore,path,persist,revalidateFresh]);const pathChanged=renderedPath.current!==path;return{data:pathChanged?null:data,loading:pathChanged||loading,error:pathChanged?"":error,retry:()=>load(true)};}
export const useHomepageData=()=>useRequest<Pick<HomepageData,"products">>("/home",{ttlMs:60_000,persist:true,revalidateFresh:true});
export const useProduct=(slug:string)=>useRequest<{product:Product}>(slug?`/products/${encodeURIComponent(slug)}`:"",{ttlMs:60_000,persist:true});
export const useRecommendations=(categoryId:string,productId:string)=>useRequest<ProductSummary[]>(categoryId&&productId?`/recommendations?category=${encodeURIComponent(categoryId)}&exclude=${encodeURIComponent(productId)}`:"",{ttlMs:300_000});
export const getSizeChart=(id:string)=>fetchPublic<SizeChart>(`/size-chart?id=${encodeURIComponent(id)}`,{ttlMs:300_000});
const emptyShopResult=(cached:ShopResponse)=>cached.items.length===0;
export const useShopProducts=(query:string)=>{const policy=shopSearchPolicy(query);return useRequest<ShopResponse>(`/products?${query}`,{ttlMs:25_000,maxEntries:40,revalidateFresh:policy.revalidateFresh,loadingWhileRevalidate:emptyShopResult,noStore:policy.search});};
export type PublicFulfillmentMethod={type:"flat"|"area_group"|"pickup";displayName:string;fee:number|null;minimumDeliveryDays:number|null;maximumDeliveryDays:number|null};
export type PublicPickupLocation={id:string;name:string;address:string;instructions:string;sortOrder:number};
export const useCheckoutConfig=()=>useRequest<{settings:Array<{key:string;value:unknown}>;methods:PublicFulfillmentMethod[];locations:Array<{id:string;district:string;town:string;postcode?:string;aliases:string[]}>;pickupLocations:PublicPickupLocation[]}>("/checkout-config",{ttlMs:15_000});
