import {z} from 'zod';
export interface Env{APPS_SCRIPT_URL:string;APPS_SCRIPT_SECRET:string;SESSION_SECRET:string;ADMIN_USERNAME:string;ADMIN_PASSWORD_HASH:string;CLOUDINARY_CLOUD_NAME:string;CLOUDINARY_API_KEY:string;CLOUDINARY_API_SECRET:string;ALLOWED_ORIGIN:string}
export const json=(data:unknown,status=200,headers:Record<string,string>={})=>new Response(JSON.stringify(data),{status,headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store',...headers}});
const enc=new TextEncoder();const b64=(buf:ArrayBuffer)=>btoa(String.fromCharCode(...new Uint8Array(buf))).replace(/=/g,'').replace(/\+/g,'-').replace(/\//g,'_');
async function hmac(value:string,secret:string){const key=await crypto.subtle.importKey('raw',enc.encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']);return b64(await crypto.subtle.sign('HMAC',key,enc.encode(value)))}
export async function makeSession(secret:string){const payload=b64(enc.encode(JSON.stringify({sub:'owner',exp:Date.now()+1000*60*60*8})).buffer);return `${payload}.${await hmac(payload,secret)}`}
export async function validSession(request:Request,secret:string){const value=request.headers.get('Cookie')?.match(/(?:^|; )zevenra_session=([^;]+)/)?.[1];if(!value)return false;const [payload,sig]=value.split('.');if(!payload||!sig||await hmac(payload,secret)!==sig)return false;try{const data=JSON.parse(atob(payload.replace(/-/g,'+').replace(/_/g,'/'))) as {exp:number};return data.exp>Date.now()}catch{return false}}
export function validOrigin(request:Request,env:Env){if(['GET','HEAD','OPTIONS'].includes(request.method))return true;const origin=request.headers.get('Origin');return !origin||origin===env.ALLOWED_ORIGIN||new URL(request.url).origin===origin}
export async function callScript(env:Env,action:string,payload:unknown){const r=await fetch(env.APPS_SCRIPT_URL,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({token:env.APPS_SCRIPT_SECRET,action,payload})});if(!r.ok)throw new Error('Upstream unavailable');const data=await r.json() as {ok:boolean;data?:unknown;error?:string};if(!data.ok)throw new Error(data.error||'Upstream rejected request');return data.data}
export const orderSchema=z.object({customerName:z.string().min(2).max(100),phone:z.string().regex(/^[+\d][\d\s-]{8,14}$/),whatsapp:z.string().max(20).optional(),email:z.string().email().or(z.literal('')).optional(),address1:z.string().min(5).max(180),address2:z.string().max(180).optional(),city:z.string().min(2).max(80),district:z.string().min(2).max(80),postalCode:z.string().max(12).optional(),deliveryNotes:z.string().max(300).optional(),paymentMethod:z.enum(['cod','bank']),items:z.array(z.object({productId:z.string().min(1),variantId:z.string().min(1),quantity:z.number().int().min(1).max(10)})).min(1).max(30)}).strict();
export const adminLoginSchema=z.object({username:z.string().min(1).max(100),password:z.string().min(8).max(200)}).strict();
export async function sha256(value:string){return b64(await crypto.subtle.digest('SHA-256',enc.encode(value)))}
