import {Link} from 'react-router-dom';
import {Minus,Plus} from 'lucide-react';
import {useCart} from '../features/cart/CartContext';
import {useStore} from '../features/store/StoreContext';
import {money} from '../config/site';
import {Seo} from '../components/Seo';

export default function CartPage(){
 const c=useCart(),{data}=useStore();
 const currentPrice=(item:typeof c.items[number])=>data.products.find(p=>p.id===item.productId&&p.status==='published')?.price??item.unitPrice;
 const valid=(item:typeof c.items[number])=>{if(item.isPreorder)return false;const product=data.products.find(p=>p.id===item.productId&&p.status==='published'),variant=product?.variants.find(v=>v.id===item.variantId&&v.active);return Boolean(product&&variant&&variant.stock>=item.quantity)};
 const displaySubtotal=c.items.reduce((sum,item)=>sum+currentPrice(item)*item.quantity,0),canCheckout=c.items.length>0&&c.items.every(valid);
 return <div className="container min-h-[70vh] pb-24 pt-36 lg:pt-44"><Seo title="Your Bag"/><p className="eyebrow text-ink/50">Your selection</p><h1 className="display mt-3 text-5xl md:text-7xl">Bag · {c.count}</h1>{!c.items.length?<div className="mt-20 border-y hairline py-24 text-center"><p className="display text-4xl">Nothing held, yet.</p><Link to="/shop" className="btn mt-7">Explore the collection</Link></div>:<div className="mt-10 grid gap-12 lg:grid-cols-[1fr_380px]"><div>{c.items.map(i=>{const available=valid(i);return <div key={i.variantId} className="flex gap-4 border-t hairline py-6 sm:gap-7">{i.image?<img src={i.image} alt={i.name} className="h-36 w-24 object-cover sm:h-48 sm:w-36"/>:<div className="h-36 w-24 bg-[#e7e1d7] sm:h-48 sm:w-36"/>}<div className="flex flex-1 flex-col"><div className="flex justify-between gap-3"><div><h2>{i.name}</h2><p className="mt-2 text-xs text-ink/55">{i.color} / {i.size}</p>{i.isPreorder&&<p className="mt-2 text-xs text-red-800">Pre-orders now use a separate request flow and cannot be checked out from the bag.</p>}{!available&&!i.isPreorder&&<p className="mt-2 text-xs text-red-800">This option is no longer available. Please remove it or choose another option.</p>}</div><p className="text-sm">{money(currentPrice(i)*i.quantity)}</p></div><div className="mt-auto flex items-center gap-4"><button aria-label={'Decrease '+i.name} onClick={()=>c.quantity(i.variantId,i.quantity-1)}><Minus size={16}/></button><span>{i.quantity}</span><button aria-label={'Increase '+i.name} disabled={i.maxStock!==undefined&&i.quantity>=i.maxStock} onClick={()=>c.quantity(i.variantId,i.quantity+1)}><Plus size={16}/></button><button onClick={()=>c.remove(i.variantId)} className="ml-auto text-xs underline">Remove</button></div></div></div>})}</div><aside className="h-fit border border-line p-6 lg:sticky lg:top-32"><p className="eyebrow">Summary</p><div className="mt-7 space-y-4 text-sm"><div className="flex justify-between"><span>Subtotal</span><span>{money(displaySubtotal)}</span></div><div className="flex justify-between text-ink/55"><span>Delivery</span><span>Calculated at checkout</span></div></div><div className="my-6 border-t hairline"/><p className="text-xs leading-5 text-ink/55">Taxes, if applicable, are included. Your order is awaiting confirmation until reviewed by ZEVENRA.</p>{canCheckout?<Link to="/checkout" className="btn btn-dark mt-6 w-full">Checkout</Link>:<><p className="mt-5 text-xs leading-5 text-red-800">Update or remove unavailable items before checkout.</p><button disabled className="btn btn-dark mt-3 w-full opacity-40">Checkout</button></>}</aside></div>}</div>
}
