import { useEffect, useMemo, useRef, useState, type FormEvent, type ReactNode } from "react";
import { AnimatePresence, motion } from "framer-motion";
import { Banknote, Check, CheckCircle2, Minus, Plus, Trash2, Upload, WalletCards, X } from "lucide-react";
import { Navigate, useNavigate } from "react-router-dom";
import { z } from "zod";
import { Seo } from "../components/Seo";
import { money } from "../config/site";
import { useCustomerAuth } from "../features/account/CustomerAuthContext";
import { useCart } from "../features/cart/CartContext";
import { useStore } from "../features/store/StoreContext";
import { api } from "../services/api";
import { uploadPaymentReceipt } from "../services/paymentReceiptUpload";
import type { PaymentMethod } from "../types";
import { checkoutCourier, cityDistrictMismatch, deliveryQuote } from "../utils/delivery";
import { checkoutAmounts } from "../utils/checkoutAmounts";
import { paymentReadinessMessage, postalCodeError } from "../utils/checkoutValidation";
import { useCheckoutConfig } from "../hooks/usePublicData";

const districts = ["Ampara","Anuradhapura","Badulla","Batticaloa","Colombo","Galle","Gampaha","Hambantota","Jaffna","Kalutara","Kandy","Kegalle","Kilinochchi","Kurunegala","Mannar","Matale","Matara","Monaragala","Mullaitivu","Nuwara Eliya","Polonnaruwa","Puttalam","Ratnapura","Trincomalee","Vavuniya"] as const;
const schema = z.object({
  customerName: z.string().trim().min(2,"Enter your full name.").max(100).regex(/^[\p{L}\p{M} .'-]+$/u,"Full name should contain letters only."),
  phone: z.string().trim().regex(/^[+\d][\d\s-]{8,14}$/,"Enter a valid mobile number."),
  address1: z.string().trim().min(5,"Enter your delivery address.").max(180),
  city: z.string().trim().min(2,"Enter your city / area.").max(80),
  district: z.enum(districts,{ errorMap:()=>({ message:"Choose your district." }) }),
  postalCode: z.string().trim().refine(value=>!value||/^\d+$/.test(value),"Postal code must contain numbers only.").refine(value=>!value||value.length===5,"Postal code must be exactly 5 digits.").optional(),
  paymentMethod: z.enum(["cod","bank"]), paymentReference: z.string().trim().max(100).optional(), paymentReceiptUrl: z.string().url().optional(),
});
const enter = { initial:{ opacity:0,y:12 }, animate:{ opacity:1,y:0 } };

export default function CheckoutPage() {
  const cart=useCart(), navigate=useNavigate(), formRef=useRef<HTMLFormElement>(null), {data}=useStore(), checkout=useCheckoutConfig(), {user}=useCustomerAuth(), raw=Object.fromEntries((checkout.data?.settings||[]).map(row=>[row.key,row.value])), bool=(value:unknown)=>value===true||String(value).toLowerCase()==="true", settings={...data.settings,codEnabled:bool(raw.codEnabled),bankEnabled:bool(raw.bankEnabled??raw.bankTransferEnabled),bankName:String(raw.bankName||""),accountName:String(raw.accountName??raw.bankAccountName??""),accountNumber:String(raw.accountNumber??raw.bankAccountNumber??""),branch:String(raw.branch??raw.bankBranch??""),bankInstructions:String(raw.bankInstructions||""),deliveryEnabled:bool(raw.deliveryEnabled),deliveryFee:Number(raw.deliveryFee??raw.deliveryFlatFee)||0,freeDeliveryThreshold:Number(raw.freeDeliveryThreshold)||0,defaultCourierProviderId:String(raw.defaultCourierProviderId||""),storeOpen:bool(raw.storeOpen),ordersEnabled:bool(raw.ordersEnabled)};
  const savedName=[user?.firstName,user?.lastName].filter(Boolean).join(" ");
  const bankConfigured=Boolean(settings.bankEnabled&&settings.bankName.trim()&&settings.accountName.trim()&&settings.accountNumber.trim());
  const availablePayments=useMemo<PaymentMethod[]>(()=>[...(settings.codEnabled?["cod" as const]:[]),...(bankConfigured?["bank" as const]:[])],[settings.codEnabled,bankConfigured]);
  const [payment,setPayment]=useState<PaymentMethod>(availablePayments[0]||"cod"), [district,setDistrict]=useState(user?.district||""), [city,setCity]=useState(user?.city||""), [postalCode,setPostalCode]=useState(user?.postalCode||""), [postalTouched,setPostalTouched]=useState(false);
  const [error,setError]=useState(""), [fieldErrors,setFieldErrors]=useState<Record<string,string>>({}), [busy,setBusy]=useState(false), [receiptBusy,setReceiptBusy]=useState(false), [receiptUrl,setReceiptUrl]=useState(""), [receiptName,setReceiptName]=useState("");
  useEffect(()=>{ if(!availablePayments.includes(payment)&&availablePayments[0]) setPayment(availablePayments[0]); },[availablePayments,payment]);
  if(!cart.items.length||cart.items.some(i=>i.isPreorder)) return <Navigate to="/cart" replace/>;
  if(checkout.loading)return <main className="container min-h-[70vh] py-20"><div className="home-skeleton"><div/><div/><div/><div/></div></main>;
  if(checkout.error)return <main className="container grid min-h-[70vh] place-content-center py-20 text-center"><h1 className="display text-5xl">Checkout is temporarily unavailable.</h1><p className="mt-3 text-sm text-ink/55">Your bag is safe. Please try again.</p><button className="btn mx-auto mt-6" onClick={()=>void checkout.retry()}>Retry</button></main>;
  const stockFor=(_pid:string,vid:string)=>cart.live[vid]?.stock??0;
  const price=(i:(typeof cart.items)[number])=>cart.live[i.variantId]?.currentPrice??i.unitPrice;
  const subtotal=cart.items.reduce((sum,i)=>sum+price(i)*i.quantity,0),postalFormatError=postalCodeError(postalCode),addressReady=Boolean(district&&city.trim().length>=2&&!postalFormatError);
  const courier=checkoutCourier(checkout.data?.couriers||[],settings.defaultCourierProviderId), quote=addressReady?deliveryQuote(courier,checkout.data?.deliveryRates||[],{district,city,postalCode}):undefined, deliveryReady=!settings.deliveryEnabled||Boolean(quote);
  const deliveryFee=settings.freeDeliveryThreshold>0&&subtotal>=settings.freeDeliveryThreshold?0:settings.deliveryEnabled?(quote?.fee??0):0,amounts=checkoutAmounts(subtotal,deliveryFee,!settings.deliveryEnabled||(addressReady&&deliveryReady));
  const deliveryMismatch=Boolean(addressReady&&settings.deliveryEnabled&&!quote),cityMismatch=deliveryMismatch&&cityDistrictMismatch(checkout.data?.deliveryRates||[],{district,city},courier?.id),paymentStatus=paymentReadinessMessage({city,district,postalError:postalFormatError,deliveryEnabled:settings.deliveryEnabled,quoteReady:Boolean(quote)});
  const clearError=(name:string)=>setFieldErrors(current=>{if(!current[name])return current;const next={...current};delete next[name];return next;});
  const focusFirst=(errors:Record<string,string>)=>requestAnimationFrame(()=>{const el=formRef.current?.querySelector<HTMLElement>(`[name="${Object.keys(errors)[0]}"]`);el?.scrollIntoView({behavior:"smooth",block:"center"});el?.focus({preventScroll:true});});
  async function uploadReceipt(file?:File){if(!file)return;setReceiptBusy(true);setError("");try{setReceiptUrl(await uploadPaymentReceipt(file));setReceiptName(file.name);}catch(reason){setReceiptUrl("");setReceiptName("");setError(reason instanceof Error?reason.message:"Could not upload the payment receipt.");}finally{setReceiptBusy(false);}}
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setError("");setFieldErrors({});
    if(!settings.storeOpen||!settings.ordersEnabled){setError("Online ordering is temporarily unavailable. Please contact us for assistance.");return;}
    if(!availablePayments.length){setError("No payment method is currently available.");return;}
    if(payment==="bank"&&!receiptUrl){const e={paymentReceiptUrl:"Upload your bank transfer receipt before placing the order."};setFieldErrors(e);setError("Please check the highlighted payment detail.");focusFirst(e);return;}
    for(const item of cart.items)if(stockFor(item.productId,item.variantId)<item.quantity){setError(`${item.name} is no longer available in that quantity. Please update your cart.`);return;}
    const raw=Object.fromEntries(new FormData(event.currentTarget)), parsed=schema.safeParse({...raw,paymentMethod:payment,paymentReceiptUrl:payment==="bank"?receiptUrl:undefined,paymentReference:payment==="bank"?String(raw.paymentReference||""):undefined});
    if(!parsed.success){const e:Record<string,string>={};for(const issue of parsed.error.issues){const key=String(issue.path[0]||"form");if(!e[key])e[key]=issue.message;}setFieldErrors(e);setError("Please fix the highlighted fields before placing your order.");focusFirst(e);return;}
    if(settings.deliveryEnabled&&!quote){const e={city:"Check your city / area.",district:"Choose your district."};setFieldErrors(e);setError("We could not calculate delivery from these details.");focusFirst(e);return;}
    setBusy(true);try{const order=await api.createOrder({...parsed.data,postalCode:parsed.data.postalCode||"",items:cart.items});sessionStorage.setItem(`order:${order.orderId}`,JSON.stringify(order));cart.clear();navigate(`/order/${order.orderId}`);}catch(reason){setError(reason instanceof Error?reason.message:"We could not submit your order. Your cart is safe—please try again.");}finally{setBusy(false);}
  }
  const stockReady=cart.items.every(item=>stockFor(item.productId,item.variantId)>=item.quantity),placeDisabled=busy||receiptBusy||!amounts.ready||!stockReady||(payment==="bank"&&!receiptUrl)||!availablePayments.length||!settings.storeOpen||!settings.ordersEnabled;
  return <main className="container min-w-0 py-6 sm:py-9 lg:py-12"><Seo title="Checkout"/><div className="mx-auto max-w-5xl"><div className="mb-6 max-w-xl"><p className="eyebrow text-bronze">Complete your order</p><h1 className="display mt-2 text-4xl sm:text-5xl">Checkout</h1><p className="mt-2 text-xs leading-5 text-ink/55">{user?`Signed in as ${user.email}. This order will appear in My Orders.`:"Checking out as a guest. Your details are used only to fulfil this order."}</p></div>
    <form ref={formRef} onSubmit={submit} noValidate className="min-w-0 space-y-4">
      <Section number="01" title="Order details"><div className="divide-y divide-black/10 border-y border-black/10">{cart.items.map(item=>{const stock=stockFor(item.productId,item.variantId),unitPrice=price(item);return <div key={item.variantId} className="grid grid-cols-[56px_minmax(0,1fr)] gap-3 py-3 sm:grid-cols-[64px_minmax(0,1fr)_auto] sm:items-center"><div className="grid aspect-[4/5] place-items-center overflow-hidden bg-[#f3eee7]">{item.image&&<img src={item.image} alt={item.name} className="h-full w-full object-contain"/>}</div><div className="min-w-0"><p className="text-sm font-medium">{item.name}</p><p className="mt-0.5 text-[10px] text-ink/50">Colour: {item.color} · Size: {item.size}</p><div className="mt-2 inline-flex h-10 items-center border border-black/15 bg-white/40"><button type="button" aria-label={`Decrease ${item.name}`} className="grid h-full w-10 place-items-center" onClick={()=>cart.quantity(item.variantId,item.quantity-1)}><Minus size={11}/></button><span className="w-7 text-center text-[10px]">{item.quantity}</span><button type="button" aria-label={`Increase ${item.name}`} disabled={stock<=item.quantity} className="grid h-full w-10 place-items-center disabled:opacity-30" onClick={()=>cart.quantity(item.variantId,item.quantity+1)}><Plus size={11}/></button></div>{stock<item.quantity&&<p className="mt-1 text-[10px] text-red-800">Only {stock} currently available.</p>}</div><div className="col-span-2 flex items-center justify-between gap-3 sm:col-span-1 sm:justify-end"><b className="text-sm">{money(unitPrice*item.quantity)}</b><button type="button" aria-label={`Remove ${item.name}`} onClick={()=>cart.remove(item.variantId)} className="grid min-h-10 min-w-10 place-items-center text-red-800"><Trash2 size={14}/></button></div></div>;})}</div><div className="ml-auto mt-4 max-w-sm space-y-2 text-xs"><SummaryLine label="Subtotal" value={money(amounts.subtotal)}/><SummaryLine label="Delivery" value={!amounts.ready?"Calculated after delivery details":amounts.deliveryFee?money(amounts.deliveryFee):"Free"}/><div className="border-t border-black/15 pt-2"><SummaryLine label="Total" value={amounts.total===undefined?"—":money(amounts.total)}/></div></div></Section>
      <Section number="02" title="Delivery information"><div className="grid gap-x-4 gap-y-3 sm:grid-cols-2"><Field name="customerName" label="Full Name" required autoComplete="name" defaultValue={savedName} error={fieldErrors.customerName} onChange={()=>clearError("customerName")}/><Field name="phone" label="Phone" required type="tel" autoComplete="tel" placeholder="0771234567" defaultValue={user?.mobile||""} error={fieldErrors.phone} onChange={()=>clearError("phone")}/><Field name="address1" label="Address" required wide autoComplete="address-line1" defaultValue={user?.address1||""} error={fieldErrors.address1} onChange={()=>clearError("address1")}/><Field name="city" label="City / Area" required autoComplete="address-level2" defaultValue={user?.city||""} error={fieldErrors.city} onChange={value=>{setCity(value);clearError("city");}}/><label className="label">District <i>*</i><select name="district" required aria-invalid={Boolean(fieldErrors.district)} aria-describedby={fieldErrors.district?"district-error":undefined} className={`field mt-1.5 ${fieldErrors.district?"border-red-700":""}`} value={district} onChange={event=>{setDistrict(event.target.value);clearError("district");}}><option value="" disabled>Select district</option>{districts.map(value=><option key={value}>{value}</option>)}</select><InlineError id="district-error" message={fieldErrors.district}/></label><Field name="postalCode" label="Postal Code" autoComplete="postal-code" inputMode="numeric" maxLength={10} placeholder="10250" value={postalCode} error={(postalTouched?postalFormatError:"")||fieldErrors.postalCode} onBlur={()=>setPostalTouched(true)} onChange={value=>{setPostalCode(value);clearError("postalCode");}}/></div>{deliveryMismatch&&<p role="alert" className="mt-4 border-l-2 border-red-800 bg-red-950/[.04] p-3 text-xs leading-5 text-red-900">{cityMismatch?"Check that your city / area matches the selected district.":"We couldn't calculate delivery for these details. Check your city, district, and postal code."}</p>}</Section>
      <Section number="03" title="Payment"><div className="grid gap-3 sm:grid-cols-2">{availablePayments.map(value=>{const selected=payment===value;return <motion.label whileTap={{scale:.99}} key={value} className={`relative flex min-h-20 cursor-pointer items-center gap-3 border p-3 ${selected?"border-bronze bg-bronze/[.06]":"border-line bg-white/20"}`}><input className="sr-only" type="radio" name="pay" checked={selected} onChange={()=>setPayment(value)}/>{value==="cod"?<Banknote size={20}/>:<WalletCards size={20}/>}<span className="min-w-0 flex-1"><b className="block text-xs uppercase tracking-[.1em]">{value==="cod"?"Cash on Delivery":"Bank Transfer"}</b><small className="mt-0.5 block text-[10px] normal-case text-ink/50">{value==="cod"?"Pay when your order arrives.":"Transfer before confirmation."}</small></span><span className={`grid h-5 w-5 place-items-center rounded-full border ${selected?"border-bronze bg-bronze text-white":"border-black/20"}`}>{selected&&<Check size={12}/>}</span></motion.label>;})}</div>{payment==="cod"?<PaymentAmount label="Pay on delivery" amounts={amounts} status={paymentStatus}/>:<AnimatePresence initial={false}>{bankConfigured&&<motion.div initial={{opacity:0,height:0}} animate={{opacity:1,height:"auto"}} exit={{opacity:0,height:0}} className="overflow-hidden"><div className="mt-4 space-y-4 border border-line bg-white/35 p-4"><div className="grid gap-x-4 gap-y-2 text-xs leading-5 sm:grid-cols-2"><BankDetail label="Bank" value={settings.bankName}/><BankDetail label="Account name" value={settings.accountName}/><BankDetail label="Account number" value={settings.accountNumber}/>{settings.branch&&<BankDetail label="Branch" value={settings.branch}/>}</div><BankTransferAmount amounts={amounts} status={paymentStatus}/>{settings.bankInstructions&&<p className="text-xs text-ink/60">{settings.bankInstructions}</p>}<Field name="paymentReference" label="Payment reference" wide/><ReceiptUpload ready={amounts.ready} busy={receiptBusy} url={receiptUrl} name={receiptName} error={fieldErrors.paymentReceiptUrl} clearError={()=>clearError("paymentReceiptUrl")} upload={uploadReceipt} remove={()=>{setReceiptUrl("");setReceiptName("");}}/></div></motion.div>}</AnimatePresence>}<FinalAction payment={payment} amounts={amounts} receiptReady={Boolean(receiptUrl)} error={error} disabled={placeDisabled} busy={busy} receiptBusy={receiptBusy}/></Section>
    </form></div></main>;
}
function Section({number,title,children}:{number:string;title:string;children:ReactNode}){return <motion.section {...enter} className="border border-black/10 bg-white/25 p-4 sm:p-5"><div className="mb-4 flex items-center gap-3"><span className="grid h-7 w-7 place-items-center rounded-full border border-bronze/50 text-[9px] text-bronze">{number}</span><h2 className="display text-2xl">{title}</h2></div>{children}</motion.section>;}
function InlineError({message,id}:{message?:string;id?:string}){return message?<span id={id} className="mt-1.5 block text-[11px] normal-case leading-5 tracking-normal text-red-800">{message}</span>:null;}
function PaymentAmount({label,amounts,status}:{label:string;amounts:ReturnType<typeof checkoutAmounts>;status:string}){return <div className="mt-4 border border-bronze/35 bg-bronze/[.07] p-4">{amounts.total===undefined?<p className="text-sm font-medium">{status}</p>:<div className="flex items-center justify-between gap-4"><p className="text-[9px] font-semibold uppercase tracking-[.2em] text-bronze">{label}</p><strong className="display text-2xl font-normal">{money(amounts.total)}</strong></div>}</div>;}
function BankTransferAmount({amounts,status}:{amounts:ReturnType<typeof checkoutAmounts>;status:string}){return <div className="border border-bronze/35 bg-bronze/[.07] p-4">{amounts.total===undefined?<p className="text-sm font-medium leading-6">{status}</p>:<><div className="flex items-center justify-between gap-4"><p className="text-[9px] font-semibold uppercase tracking-[.2em] text-bronze">Amount to transfer</p><strong className="display text-2xl font-normal">{money(amounts.total)}</strong></div><div className="mt-3 grid grid-cols-2 gap-x-4 border-t border-black/10 pt-3 text-[11px]"><SummaryLine label="Subtotal" value={money(amounts.subtotal)}/><SummaryLine label="Delivery" value={amounts.deliveryFee?money(amounts.deliveryFee):"Free"}/></div></>}</div>;}
function ReceiptUpload({ready,busy,url,name,error,clearError,upload,remove}:{ready:boolean;busy:boolean;url:string;name:string;error?:string;clearError:()=>void;upload:(file?:File)=>Promise<void>;remove:()=>void}){const accept="image/jpeg,image/png,image/webp,image/heic,image/heif,application/pdf",change=(file?:File)=>{clearError();void upload(file);};return <div><p className="mb-1.5 label">Receipt upload <i>*</i></p><InlineError message={error}/>{busy?<div className="flex min-h-20 items-center justify-center border border-dashed border-black/25 text-sm">Uploading receipt…</div>:url?<div className="flex flex-wrap items-center justify-between gap-2 border border-emerald-900/20 bg-emerald-950/[.05] p-3"><span className="flex min-w-0 items-center gap-2 text-emerald-900"><CheckCircle2 size={16}/><span className="min-w-0"><b className="block text-xs">Receipt uploaded</b><small className="block max-w-64 truncate text-emerald-800">{name}</small></span></span><span className="flex items-center gap-1"><label className={`btn min-h-10 px-3 ${ready?"cursor-pointer":"pointer-events-none opacity-40"}`}>Replace<input className="sr-only" type="file" accept={accept} disabled={!ready} onChange={event=>{change(event.target.files?.[0]);event.currentTarget.value="";}}/></label><button type="button" className="btn min-h-10 px-3" onClick={remove}><X size={13}/> Remove</button></span></div>:<label tabIndex={ready?0:-1} className={`flex min-h-20 items-center justify-center gap-3 border border-dashed border-black/25 px-4 text-center ${ready?"cursor-pointer":"cursor-not-allowed opacity-55"}`}><Upload size={18}/><span className="text-left"><b className="block text-xs">Upload bank receipt</b><small className="block text-[10px] text-ink/45">{ready?"Image or PDF":"Add delivery details first."}</small></span><input name="paymentReceiptUrl" className="sr-only" type="file" accept={accept} disabled={!ready} onChange={event=>{change(event.target.files?.[0]);event.currentTarget.value="";}}/></label>}</div>;}
function FinalAction({payment,amounts,receiptReady,error,disabled,busy,receiptBusy}:{payment:PaymentMethod;amounts:ReturnType<typeof checkoutAmounts>;receiptReady:boolean;error:string;disabled:boolean;busy:boolean;receiptBusy:boolean}){return <div className="mt-5 border-t border-black/15 pt-4"><div className="flex items-end justify-between gap-4"><span><p className="eyebrow text-bronze">Total</p><small className="mt-1 block text-[10px] text-ink/50">{payment==="cod"?"Pay on delivery":"Transfer total"}</small></span><strong className="display text-3xl font-normal">{amounts.total===undefined?"—":money(amounts.total)}</strong></div>{payment==="bank"&&<p className={`mt-2 text-[10px] ${receiptReady?"text-emerald-800":"text-ink/50"}`}>{receiptReady?"Receipt attached securely for verification.":"Receipt required before placing your order."}</p>}{error&&<motion.p initial={{opacity:0}} animate={{opacity:1}} role="alert" className="mt-3 border-l-2 border-red-800 bg-red-950/[.06] p-3 text-[11px] leading-5 text-red-900">{error}</motion.p>}<button disabled={disabled} className="btn btn-dark mt-4 w-full">{busy?"Placing order…":receiptBusy?"Uploading receipt…":"Place Order"}</button><p className="mt-2 text-center text-[9px] leading-4 text-ink/50">By placing your order, you agree to our store terms. Orders are subject to confirmation.</p></div>;}
function BankDetail({label,value}:{label:string;value:string}){return <p><span className="text-ink/45">{label}</span><br/><b>{value}</b></p>;}
function SummaryLine({label,value}:{label:string;value:string}){return <div className="flex items-start justify-between gap-4"><span className="text-ink/60">{label}</span><span className="max-w-[190px] text-right font-medium leading-5">{value}</span></div>;}
function Field({name,label,required,type="text",autoComplete,wide,defaultValue,value,inputMode,maxLength,onChange,onBlur,error,placeholder}:{name:string;label:string;required?:boolean;type?:string;autoComplete?:string;wide?:boolean;defaultValue?:string;value?:string;inputMode?:"text"|"numeric"|"tel";maxLength?:number;onChange?:(value:string)=>void;onBlur?:()=>void;error?:string;placeholder?:string}){const errorId=`${name}-error`;return <label className={`${wide?"sm:col-span-2 ":""}label`}>{label} {required&&<i>*</i>}<input name={name} required={required} type={type} inputMode={inputMode||(type==="tel"?"tel":undefined)} maxLength={maxLength} aria-invalid={Boolean(error)} aria-describedby={error?errorId:undefined} className={`field mt-1.5 normal-case tracking-normal ${error?"border-red-700":""}`} autoComplete={autoComplete} defaultValue={value===undefined?defaultValue:undefined} value={value} placeholder={placeholder} onBlur={onBlur} onChange={e=>onChange?.(e.target.value)}/><InlineError id={errorId} message={error}/></label>;}
