import {useEffect,useMemo,useState,type FormEvent} from 'react';
import {Navigate,useNavigate} from 'react-router-dom';
import {z} from 'zod';
import {Seo} from '../components/Seo';
import {money} from '../config/site';
import {useCustomerAuth} from '../features/account/CustomerAuthContext';
import {useCart} from '../features/cart/CartContext';
import {useStore} from '../features/store/StoreContext';
import {api} from '../services/api';
import type {PaymentMethod} from '../types';

const schema=z.object({customerName:z.string().min(2),phone:z.string().regex(/^[+\d][\d\s-]{8,14}$/),whatsapp:z.string().optional(),email:z.string().email().or(z.literal('')).optional(),address1:z.string().min(5),address2:z.string().optional(),city:z.string().min(2),district:z.string().min(2),postalCode:z.string().optional(),deliveryNotes:z.string().max(300).optional(),paymentMethod:z.enum(['cod','bank'])});
const districts=['Ampara','Anuradhapura','Badulla','Batticaloa','Colombo','Galle','Gampaha','Hambantota','Jaffna','Kalutara','Kandy','Kegalle','Kilinochchi','Kurunegala','Mannar','Matale','Matara','Monaragala','Mullaitivu','Nuwara Eliya','Polonnaruwa','Puttalam','Ratnapura','Trincomalee','Vavuniya'];

export default function CheckoutPage(){
 const cart=useCart(),navigate=useNavigate(),{data}=useStore(),settings=data.settings,{user}=useCustomerAuth();
 const savedName=[user?.firstName,user?.lastName].filter(Boolean).join(' '),savedMobile=user?.mobile||'',savedAddress1=user?.address1||'',savedAddress2=user?.address2||'',savedCity=user?.city||'',savedDistrict=user?.district||'',savedPostalCode=user?.postalCode||'';
 const bankConfigured=Boolean(settings.bankEnabled&&settings.bankName.trim()&&settings.accountName.trim()&&settings.accountNumber.trim());
 const availablePayments=useMemo<PaymentMethod[]>(()=>[...(settings.codEnabled?['cod' as const]:[]),...(bankConfigured?['bank' as const]:[])],[settings.codEnabled,bankConfigured]);
 const[payment,setPayment]=useState<PaymentMethod>(availablePayments[0]||'cod'),[district,setDistrict]=useState(savedDistrict),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{if(!availablePayments.includes(payment)&&availablePayments[0])setPayment(availablePayments[0])},[availablePayments,payment]);
 if(!cart.items.length)return <Navigate to="/cart" replace/>;
 const currentPrice=(item:typeof cart.items[number])=>data.products.find(p=>p.id===item.productId&&p.status==='published')?.price??item.unitPrice;
 const displaySubtotal=cart.items.reduce((sum,item)=>sum+currentPrice(item)*item.quantity,0);
 const districtRate=data.deliveryRates.find(rate=>rate.active&&rate.district.trim().toLowerCase()===district.trim().toLowerCase());
 const baseDeliveryFee=settings.deliveryEnabled?(districtRate?.fee??settings.deliveryFee):0;
 const fee=settings.freeDeliveryThreshold>0&&displaySubtotal>=settings.freeDeliveryThreshold?0:baseDeliveryFee;
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setError('');if(!settings.storeOpen||!settings.ordersEnabled){setError('Online ordering is temporarily unavailable. Please contact us for assistance.');return}if(!availablePayments.length){setError('No payment method is currently available. Please contact us for assistance.');return}const raw=Object.fromEntries(new FormData(event.currentTarget));const parsed=schema.safeParse({...raw,paymentMethod:payment});if(!parsed.success){setError('Please review the required information and try again.');return}setBusy(true);try{const order=await api.createOrder({...parsed.data,items:cart.items});sessionStorage.setItem(`order:${order.orderId}`,JSON.stringify(order));cart.clear();navigate(`/order/${order.orderId}`)}catch{setError('We could not submit your order. Your bag is safe—please try again.')}finally{setBusy(false)}}
 return <main className="container py-10 lg:py-16"><Seo title="Checkout"/>{user&&<p className="mb-7 border-l-2 border-bronze bg-white/30 px-4 py-3 text-xs text-ink/60">Signed in as <b className="text-ink">{user.email}</b>. Your account email will connect this order to your order history.</p>}<form onSubmit={submit} className="grid gap-12 lg:grid-cols-[1fr_420px]"><div className="space-y-12">
  <section><p className="eyebrow mb-5">01 · Contact</p><div className="grid gap-4 sm:grid-cols-2"><Field name="customerName" label="Full Name *" required autoComplete="name" wide defaultValue={savedName}/><Field name="phone" label="Mobile Number *" required type="tel" autoComplete="tel" defaultValue={savedMobile}/><Field name="whatsapp" label="WhatsApp Number" type="tel"/><Field name="email" label={user?'Email (account email)':'Email (optional)'} type="email" autoComplete="email" wide defaultValue={user?.email||''} readOnly={Boolean(user)}/></div></section>
  <section><p className="eyebrow mb-5">02 · Delivery</p><div className="grid gap-4 sm:grid-cols-2"><Field name="address1" label="Address Line 1 *" required autoComplete="address-line1" wide defaultValue={savedAddress1}/><Field name="address2" label="Address Line 2" autoComplete="address-line2" wide defaultValue={savedAddress2}/><Field name="city" label="City *" required autoComplete="address-level2" defaultValue={savedCity}/><label className="text-xs">District *<select name="district" required className="field mt-2" value={district} onChange={e=>setDistrict(e.target.value)}><option value="" disabled>Select district</option>{districts.map(d=><option key={d}>{d}</option>)}</select></label><Field name="postalCode" label="Postal Code" autoComplete="postal-code" defaultValue={savedPostalCode}/><label className="sm:col-span-2 text-xs">Delivery Instructions<textarea name="deliveryNotes" rows={3} className="field mt-2 resize-none"/></label></div></section>
  <section><p className="eyebrow mb-5">03 · Payment</p>{availablePayments.length?<div className="grid gap-3">{availablePayments.map(value=><label key={value} className={`flex min-h-16 cursor-pointer items-center gap-4 border p-4 ${payment===value?'border-ink':'border-line'}`}><input type="radio" checked={payment===value} onChange={()=>setPayment(value)} name="pay" className="accent-black"/><span className="text-sm uppercase tracking-widest">{value==='cod'?'Cash on delivery':'Bank transfer'}</span></label>)}</div>:<p className="border border-line p-4 text-sm">Payment methods are temporarily unavailable.</p>}{payment==='bank'&&bankConfigured&&<div className="mt-4 border border-line bg-white/30 p-5 text-sm leading-7"><p><b>Bank:</b> {settings.bankName}</p><p><b>Account Name:</b> {settings.accountName}</p><p><b>Account Number:</b> {settings.accountNumber}</p>{settings.branch&&<p><b>Branch:</b> {settings.branch}</p>}{settings.bankInstructions&&<p className="mt-3 text-xs text-ink/60">{settings.bankInstructions}</p>}</div>}</section>
 </div><aside className="h-fit bg-[#e7e1d7] p-6 lg:sticky lg:top-6"><p className="eyebrow">Order summary</p><div className="mt-6 space-y-4">{cart.items.map(item=><div key={item.variantId} className="flex gap-3"><div className="relative">{item.image?<img src={item.image} alt={item.name} className="h-20 w-14 object-cover"/>:<div className="h-20 w-14 bg-black/5"/>}<span className="absolute -right-2 -top-2 grid h-5 w-5 place-items-center rounded-full bg-ink text-[10px] text-white">{item.quantity}</span></div><div className="flex-1 text-sm"><p>{item.name}</p><p className="mt-1 text-xs text-ink/50">{item.color} / {item.size}</p></div><span className="text-sm">{money(currentPrice(item)*item.quantity)}</span></div>)}</div><div className="my-6 border-t hairline"/><div className="space-y-3 text-sm"><div className="flex justify-between"><span>Subtotal</span><span>{money(displaySubtotal)}</span></div><div className="flex justify-between"><span>Delivery</span><span>{fee?money(fee):'Complimentary'}</span></div><div className="flex justify-between border-t hairline pt-4 text-base"><span>Total</span><span>{money(displaySubtotal+fee)}</span></div></div>{error&&<p role="alert" className="mt-5 bg-red-950 p-3 text-xs leading-5 text-white">{error}</p>}<button disabled={busy||!availablePayments.length||!settings.storeOpen||!settings.ordersEnabled} className="btn btn-dark mt-6 w-full disabled:opacity-50">{busy?'Placing order…':'Place order'}</button><p className="mt-4 text-center text-[10px] leading-5 text-ink/50">By placing an order, you agree to the store terms. This is an order request, not automatic confirmation.</p></aside></form></main>
}
function Field({name,label,required,type='text',autoComplete,wide=false,defaultValue,readOnly=false}:{name:string;label:string;required?:boolean;type?:string;autoComplete?:string;wide?:boolean;defaultValue?:string;readOnly?:boolean}){return <label className={`${wide?'sm:col-span-2 ':''}text-xs`}>{label}<input name={name} required={required} type={type} inputMode={type==='tel'?'tel':undefined} className={`field mt-2 ${readOnly?'opacity-65':''}`} autoComplete={autoComplete} defaultValue={defaultValue} readOnly={readOnly}/></label>}
