import {useCallback,useEffect,useState} from 'react';
import {Link,Navigate} from 'react-router-dom';
import {ArrowLeft,ChevronDown,MapPin,MessageCircle,PackageOpen,RefreshCw} from 'lucide-react';
import {Seo} from '../components/Seo';
import {money} from '../config/site';
import {useCustomerAuth} from '../features/account/CustomerAuthContext';
import {api} from '../services/api';
import type {CustomerOrder,CustomerPreorder,PreorderStatus} from '../types';
import {AccountLoading} from './AccountPage';

const preorderLabels:Record<PreorderStatus,string>={new:'Request received',contacted:'We contacted you',confirmed:'Confirmed',batched:'In supplier batch',ordered:'Supplier order placed',in_transit:'On the way',arrived:'Arrived',ready:'Ready for you',converted:'Moved to Orders',cancelled:'Cancelled'};
const preorderHelp:Record<PreorderStatus,string>={new:'We received your request. ZEVENRA will contact you on WhatsApp before any supplier order is placed.',contacted:'Please confirm the item and final price with us on WhatsApp.',confirmed:'You confirmed the item. It is waiting to join the next supplier batch.',batched:'Your confirmed piece has been grouped into a supplier batch.',ordered:'The supplier order has been placed.',in_transit:'Your piece is on the way to Sri Lanka.',arrived:'Your piece has arrived and is being checked.',ready:'Your piece is ready. We will arrange the normal order/payment with you.',converted:'This pre-order is finished and has been converted into a normal order. Check the Orders tab.',cancelled:'This pre-order request was cancelled.'};

export default function CustomerOrdersPage(){
 const{user,loading}=useCustomerAuth(),[orders,setOrders]=useState<CustomerOrder[]>([]),[preorders,setPreorders]=useState<CustomerPreorder[]>([]),[tab,setTab]=useState<'orders'|'preorders'>('orders'),[busy,setBusy]=useState(true),[error,setError]=useState(''),[warning,setWarning]=useState(''),[open,setOpen]=useState('');
 const load=useCallback(async()=>{setBusy(true);setError('');setWarning('');const[normal,requests]=await Promise.allSettled([api.customerOrders(),api.customerPreorders()]);if(normal.status==='fulfilled')setOrders(normal.value);else setOrders([]);if(requests.status==='fulfilled')setPreorders(requests.value);else setPreorders([]);if(normal.status==='rejected'&&requests.status==='rejected')setError('We could not load your orders or pre-orders right now.');else if(normal.status==='rejected')setWarning('Normal orders could not be loaded right now. Pre-orders are still available.');else if(requests.status==='rejected')setWarning('Pre-orders could not be loaded right now. Normal orders are still available.');setBusy(false)},[]);
 useEffect(()=>{if(user)void load()},[load,user]);if(loading)return <AccountLoading/>;if(!user)return <Navigate to="/account/login" replace state={{from:'/account/orders'}}/>;
 return <main className="account-page account-orders"><Seo title="My Orders"/><div className="container account-page__inner"><Link to="/account" className="account-back"><ArrowLeft/> My account</Link><p className="eyebrow text-bronze">Your ZEVENRA activity</p><h1 className="display">Orders & pre-orders</h1><p className="account-page__lead">See what you requested, payment status, delivery details and where each item is in the process.</p><div className="customer-order-tabs"><button className={tab==='orders'?'is-active':''} onClick={()=>{setTab('orders');setOpen('')}}><span>Orders</span><b>{orders.length}</b></button><button className={tab==='preorders'?'is-active':''} onClick={()=>{setTab('preorders');setOpen('')}}><span>Pre-orders</span><b>{preorders.length}</b></button><button className="customer-order-refresh" onClick={()=>void load()} disabled={busy}><RefreshCw size={15}/><span>Refresh</span></button></div>{warning&&<p className="account-orders-warning" role="status">{warning}</p>}{busy?<OrdersSkeleton/>:error?<div className="account-state"><p>{error}</p><button onClick={()=>void load()} className="btn"><RefreshCw/> Retry</button></div>:tab==='orders'?<OrdersView orders={orders} open={open} setOpen={setOpen}/>:<PreordersView requests={preorders}/>}</div></main>
}
function OrdersView({orders,open,setOpen}:{orders:CustomerOrder[];open:string;setOpen:(id:string)=>void}){if(!orders.length)return <div className="account-state"><PackageOpen/><h2 className="display">No account orders yet.</h2><p>Orders placed while you are signed in will appear here.</p><Link to="/shop" className="btn btn-dark">Explore shop</Link></div>;return <div className="orders-list">{orders.map(order=><article className={'order-row '+(open===order.orderId?'is-open':'')} key={order.orderId}><button className="order-row__summary" onClick={()=>setOpen(open===order.orderId?'':order.orderId)} aria-expanded={open===order.orderId}><span><small>Order</small><b>#{order.orderId}</b></span><span><small>Date</small><b>{new Date(order.createdAt).toLocaleDateString('en-LK',{year:'numeric',month:'short',day:'numeric'})}</b></span><span><small>Total</small><b>{money(order.total)}</b></span><span><small>Payment</small><b>{order.paymentMethod==='cod'?'Cash on delivery':'Bank transfer'}</b>{order.paymentStatus&&<small>{order.paymentStatus}</small>}</span><span className={'order-status order-status--'+order.orderStatus.toLowerCase()}>{order.orderStatus}</span><ChevronDown/></button>{open===order.orderId&&<div className="customer-order-detail"><section><p className="eyebrow text-bronze">Items</p><div className="customer-order-items">{order.items.map((item,index)=><div className="order-item" key={item.variantId+'-'+index}><span><b>{item.name}</b><small>{item.color} / {item.size} · Qty {item.quantity}</small></span><b>{money(item.subtotal)}</b></div>)}</div></section><section className="customer-order-info"><div><small>Delivery to</small><p><MapPin size={14}/>{[order.address1,order.address2,order.city,order.district,order.postalCode].filter(Boolean).join(', ')||'Address unavailable'}</p></div><div><small>Contact</small><p>{order.phone||'—'}{order.whatsapp?' · WhatsApp '+order.whatsapp:''}</p></div>{order.deliveryNotes&&<div><small>Delivery instructions</small><p>{order.deliveryNotes}</p></div>}{order.paymentReference&&<div><small>Bank reference</small><p>{order.paymentReference}</p></div>}</section><dl><div><dt>Subtotal</dt><dd>{money(order.subtotal)}</dd></div><div><dt>Delivery</dt><dd>{order.deliveryFee?money(order.deliveryFee):'Complimentary'}</dd></div><div><dt>Total</dt><dd>{money(order.total)}</dd></div><div><dt>Order status</dt><dd>{order.orderStatus}</dd></div><div><dt>Payment status</dt><dd>{order.paymentStatus||'—'}</dd></div></dl></div>}</article>)}</div>}
function PreordersView({requests}:{requests:CustomerPreorder[]}){if(!requests.length)return <div className="account-state"><MessageCircle/><h2 className="display">No signed-in pre-orders yet.</h2><p>Pre-order requests you submit while signed in will appear here.</p><Link to="/shop" className="btn btn-dark">Explore shop</Link></div>;return <div className="customer-preorder-list">{requests.map(item=><article className="customer-preorder-card" key={item.requestId}><div className="customer-preorder-card__head"><div><small>Pre-order request</small><h2>{item.requestId}</h2><p>{new Date(item.createdAt).toLocaleString('en-LK',{year:'numeric',month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'})}</p></div><span className={'preorder-status preorder-status--'+item.status}>{preorderLabels[item.status]}</span></div><div className="customer-preorder-card__grid"><section><small>Item</small><h3>{item.productName}</h3><p>{item.color} / {item.size} · Qty {item.quantity}</p><p>Price when requested: <b>{money(item.requestedPrice)}</b></p>{Number(item.confirmedPrice||0)>0&&<p>Final agreed price: <b>{money(Number(item.confirmedPrice))}</b></p>}</section><section><small>Delivery details</small><p>{item.customerName}</p><p>{item.whatsapp}</p><p>{[item.address1,item.address2,item.city,item.district,item.postalCode].filter(Boolean).join(', ')}</p></section><section className="customer-preorder-next"><small>What happens now</small><p>{preorderHelp[item.status]}</p>{item.batchId&&<span>Supplier batch: {item.batchId}</span>}</section></div></article>)}</div>}
function OrdersSkeleton(){return <div className="orders-list" aria-label="Loading order history"><div className="account-skeleton account-skeleton--order"/><div className="account-skeleton account-skeleton--order"/><div className="account-skeleton account-skeleton--order"/></div>}
