import {useState,type FormEvent,type ReactNode} from 'react';
import {Link,Navigate,useLocation,useNavigate} from 'react-router-dom';
import {ArrowRight} from 'lucide-react';
import {Seo} from '../components/Seo';
import {useCustomerAuth} from '../features/account/CustomerAuthContext';

export default function CustomerLoginPage(){
 const{user,loading,configured,passwordRecovery,signIn,sendReset,updatePassword}=useCustomerAuth(),navigate=useNavigate(),location=useLocation();
 const[forgot,setForgot]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 if(!loading&&user&&!passwordRecovery)return <Navigate to="/account" replace/>;
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError('');setMessage('');const data=new FormData(event.currentTarget),email=String(data.get('email')||'').trim();try{if(forgot){await sendReset(email);setMessage('Check your inbox for a secure password reset link.')}else{await signIn(email,String(data.get('password')||''));const next=(location.state as{from?:string}|null)?.from;navigate(next&&next.startsWith('/')&&!next.startsWith('//')?next:'/account')}}catch(reason){setError(reason instanceof Error?friendlyAuthError(reason.message):'Unable to sign in. Please try again.')}finally{setBusy(false)}}
 if(passwordRecovery)return <PasswordRecovery onUpdate={updatePassword}/>;
 return <AuthShell title={forgot?'Reset password':'Welcome back'} intro={forgot?'Enter your email and we’ll send a secure reset link.':'Sign in to see your orders and move through checkout a little faster.'}><Seo title={forgot?'Reset Password':'Customer Sign In'}/>{!configured&&<p className="account-auth__error">Customer accounts are being configured. Guest shopping and checkout remain available.</p>}<form onSubmit={submit} className="account-auth__form"><label>Email<input name="email" type="email" autoComplete="email" required placeholder="you@example.com"/></label>{!forgot&&<label>Password<input name="password" type="password" autoComplete="current-password" required minLength={8} placeholder="Your password"/></label>}{error&&<p role="alert" className="account-auth__error">{error}</p>}{message&&<p role="status" className="account-auth__success">{message}</p>}<button className="account-auth__primary" disabled={busy||!configured}>{busy?'Please wait…':forgot?'Send reset link':'Sign in'}<ArrowRight/></button></form><button className="account-auth__text" onClick={()=>{setForgot(value=>!value);setError('');setMessage('')}}>{forgot?'Back to sign in':'Forgot password?'}</button>{!forgot&&<Link to="/account/register" className="account-auth__secondary">Create account</Link>}<Link to="/shop" className="account-auth__shopping">Continue shopping</Link></AuthShell>
}
function PasswordRecovery({onUpdate}:{onUpdate:(password:string)=>Promise<void>}){const[busy,setBusy]=useState(false),[error,setError]=useState(''),navigate=useNavigate();async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const data=new FormData(event.currentTarget),password=String(data.get('password')||''),confirm=String(data.get('confirm')||'');if(password.length<8||!/[A-Za-z]/.test(password)||!/\d/.test(password)){setError('Use at least 8 characters with a letter and number.');return}if(password!==confirm){setError('Passwords do not match.');return}setBusy(true);setError('');try{await onUpdate(password);navigate('/account')}catch(reason){setError(reason instanceof Error?reason.message:'Unable to update your password.')}finally{setBusy(false)}}return <AuthShell title="Choose a new password" intro="Create a secure new password for your ZEVENRA account."><Seo title="Choose New Password"/><form onSubmit={submit} className="account-auth__form"><label>New password<input name="password" type="password" autoComplete="new-password" required/></label><label>Confirm password<input name="confirm" type="password" autoComplete="new-password" required/></label>{error&&<p role="alert" className="account-auth__error">{error}</p>}<button className="account-auth__primary" disabled={busy}>{busy?'Updating…':'Update password'}<ArrowRight/></button></form></AuthShell>}
function friendlyAuthError(message:string){return /invalid login credentials/i.test(message)?'The email or password is incorrect.':/email not confirmed/i.test(message)?'Please verify your email before signing in.':message}
export function AuthShell({title,intro,children}:{title:string;intro:string;children:ReactNode}){return <main className="account-auth"><section className="account-auth__image"><img src="/brand/about-story.webp" alt=""/><div><span>ZEVENRA PRIVATE CLIENT</span><p className="display">A more considered<br/>way to return.</p></div></section><section className="account-auth__panel"><Link to="/" className="account-auth__logo"><img src="/brand/logo.svg" alt="ZEVENRA"/></Link><div className="account-auth__box"><p className="eyebrow text-bronze">Customer account</p><h1 className="display">{title}</h1><p className="account-auth__intro">{intro}</p>{children}</div><span className="account-auth__foot">OPTIONAL ACCOUNT · GUEST CHECKOUT ALWAYS AVAILABLE</span></section></main>}
