import {useCallback,useEffect,useState} from 'react';
import {Link,Navigate} from 'react-router-dom';
import {ArrowLeft,ChevronDown,PackageOpen,RefreshCw} from 'lucide-react';
import {Seo} from '../components/Seo';
import {money} from '../config/site';
import {useCustomerAuth} from '../features/account/CustomerAuthContext';
import {api} from '../services/api';
import type {CustomerOrder} from '../types';
import {AccountLoading} from './AccountPage';

export default function CustomerOrdersPage(){const{user,session,loading}=useCustomerAuth(),[orders,setOrders]=useState<CustomerOrder[]>([]),[busy,setBusy]=useState(true),[error,setError]=useState(''),[open,setOpen]=useState('');const load=useCallback(async()=>{if(!session)return;setBusy(true);setError('');try{setOrders(await api.customerOrders(session.access_token))}catch{setError('We could not load your orders right now.')}finally{setBusy(false)}},[session]);useEffect(()=>{void load()},[load]);if(loading)return <AccountLoading/>;if(!user||!session)return <Navigate to="/account/login" replace state={{from:'/account/orders'}}/>;return <main className="account-page account-orders"><Seo title="My Orders"/><div className="container account-page__inner"><Link to="/account" className="account-back"><ArrowLeft/> My account</Link><p className="eyebrow text-bronze">Order history</p><h1 className="display">My orders</h1>{busy?<OrdersSkeleton/>:error?<div className="account-state"><p>{error}</p><button onClick={()=>void load()} className="btn"><RefreshCw/> Retry</button></div>:orders.length===0?<div className="account-state"><PackageOpen/><h2 className="display">No orders yet.</h2><p>Your next piece is waiting.</p><Link to="/shop" className="btn btn-dark">Explore shop</Link></div>:<div className="orders-list">{orders.map(order=><article className={`order-row ${open===order.orderId?'is-open':''}`} key={order.orderId}><button className="order-row__summary" onClick={()=>setOpen(value=>value===order.orderId?'':order.orderId)} aria-expanded={open===order.orderId}><span><small>Order</small><b>#{order.orderId}</b></span><span><small>Date</small><b>{new Date(order.createdAt).toLocaleDateString('en-LK',{year:'numeric',month:'short',day:'numeric'})}</b></span><span><small>Total</small><b>{money(order.total)}</b></span><span><small>Payment</small><b>{order.paymentMethod==='cod'?'Cash on delivery':'Bank transfer'}</b></span><span className={`order-status order-status--${order.orderStatus.toLowerCase()}`}>{order.orderStatus}</span><ChevronDown/></button>{open===order.orderId&&<div className="order-row__details"><div>{order.items.map((item,index)=><div className="order-item" key={`${item.variantId}-${index}`}><span><b>{item.name}</b><small>{item.color} / {item.size} · Qty {item.quantity}</small></span><b>{money(item.subtotal)}</b></div>)}</div><dl><div><dt>Subtotal</dt><dd>{money(order.subtotal)}</dd></div><div><dt>Delivery</dt><dd>{order.deliveryFee?money(order.deliveryFee):'Complimentary'}</dd></div><div><dt>Total</dt><dd>{money(order.total)}</dd></div><div><dt>Status</dt><dd>{order.orderStatus}</dd></div></dl></div>}</article>)}</div>}</div></main>}
function OrdersSkeleton(){return <div className="orders-list" aria-label="Loading orders"><div className="account-skeleton account-skeleton--order"/><div className="account-skeleton account-skeleton--order"/><div className="account-skeleton account-skeleton--order"/></div>}
