import {useState,type FormEvent,type ReactNode} from 'react';
import {Link,Navigate,useLocation,useNavigate} from 'react-router-dom';
import {ArrowRight} from 'lucide-react';
import {Seo} from '../components/Seo';
import {useCustomerAuth} from '../features/account/CustomerAuthContext';

export default function CustomerLoginPage(){
 const{user,loading,signIn}=useCustomerAuth(),navigate=useNavigate(),location=useLocation();
 const[forgot,setForgot]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 if(!loading&&user)return <Navigate to="/account" replace/>;
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError('');const data=new FormData(event.currentTarget);try{await signIn(String(data.get('email')||'').trim(),String(data.get('password')||''));const next=(location.state as{from?:string}|null)?.from;navigate(next&&next.startsWith('/')&&!next.startsWith('//')?next:'/account')}catch(reason){setError(reason instanceof Error?reason.message:'Unable to sign in. Please try again.')}finally{setBusy(false)}}
 return <AuthShell title="Welcome back" intro="Sign in to see your orders and move through checkout a little faster."><Seo title="Customer Sign In"/><form onSubmit={submit} className="account-auth__form"><label>Email<input name="email" type="email" autoComplete="email" required placeholder="you@example.com"/></label><label>Password<input name="password" type="password" autoComplete="current-password" required minLength={8} placeholder="Your password"/></label>{error&&<p role="alert" className="account-auth__error">{error}</p>}<button className="account-auth__primary" disabled={busy}>{busy?'Please wait…':'Sign in'}<ArrowRight/></button></form><button className="account-auth__text" onClick={()=>setForgot(value=>!value)}>Forgot password?</button>{forgot&&<p role="status" className="account-auth__support">Please contact ZEVENRA support to reset your password.</p>}<Link to="/account/register" className="account-auth__secondary">Create account</Link><Link to="/shop" className="account-auth__shopping">Continue shopping</Link></AuthShell>
}
export function AuthShell({title,intro,children}:{title:string;intro:string;children:ReactNode}){return <main className="account-auth"><section className="account-auth__image"><img src="/brand/about-story.webp" alt=""/><div><span>ZEVENRA PRIVATE CLIENT</span><p className="display">A more considered<br/>way to return.</p></div></section><section className="account-auth__panel"><Link to="/" className="account-auth__logo"><img src="/brand/logo.svg" alt="ZEVENRA"/></Link><div className="account-auth__box"><p className="eyebrow text-bronze">Customer account</p><h1 className="display">{title}</h1><p className="account-auth__intro">{intro}</p>{children}</div><span className="account-auth__foot">OPTIONAL ACCOUNT · GUEST CHECKOUT ALWAYS AVAILABLE</span></section></main>}
