import {useState,type FormEvent} from 'react';
import {Link,Navigate,useNavigate} from 'react-router-dom';
import {z} from 'zod';
import {ArrowRight} from 'lucide-react';
import {Seo} from '../components/Seo';
import {useCustomerAuth} from '../features/account/CustomerAuthContext';
import {AuthShell} from './CustomerLoginPage';

const schema=z.object({firstName:z.string().trim().min(2,'Enter your first name.'),lastName:z.string().trim().min(2,'Enter your last name.'),email:z.string().trim().email('Enter a valid email.'),mobile:z.string().trim().regex(/^$|^[+\d][\d\s-]{8,14}$/,'Enter a valid mobile number.'),password:z.string().min(8,'Use at least 8 characters.').regex(/[A-Za-z]/,'Include a letter.').regex(/\d/,'Include a number.'),confirmPassword:z.string()}).refine(value=>value.password===value.confirmPassword,{path:['confirmPassword'],message:'Passwords do not match.'});
export default function CustomerRegisterPage(){const{user,loading,register}=useCustomerAuth(),navigate=useNavigate(),[busy,setBusy]=useState(false),[error,setError]=useState('');if(!loading&&user)return <Navigate to="/account" replace/>;async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setError('');const parsed=schema.safeParse(Object.fromEntries(new FormData(event.currentTarget)));if(!parsed.success){setError(parsed.error.issues[0]?.message||'Please review your details.');return}setBusy(true);try{await register({firstName:parsed.data.firstName,lastName:parsed.data.lastName,email:parsed.data.email,mobile:parsed.data.mobile,password:parsed.data.password});navigate('/account')}catch(reason){setError(reason instanceof Error?reason.message:'Unable to create your account.')}finally{setBusy(false)}}return <AuthShell title="Create account" intro="Save time at checkout and keep your ZEVENRA order history close."><Seo title="Create Account"/><form onSubmit={submit} className="account-auth__form account-auth__form--register"><div className="account-auth__split"><label>First name<input name="firstName" autoComplete="given-name" required/></label><label>Last name<input name="lastName" autoComplete="family-name" required/></label></div><label>Email<input name="email" type="email" autoComplete="email" required/></label><label>Mobile <small>Optional</small><input name="mobile" type="tel" autoComplete="tel"/></label><div className="account-auth__split"><label>Password<input name="password" type="password" autoComplete="new-password" required minLength={8}/></label><label>Confirm password<input name="confirmPassword" type="password" autoComplete="new-password" required minLength={8}/></label></div>{error&&<p role="alert" className="account-auth__error">{error}</p>}<button className="account-auth__primary" disabled={busy}>{busy?'Creating account…':'Create account'}<ArrowRight/></button></form><Link to="/account/login" className="account-auth__text">Already have an account? Sign in</Link><Link to="/shop" className="account-auth__shopping">Continue shopping</Link></AuthShell>}
