import {useState} from 'react';
import {Link} from 'react-router-dom';
import {ProductSection} from '../components/ProductSection';
import {Seo} from '../components/Seo';
import {useStore} from '../features/store/StoreContext';
import {getNavigationCategories} from '../utils/catalog';

export default function HomePage(){
 const{data}=useStore(),hero=data.settings.hero,[videoReady,setVideoReady]=useState(false),[videoFailed,setVideoFailed]=useState(false),products=data.products.filter(product=>product.status==='published'),newArrivals=products.filter(product=>product.newArrival).slice(0,4),featured=products.filter(product=>product.featured).slice(0,4),categories=getNavigationCategories(data.categories,data.products).filter(category=>category.showOnHomepage||category.featured),banner=data.homepageSections.find(section=>section.enabled&&(section.type==='full-width-campaign'||section.type==='editorial-image')),showVideo=hero.videoEnabled&&!videoFailed&&Boolean(hero.desktopVideo);
 return <><Seo title="The Art of Becoming" description={data.settings.defaultDescription}/><section className={`home-hero ${videoReady?'home-hero--ready':''}`}><img className="home-hero__fallback" src={hero.fallbackImage||hero.poster} alt="ZEVENRA fashion and lifestyle collection" fetchPriority="high"/>{showVideo&&<video className="home-hero__video" autoPlay muted loop playsInline preload="metadata" poster={hero.poster||hero.fallbackImage} onCanPlay={()=>setVideoReady(true)} onError={()=>setVideoFailed(true)} aria-label="ZEVENRA fashion and lifestyle collection"><source media="(max-width: 767px)" src={hero.mobileVideo||hero.desktopVideo} type="video/mp4"/><source src={hero.desktopVideo} type="video/mp4"/></video>}<div className="home-hero__shade"/><Link to={hero.ctaLink||'/shop'} className="home-hero__cta">{hero.ctaLabel||'EXPLORE SHOP'}</Link></section>{newArrivals.length>0&&<ProductSection title="New arrivals" products={newArrivals} link="/shop?new=true"/>}{categories.length>0&&<section className="section home-categories"><div className="container"><div className="section-heading"><h2 className="display">Shop by category</h2></div><div className={`category-grid ${categories.length===1?'category-grid--single':''}`}>{categories.map(category=><Link key={category.id} to={`/category/${category.slug}`}><img src={category.imageUrl} alt={category.name} loading="lazy"/><span>{category.name}</span></Link>)}</div></div></section>}{banner&&<section className="home-banner"><img src={banner.desktopMedia||hero.fallbackImage} alt={banner.title} loading="lazy"/>{banner.ctaLink&&<Link to={banner.ctaLink} className="home-banner__link">{banner.ctaLabel||'SHOP NOW'}</Link>}</section>}{featured.length>0&&<ProductSection title="Featured" products={featured} link="/shop"/>}{products.length===0&&<section className="container section text-center"><p className="eyebrow">The next edit is arriving soon</p><h2 className="display mx-auto mt-4 max-w-2xl text-4xl sm:text-6xl">Something considered is taking shape.</h2><Link to="/contact" className="btn mt-7">Stay in touch</Link></section>}<section className="service-strip"><div className="container"><span>Islandwide delivery</span><span>Secure order request</span><span>Support on WhatsApp</span></div></section></>
}
