import {useMemo,useState,type FormEvent} from 'react';
import {ArrowLeft,CheckCircle2,Minus,Plus} from 'lucide-react';
import {Link,Navigate,useSearchParams,useParams} from 'react-router-dom';
import {Seo} from '../components/Seo';
import {money} from '../config/site';
import {useCustomerAuth} from '../features/account/CustomerAuthContext';
import {useStore} from '../features/store/StoreContext';
import {api} from '../services/api';

const districts=['Ampara','Anuradhapura','Badulla','Batticaloa','Colombo','Galle','Gampaha','Hambantota','Jaffna','Kalutara','Kandy','Kegalle','Kilinochchi','Kurunegala','Mannar','Matale','Matara','Monaragala','Mullaitivu','Nuwara Eliya','Polonnaruwa','Puttalam','Ratnapura','Trincomalee','Vavuniya'];

export default function PreorderPage(){
 const {slug}=useParams(),[search]=useSearchParams(),{data}=useStore(),{user}=useCustomerAuth(),product=data.products.find(p=>p.slug===slug&&p.status==='published'),variant=product?.variants.find(v=>v.id===search.get('variant')&&v.active),[qty,setQty]=useState(1),[busy,setBusy]=useState(false),[error,setError]=useState(''),[done,setDone]=useState('');
 const defaultName=useMemo(()=>[user?.firstName,user?.lastName].filter(Boolean).join(' '),[user]);
 if(!product||!variant||!product.preorderEnabled||variant.stock>0)return <Navigate to={product?'/product/'+product.slug:'/shop'} replace/>;
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setError('');setBusy(true);try{const raw=Object.fromEntries(new FormData(event.currentTarget));const created=await api.createPreorder({customerName:String(raw.customerName||''),phone:String(raw.phone||''),whatsapp:String(raw.whatsapp||''),email:String(raw.email||''),address1:String(raw.address1||''),address2:String(raw.address2||''),city:String(raw.city||''),district:String(raw.district||''),postalCode:String(raw.postalCode||''),productId:product.id,variantId:variant.id,quantity:qty});setDone(created.requestId)}catch(reason){setError(reason instanceof Error?reason.message:'Could not submit preorder request.')}finally{setBusy(false)}}
 if(done)return <main className="container grid min-h-[75vh] place-content-center px-4 py-28 text-center"><Seo title="Pre-order requested"/><CheckCircle2 className="mx-auto" size={34}/><p className="eyebrow mt-5 text-bronze">Request received</p><h1 className="display mt-3 text-5xl">We’ll confirm with you first.</h1><p className="mx-auto mt-5 max-w-xl text-sm leading-7 text-ink/60">No payment has been taken. ZEVENRA will contact you on WhatsApp before this item is included in a supplier order.</p><p className="mt-4 text-xs text-ink/45">Reference: {done}</p><Link className="btn btn-dark mx-auto mt-8" to="/shop">Continue shopping</Link></main>;
 return <main className="container pb-20 pt-28 lg:pt-36"><Seo title={'Pre-order '+product.name}/><Link to={'/product/'+product.slug} className="inline-flex items-center gap-2 text-xs underline"><ArrowLeft size={14}/> Back to product</Link><div className="mt-7 grid gap-8 lg:grid-cols-[.8fr_1.2fr]"><section className="border border-line bg-[#ebe6de] p-4 sm:p-6"><div className="grid grid-cols-[110px_1fr] gap-4 sm:grid-cols-[150px_1fr]">{product.media.find(m=>m.type==='image')?<img src={product.media.find(m=>m.type==='image')!.url} alt={product.name} className="aspect-[4/5] w-full object-cover"/>:<div className="aspect-[4/5] bg-black/5"/>}<div><p className="eyebrow text-bronze">Pre-order request</p><h1 className="display mt-3 text-3xl sm:text-4xl">{product.name}</h1><p className="mt-3 text-sm text-ink/55">{variant.color} / {variant.size}</p><p className="mt-2 text-sm">{money(product.price)} <span className="text-xs text-ink/45">current display price</span></p><p className="mt-5 border-l-2 border-bronze pl-3 text-xs leading-6 text-ink/60">{product.preorderMessage||'We collect preorder requests and confirm with you before placing our supplier order.'}</p></div></div><div className="mt-6 border-t border-line pt-5"><p className="text-xs leading-6 text-ink/60"><b>No payment now.</b> This is only a request. We normally group several confirmed items before placing a supplier order, so delivery may take around two weeks after the supplier order is placed.</p></div></section>
 <form onSubmit={submit} className="space-y-7"><div><p className="eyebrow">Your details</p><h2 className="display mt-2 text-4xl">Request this piece.</h2></div><div className="grid gap-4 sm:grid-cols-2"><Field name="customerName" label="Full name *" required defaultValue={defaultName}/><Field name="phone" label="Mobile number *" required type="tel" defaultValue={user?.mobile||''}/><Field name="whatsapp" label="WhatsApp number *" required type="tel" defaultValue={user?.mobile||''}/><Field name="email" label="Email (optional)" type="email" defaultValue={user?.email||''}/><Field name="address1" label="Address line 1 *" required wide defaultValue={user?.address1||''}/><Field name="address2" label="Address line 2" wide defaultValue={user?.address2||''}/><Field name="city" label="City *" required defaultValue={user?.city||''}/><label className="text-xs">District *<select name="district" required className="field mt-2" defaultValue={user?.district||''}><option value="" disabled>Select district</option>{districts.map(d=><option key={d}>{d}</option>)}</select></label><Field name="postalCode" label="Postal code" defaultValue={user?.postalCode||''}/></div><div><p className="mb-2 text-xs">Quantity</p><div className="flex min-h-12 w-fit items-center border border-line"><button type="button" className="px-4" onClick={()=>setQty(Math.max(1,qty-1))}><Minus size={15}/></button><span className="w-10 text-center text-sm">{qty}</span><button type="button" className="px-4" disabled={qty>=5} onClick={()=>setQty(Math.min(5,qty+1))}><Plus size={15}/></button></div></div><div className="border border-bronze/25 bg-bronze/5 p-4 text-xs leading-6 text-ink/65">You are <b>not paying now</b>. We will contact you on WhatsApp to confirm the item and final price before we spend money on the supplier order.</div>{error&&<p className="bg-red-950 p-3 text-xs text-white">{error}</p>}<button disabled={busy} className="btn btn-dark w-full disabled:opacity-50">{busy?'Sending request…':'Request pre-order'}</button></form></div></main>
}
function Field({name,label,required,type='text',wide=false,defaultValue}:{name:string;label:string;required?:boolean;type?:string;wide?:boolean;defaultValue?:string}){return <label className={wide?'text-xs sm:col-span-2':'text-xs'}>{label}<input name={name} required={required} type={type} className="field mt-2" defaultValue={defaultValue}/></label>}
