import { useEffect,useMemo,useState,type FormEvent } from "react";
import { useLocation,useParams,useSearchParams } from "react-router-dom";
import { Search,SlidersHorizontal,X } from "lucide-react";
import { AnimatePresence,motion } from "framer-motion";
import { ProductCard } from "../components/ProductCard";
import { Seo } from "../components/Seo";
import { useStore } from "../features/store/StoreContext";
import { useShopProducts } from "../hooks/usePublicData";

export default function ShopPage(){
  const {slug}=useParams(),location=useLocation(),[params,setParams]=useSearchParams(),{data}=useStore(),[filtersOpen,setFiltersOpen]=useState(false),[search,setSearch]=useState(params.get("q")||"");
  const categories=data.categories.filter(item=>item.active),collections=data.collections.filter(item=>item.active),routeCategory=location.pathname.startsWith("/category/")?categories.find(item=>item.slug===slug):undefined,routeCollection=location.pathname.startsWith("/collections/")?collections.find(item=>item.slug===slug):undefined;
  const rootCategory=routeCategory?.parentId?categories.find(item=>item.id===routeCategory.parentId):routeCategory,subcategories=rootCategory?categories.filter(item=>item.parentId===rootCategory.id).sort((a,b)=>a.sortOrder-b.sortOrder):[];
  const value=(key:string,fallback="all")=>params.get(key)||fallback,cat=value("category",routeCategory?.slug||"all"),collection=value("collection",routeCollection?.slug||"all"),size=value("size"),color=value("color"),sort=value("sort","newest"),available=params.get("available")==="true",page=Math.max(1,Number(params.get("page"))||1),maxPrice=Number(params.get("maxPrice"))||0;
  useEffect(()=>setSearch(params.get("q")||""),[params]);
  const apiQuery=useMemo(()=>{const query=new URLSearchParams({page:String(page),pageSize:"24",sort});const q=params.get("q")?.trim();if(q)query.set("q",q);if(cat!=="all")query.set("category",cat);if(collection!=="all")query.set("collection",collection);if(size!=="all")query.set("size",size);if(color!=="all")query.set("color",color);if(available)query.set("available","true");if(maxPrice)query.set("maxPrice",String(maxPrice));if(params.get("new")==="true")query.set("new","true");return query.toString();},[available,cat,collection,color,maxPrice,page,params,size,sort]);
  const result=useShopProducts(apiQuery),payload=result.data,priceCeiling=Math.max(1000,Math.ceil((payload?.filters.maxPrice||1000)/1000)*1000),title=routeCollection?.name||routeCategory?.name||(params.get("q")?"Search":"Shop");
  const update=(key:string,next:string|boolean)=>{const query=new URLSearchParams(params);if(next==="all"||next===""||next===false)query.delete(key);else query.set(key,String(next));if(key!=="page")query.delete("page");setParams(query);};
  function submitSearch(event:FormEvent){event.preventDefault();update("q",search.trim());}
  const categoryOptions=rootCategory?[[rootCategory.slug,"All "+rootCategory.name],...subcategories.map(item=>[item.slug,item.name])]:categories.filter(item=>!item.parentId).sort((a,b)=>a.sortOrder-b.sortOrder).map(item=>[item.slug,item.name]);
  const controls=<div className="space-y-6"><Filter label={rootCategory?rootCategory.name+" styles":"Category"} value={cat} onChange={next=>update("category",next)} options={categoryOptions} allowAll={!rootCategory}/><Filter label="Size" value={size} onChange={next=>update("size",next)} options={(payload?.filters.sizes||[]).map(item=>[item,item])}/><Filter label="Sort" value={sort} onChange={next=>update("sort",next)} options={[["newest","Newest"],["low","Price low–high"],["high","Price high–low"]]} allowAll={false}/><label className="flex min-h-11 items-center gap-3 text-sm"><input type="checkbox" checked={available} onChange={event=>update("available",event.target.checked)} className="h-5 w-5 accent-black"/> Available only</label><details className="border-t border-black/10 pt-5"><summary className="cursor-pointer text-[10px] font-medium uppercase tracking-[.18em] text-ink/60">More filters</summary><div className="mt-5 space-y-6"><Filter label="Collection" value={collection} onChange={next=>update("collection",next)} options={collections.map(item=>[item.slug,item.name])}/><Filter label="Colour" value={color} onChange={next=>update("color",next)} options={(payload?.filters.colors||[]).map(item=>[item,item])}/><div><p className="eyebrow mb-3">Up to LKR {(maxPrice||priceCeiling).toLocaleString()}</p><input aria-label="Maximum price" className="w-full accent-black" type="range" min="1000" max={priceCeiling} step="1000" value={maxPrice||priceCeiling} onChange={event=>update("maxPrice",event.target.value===String(priceCeiling)?"":event.target.value)}/></div></div></details></div>;
  return <><Seo title={params.get("q")?`Search: ${params.get("q")}`:title}/><div className="container pb-24 pt-28 lg:pt-[118px]"><div className="mb-5 flex flex-wrap items-end justify-between gap-5"><div><p className="eyebrow text-bronze">The ZEVENRA edit</p><h1 className="display mt-2 text-5xl md:text-7xl">{title}</h1><p className="mt-3 text-[10px] tracking-[.16em] text-ink/45">{payload?.total||0} PIECES{params.get("q")?` · “${params.get("q")}”`:""}</p></div><button onClick={()=>setFiltersOpen(true)} className="btn lg:hidden"><SlidersHorizontal size={15}/> Filter</button></div>
  <form onSubmit={submitSearch} className="shop-search mb-6 flex" role="search"><Search size={17} className="my-auto shrink-0"/><input aria-label="Search products" autoFocus={params.has("focusSearch")} value={search} onChange={event=>setSearch(event.target.value)} placeholder="Search products" className="min-w-0 flex-1 bg-transparent text-sm outline-none"/>{search&&<button type="button" onClick={()=>{setSearch("");update("q","");}} aria-label="Clear search" className="shop-search__action"><X size={15}/></button>}<button aria-label="Submit search" className="shop-search__action"><Search size={15}/></button></form>
  {rootCategory&&subcategories.length>0&&<section className="shop-style-filter" aria-label={`${rootCategory.name} styles`}><div className="shop-style-filter__head"><div><p className="eyebrow text-bronze">Shop {rootCategory.name}</p><h2>Choose your style</h2></div></div><div className="shop-style-filter__rail hide-scrollbar"><button type="button" onClick={()=>update("category",rootCategory.slug)} className={`shop-style-card ${cat===rootCategory.slug?"is-active":""}`}><div className="shop-style-card__all">ALL</div><span>ALL {rootCategory.name.toUpperCase()}</span></button>{subcategories.map(child=><button type="button" key={child.id} onClick={()=>update("category",child.slug)} className={`shop-style-card ${cat===child.slug?"is-active":""}`}>{child.imageUrl?<img src={child.imageUrl} alt="" loading="lazy"/>:<div className="shop-style-card__all">{child.name.slice(0,2).toUpperCase()}</div>}<span>{child.name.toUpperCase()}</span></button>)}</div></section>}
  <div className="grid gap-12 lg:grid-cols-[220px_1fr]"><aside className="hidden lg:block">{controls}</aside><div>{result.loading?<div className="shop-product-grid grid grid-cols-2 gap-x-3 gap-y-10 md:grid-cols-3 xl:grid-cols-4 lg:gap-x-4" aria-label="Loading products">{Array.from({length:8},(_,index)=><div key={index} className="home-skeleton"><div/></div>)}</div>:result.error?<div className="grid min-h-96 place-content-center text-center"><h2 className="display text-4xl">The edit is temporarily unavailable.</h2><button className="btn mx-auto mt-6" onClick={()=>void result.retry()}>Retry</button></div>:payload?.items.length?<><div className="shop-product-grid grid grid-cols-2 gap-x-3 gap-y-10 md:grid-cols-3 xl:grid-cols-4 lg:gap-x-4">{payload.items.map(product=><ProductCard key={product.id} product={product}/>)}</div>{payload.pageCount>1&&<nav className="mt-14 flex items-center justify-center gap-3" aria-label="Product pages"><button className="btn" disabled={page<=1} onClick={()=>update("page",String(page-1))}>Previous</button><span className="text-xs">{page} / {payload.pageCount}</span><button className="btn" disabled={page>=payload.pageCount} onClick={()=>update("page",String(page+1))}>Next</button></nav>}</>:<div className="grid min-h-96 place-content-center text-center"><h2 className="display text-4xl">Nothing found.</h2><p className="mt-3 text-sm text-ink/50">Try adjusting your filters.</p></div>}</div></div></div>
  <AnimatePresence>{filtersOpen&&<><motion.button aria-label="Close filters" className="fixed inset-0 z-50 bg-black/60" onClick={()=>setFiltersOpen(false)} initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}}/><motion.div role="dialog" aria-modal="true" aria-label="Product filters" className="fixed inset-x-0 bottom-0 z-50 max-h-[88svh] overflow-auto bg-paper p-6" initial={{y:"100%"}} animate={{y:0}} exit={{y:"100%"}}><div className="mb-7 flex items-center justify-between"><p className="eyebrow">Filter the edit</p><button onClick={()=>setFiltersOpen(false)} aria-label="Close filters" className="min-h-11 min-w-11"><X/></button></div>{controls}<button onClick={()=>setFiltersOpen(false)} className="btn btn-dark mt-8 w-full">Show {payload?.total||0} pieces</button></motion.div></>}</AnimatePresence></>;
}
function Filter({label,value,onChange,options,allowAll=true}:{label:string;value:string;onChange:(value:string)=>void;options:string[][];allowAll?:boolean}){return <div><p className="eyebrow mb-3">{label}</p><select aria-label={label} value={value} onChange={event=>onChange(event.target.value)} className="field">{allowAll&&<option value="all">All</option>}{options.map(([option,label])=><option key={option} value={option}>{label}</option>)}</select></div>}
