import {AnimatePresence,motion} from 'framer-motion';
import {Minus,Plus,X} from 'lucide-react';
import {Link} from 'react-router-dom';
import {useCart} from '../features/cart/CartContext';
import {useStore} from '../features/store/StoreContext';
import {money} from '../config/site';

export function CartDrawer(){
 const c=useCart(),{data}=useStore();
 const currentPrice=(item:typeof c.items[number])=>data.products.find(p=>p.id===item.productId&&p.status==='published')?.price??item.unitPrice;
 const valid=(item:typeof c.items[number])=>{const product=data.products.find(p=>p.id===item.productId&&p.status==='published'),variant=product?.variants.find(v=>v.id===item.variantId&&v.active);return Boolean(product&&variant&&variant.stock>=item.quantity)};
 const subtotal=c.items.reduce((sum,item)=>sum+currentPrice(item)*item.quantity,0),canCheckout=c.items.length>0&&c.items.every(valid);
 return <AnimatePresence>{c.open&&<><motion.button aria-label="Close bag" className="fixed inset-0 z-50 bg-black/50" onClick={()=>c.setOpen(false)} initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}}/><motion.aside role="dialog" aria-modal="true" aria-label="Shopping bag" className="fixed right-0 top-0 z-50 flex h-dvh w-full max-w-md flex-col bg-paper p-5 sm:p-7" initial={{x:'100%'}} animate={{x:0}} exit={{x:'100%'}} transition={{type:'tween',duration:.35}}><div className="flex items-center justify-between border-b hairline pb-5"><p className="eyebrow">Your Bag · {c.count}</p><button className="p-2" onClick={()=>c.setOpen(false)} aria-label="Close"><X/></button></div><div className="flex-1 overflow-y-auto py-3">{c.items.length===0?<div className="grid h-full place-content-center text-center"><p className="display text-3xl">Your bag is waiting.</p><Link to="/shop" onClick={()=>c.setOpen(false)} className="mt-5 underline underline-offset-4">Explore the collection</Link></div>:c.items.map(i=>{const available=valid(i);return <div key={i.variantId} className="flex gap-4 border-b hairline py-5">{i.image?<img src={i.image} alt={i.name} className="h-28 w-20 object-cover"/>:<div className="h-28 w-20 shrink-0 bg-black/5"/>}<div className="min-w-0 flex-1"><p className="text-sm">{i.name}</p><p className="mt-1 text-xs text-ink/55">{i.color} / {i.size}</p>{!available&&<p className="mt-2 text-[10px] leading-4 text-red-800">Availability changed. Review this item before checkout.</p>}<div className="mt-5 flex items-center gap-3"><button aria-label="Decrease quantity" onClick={()=>c.quantity(i.variantId,i.quantity-1)}><Minus size={15}/></button><span className="text-sm">{i.quantity}</span><button aria-label="Increase quantity" disabled={i.maxStock!==undefined&&i.quantity>=i.maxStock} onClick={()=>c.quantity(i.variantId,i.quantity+1)}><Plus size={15}/></button><button className="ml-auto text-xs underline" onClick={()=>c.remove(i.variantId)}>Remove</button></div></div><p className="text-sm">{money(currentPrice(i)*i.quantity)}</p></div>})}</div>{c.items.length>0&&<div className="border-t hairline pt-5"><div className="mb-5 flex justify-between"><span>Subtotal</span><span>{money(subtotal)}</span></div>{canCheckout?<Link to="/checkout" onClick={()=>c.setOpen(false)} className="btn btn-dark w-full">Checkout</Link>:<button disabled className="btn btn-dark w-full opacity-40">Review bag</button>}<Link to="/cart" onClick={()=>c.setOpen(false)} className="mt-2 flex min-h-11 items-center justify-center text-xs underline">View full bag</Link></div>}</motion.aside></>}</AnimatePresence>
}
