import { neon } from "@neondatabase/serverless";

const connectionString=process.env.DATABASE_URL;
if(!connectionString){console.error("FAIL configuration: DATABASE_URL is required");process.exit(1);}
const sql=neon(connectionString,{fullResults:true});
const run=async(text,values=[])=>{try{return await sql.query(text,values);}catch(error){if(!/connection|timeout|fetch failed|ECONNRESET|socket|terminated/i.test(error instanceof Error?error.message:String(error)))throw error;return sql.query(text,values);}};
const checks=[];
const planReports=[];
async function check(name,work){const started=performance.now();try{await work();checks.push({name,ok:true,ms:performance.now()-started});}catch(error){checks.push({name,ok:false,ms:performance.now()-started,error:error instanceof Error?error.message:"Unknown query error"});}}

let product=null;
await check("public/store bootstrap",async()=>Promise.all([run("SELECT * FROM categories ORDER BY sort_order,name"),run("SELECT * FROM collections ORDER BY sort_order,name"),run("SELECT * FROM navigation ORDER BY sort_order,label"),run("SELECT * FROM homepage_sections ORDER BY sort_order,id"),run("SELECT key,value FROM site_settings ORDER BY key")]));
await check("public/homepage",async()=>{const sections=await run("SELECT reference_id FROM homepage_sections WHERE enabled=true ORDER BY sort_order,id"),references=sections.rows.map(row=>row.reference_id).filter(Boolean);await run("SELECT p.id FROM products p WHERE p.status='published' AND (p.new_arrival=true OR p.featured=true OR p.id=ANY($1::text[]) OR p.category_id=ANY($1::text[])) ORDER BY p.sort_order,p.name LIMIT 64",[references]);});
await check("public/product by slug",async()=>{const result=await run("SELECT id,slug,category_id,size_chart_id,media FROM products WHERE status='published' ORDER BY sort_order,name LIMIT 1");product=result.rows[0]||null;if(product)await run("SELECT p.id,COALESCE((SELECT jsonb_agg(to_jsonb(v)) FROM variants v WHERE v.product_id=p.id),'[]') variants FROM products p WHERE p.slug=$1 AND p.status='published' LIMIT 1",[product.slug]);});
await check("public/shop filters",async()=>Promise.all([run("SELECT count(*)::int count FROM products p WHERE p.status='published'"),run("SELECT p.id FROM products p WHERE p.status='published' ORDER BY p.updated_at DESC LIMIT $1 OFFSET $2",[24,0]),run("SELECT min(price),max(price) FROM products WHERE status='published'")]));
await check("public/recommendations",async()=>{if(product)await run("SELECT p.id FROM products p WHERE p.status='published' AND NOT(p.id=ANY($1::text[])) ORDER BY (p.category_id=ANY($2::text[])) DESC,p.featured DESC,p.sort_order LIMIT 8",[[product.id],[product.category_id]]);});
await check("public/cart hydration",async()=>{const variants=await run("SELECT id FROM variants WHERE active=true LIMIT 2");await run("SELECT v.id,p.id product_id FROM variants v JOIN products p ON p.id=v.product_id WHERE v.id=ANY($1::text[])",[variants.rows.map(row=>row.id)]);});
await check("public/checkout config",async()=>Promise.all([run("SELECT key,value FROM site_settings ORDER BY key"),run("SELECT * FROM courier_providers WHERE active=true ORDER BY name"),run("SELECT * FROM delivery_rates ORDER BY sort_order,name")]));
await check("admin/dashboard",async()=>Promise.all([run("SELECT count(*)::int count FROM orders"),run("SELECT count(*)::int count FROM products WHERE status='published'"),run("SELECT count(*)::int count FROM preorders")]));
await check("admin/product filters",async()=>Promise.all([run("SELECT count(*)::int count FROM products p"),run("SELECT p.id,COALESCE(sum(v.stock) FILTER(WHERE v.active),0)::int total_stock FROM products p LEFT JOIN variants v ON v.product_id=p.id GROUP BY p.id ORDER BY p.updated_at DESC LIMIT $1 OFFSET $2",[25,0])]));
await check("admin/reference data",async()=>Promise.all([run("SELECT * FROM categories ORDER BY sort_order,name"),run("SELECT * FROM collections ORDER BY sort_order,name"),run("SELECT * FROM site_settings ORDER BY key"),run("SELECT * FROM courier_providers ORDER BY name"),run("SELECT * FROM delivery_rates ORDER BY sort_order,name")]));
await check("admin/orders",async()=>run("SELECT * FROM orders ORDER BY created_at DESC LIMIT $1",[50]));
await check("admin/preorders",async()=>run("SELECT * FROM preorders ORDER BY created_at DESC LIMIT $1",[50]));
await check("admin/courier rate cards",async()=>run("SELECT c.id,c.status,p.name courier_name FROM courier_rate_cards c JOIN courier_providers p ON p.id=c.courier_provider_id ORDER BY c.imported_at DESC"));
await check("customer read paths",async()=>Promise.all([run("SELECT id FROM customers ORDER BY created_at DESC LIMIT 1"),run("SELECT order_id FROM orders WHERE customer_id IS NOT NULL ORDER BY created_at DESC LIMIT 1"),run("SELECT request_id FROM preorders WHERE customer_id IS NOT NULL ORDER BY created_at DESC LIMIT 1")]));
await check("query plans",async()=>{for(const [name,text,values] of [["product by slug","SELECT id FROM products WHERE slug=$1 AND status='published' LIMIT 1",[product?.slug||""]],["published pagination","SELECT id FROM products WHERE status='published' ORDER BY updated_at DESC LIMIT 24",[]],["homepage products","SELECT id FROM products WHERE status='published' AND (featured=true OR new_arrival=true) ORDER BY sort_order LIMIT 64",[]],["recommendations","SELECT id FROM products WHERE status='published' ORDER BY featured DESC,sort_order LIMIT 8",[]],["admin product filters","SELECT id FROM products ORDER BY updated_at DESC LIMIT 25",[]],["order list","SELECT order_id FROM orders ORDER BY created_at DESC LIMIT 50",[]],["delivery matching","SELECT id FROM delivery_rates WHERE active=true AND $1=ANY(districts) ORDER BY sort_order",["Colombo"]]]){const result=await run(`EXPLAIN (FORMAT JSON) ${text}`,values),root=result.rows[0]["QUERY PLAN"][0].Plan,nodes=[];const walk=node=>{nodes.push(`${node["Node Type"]}${node["Index Name"]?`:${node["Index Name"]}`:""}`);for(const child of node.Plans||[])walk(child);};walk(root);planReports.push(`${name}: ${nodes.join(" > ")} (cost ${root["Total Cost"]})`);}});

for(const item of checks)console.log(`${item.ok?"PASS":"FAIL"} ${item.name} ${item.ms.toFixed(1)}ms${item.error?` — ${item.error}`:""}`);
for(const plan of planReports)console.log(`PLAN ${plan}`);
if(checks.some(item=>!item.ok))process.exitCode=1;
