import { neon } from "@neondatabase/serverless";

const connectionString=process.env.DATABASE_URL;
if(!connectionString){console.error("FAIL configuration: DATABASE_URL is required");process.exit(1);}
const sql=neon(connectionString,{fullResults:true});
const run=async(text,values=[])=>{try{return await sql.query(text,values);}catch(error){if(!/connection|timeout|fetch failed|ECONNRESET|socket|terminated/i.test(error instanceof Error?error.message:String(error)))throw error;return sql.query(text,values);}};
const checks=[],planReports=[];
const assert=(condition,message)=>{if(!condition)throw new Error(message);};
async function check(name,work){const started=performance.now();try{await work();checks.push({name,ok:true,ms:performance.now()-started});}catch(error){checks.push({name,ok:false,ms:performance.now()-started,error:error instanceof Error?error.message:"Unknown query error"});}}
const rows=async(text,values=[])=>(await run(text,values)).rows;
const count=async(text,values=[])=>Number((await rows(text,values))[0]?.count||0);

let product=null;
await check("public/store bootstrap",async()=>Promise.all([run("SELECT id,name,slug,parent_id,active,sort_order FROM categories ORDER BY sort_order,name"),run("SELECT id,name,slug,active,sort_order FROM collections ORDER BY sort_order,name"),run("SELECT id,label,target,link_type,visible,sort_order FROM navigation ORDER BY sort_order,label"),run("SELECT id,type,title,reference_id,enabled,sort_order FROM homepage_sections ORDER BY sort_order,id"),run("SELECT key,value FROM site_settings ORDER BY key")]));
await check("public/homepage",async()=>{const sections=await rows("SELECT reference_id FROM homepage_sections WHERE enabled=true ORDER BY sort_order,id"),references=sections.map(row=>row.reference_id).filter(Boolean);await run("SELECT p.id FROM products p WHERE p.status='published' AND (p.new_arrival=true OR p.featured=true OR p.id=ANY($1::text[]) OR p.category_id=ANY($1::text[])) ORDER BY p.sort_order,p.name LIMIT 64",[references]);});
await check("public/product by slug",async()=>{const result=await run("SELECT id,slug,category_id,size_chart_id,media FROM products WHERE status='published' ORDER BY sort_order,name LIMIT 1");product=result.rows[0]||null;if(product)await run("SELECT p.id,COALESCE((SELECT jsonb_agg(to_jsonb(v)) FROM variants v WHERE v.product_id=p.id),'[]') variants FROM products p WHERE p.slug=$1 AND p.status='published' LIMIT 1",[product.slug]);});
await check("public/shop filters",async()=>Promise.all([run("SELECT count(*)::int count FROM products p WHERE p.status='published'"),run("SELECT p.id FROM products p WHERE p.status='published' ORDER BY p.updated_at DESC LIMIT $1 OFFSET $2",[24,0]),run("SELECT min(price),max(price) FROM products WHERE status='published'")]));
await check("public/cart hydration",async()=>{const variants=await rows("SELECT id FROM variants WHERE active=true LIMIT 2");await run("SELECT v.id,p.id product_id FROM variants v JOIN products p ON p.id=v.product_id WHERE v.id=ANY($1::text[])",[variants.map(row=>row.id)]);});

await check("fulfillment/method records",async()=>{const methods=await rows("SELECT type,display_name,active,fee,minimum_delivery_days,maximum_delivery_days,sort_order FROM delivery_methods ORDER BY sort_order,type");assert(methods.length===3,"expected exactly flat, area_group and pickup delivery methods");assert(methods.map(x=>x.type).sort().join(",")==="area_group,flat,pickup","delivery method types are incomplete or invalid");});
await check("fulfillment/default area groups",async()=>{const groups=await rows("SELECT id,name,fee,active,is_fallback,sort_order FROM delivery_area_groups ORDER BY sort_order,id"),expected=["colombo-city","colombo-suburbs","western-other","major-outstation","other-outstation"];assert(groups.length===5&&groups.map(x=>x.id).sort().join(",")===expected.sort().join(","),"area groups must be exactly the five seeded groups");});
await check("fulfillment/area configuration",async()=>{const active=await count("SELECT count(*) count FROM delivery_methods WHERE type='area_group' AND active"),fallback=await count("SELECT count(*) count FROM delivery_area_groups WHERE active AND is_fallback"),missingFees=await count("SELECT count(*) count FROM delivery_area_groups WHERE active AND fee IS NULL");if(active){assert(fallback===1,"active area delivery requires exactly one active fallback group");assert(missingFees===0,"active area delivery requires fees on every active group");}});
await check("fulfillment/Colombo mappings",async()=>{const locations=await rows("SELECT town,normalized_town,postcode,group_id FROM delivery_area_locations WHERE id ~ '^colombo-(0[1-9]|1[0-5])$' ORDER BY postcode");assert(locations.length===15,"Colombo 01-15 mappings are incomplete");for(let n=1;n<=15;n++){const x=locations[n-1],postcode=String(n).padStart(3,"0")+"00";assert(x?.group_id==="colombo-city"&&x.postcode===postcode&&x.normalized_town===`colombo ${n}`,`invalid Colombo ${String(n).padStart(2,"0")} mapping`);}});
await check("fulfillment/Western defaults",async()=>{const defaults=await rows("SELECT district,group_id FROM delivery_district_defaults ORDER BY district"),expected=new Map([["Colombo","western-other"],["Gampaha","western-other"],["Kalutara","western-other"]]);for(const [district,group] of expected)assert(defaults.some(x=>x.district===district&&x.group_id===group),`missing ${district} district default`);assert(await count("SELECT count(*) count FROM delivery_district_defaults d LEFT JOIN delivery_area_groups g ON g.id=d.group_id WHERE g.id IS NULL OR NOT g.active")===0,"district defaults reference missing/inactive groups");});
await check("fulfillment/location integrity",async()=>{assert(await count("SELECT count(*) count FROM delivery_area_locations l LEFT JOIN delivery_area_groups g ON g.id=l.group_id WHERE g.id IS NULL")===0,"location mapping references an invalid group");assert(await count("SELECT count(*) count FROM (SELECT lower(btrim(district)),normalized_town,COALESCE(postcode,'') FROM delivery_area_locations WHERE active GROUP BY 1,2,3 HAVING count(*)>1) d")===0,"duplicate active district+town+postcode identity");});
await check("fulfillment/pickup integrity",async()=>{assert(await count("SELECT count(*) count FROM pickup_locations WHERE active AND (btrim(name)='' OR btrim(address)='')")===0,"active pickup branches require name and address");const pickupActive=await count("SELECT count(*) count FROM delivery_methods WHERE type='pickup' AND active");if(pickupActive)assert(await count("SELECT count(*) count FROM pickup_locations WHERE active")>0,"active pickup requires an active branch");});
await check("fulfillment/flat integrity",async()=>{assert(await count("SELECT count(*) count FROM delivery_methods WHERE type='flat' AND active AND (fee IS NULL OR fee<0)")===0,"active flat delivery requires a non-negative fee");});
await check("fulfillment/checkout consistency",async()=>{const enabled=await count("SELECT count(*) count FROM site_settings WHERE key='ordersEnabled' AND lower(value #>> '{}')='true'");if(enabled){assert(await count("SELECT count(*) count FROM delivery_methods WHERE active")>0,"orders are enabled without fulfillment");const payment=await count("SELECT count(*) count FROM site_settings WHERE key IN ('codEnabled','bankEnabled','bankTransferEnabled') AND lower(value #>> '{}')='true'");assert(payment>0,"orders are enabled without a payment method");}});

const preorderList="SELECT request_id,created_at,updated_at,customer_id,customer_name,phone,whatsapp,email,address1,address2,city,district,postal_code,product_id,variant_id,product_name,sku,color,size,quantity,requested_price,confirmed_price,status,batch_id,notes FROM preorders ORDER BY created_at DESC LIMIT 50";
const orderList="SELECT order_id,created_at,customer_name,phone,city,district,fulfillment_method,delivery_method_name,pickup_branch_name,payment_method,payment_status,subtotal,discount_amount,delivery_fee,total,order_status,source,stock_state FROM orders ORDER BY created_at DESC LIMIT 50";
const fulfillmentList="SELECT type,display_name,active,fee,minimum_delivery_days,maximum_delivery_days,sort_order FROM delivery_methods ORDER BY sort_order,type";
await check("admin/orders list",async()=>run(orderList));
await check("admin/preorders list",async()=>run(preorderList));
await check("public/checkout fulfillment config",async()=>Promise.all([run(fulfillmentList),run("SELECT id,name,fee,active,is_fallback,sort_order FROM delivery_area_groups ORDER BY sort_order,id"),run("SELECT id,name,address,instructions,active,sort_order FROM pickup_locations WHERE active ORDER BY sort_order,name")]));
await check("customer read paths",async()=>Promise.all([run("SELECT id FROM customers ORDER BY created_at DESC LIMIT 1"),run("SELECT order_id FROM orders WHERE customer_id IS NOT NULL ORDER BY created_at DESC LIMIT 1"),run("SELECT request_id FROM preorders WHERE customer_id IS NOT NULL ORDER BY created_at DESC LIMIT 1")]));

await check("measured query plans",async()=>{for(const [name,text,values] of [["product lookup","SELECT id,slug,category_id,size_chart_id,media FROM products WHERE slug=$1 AND status='published' LIMIT 1",[product?.slug||""]],["admin orders",orderList,[]],["admin preorders",preorderList,[]],["checkout fulfillment",fulfillmentList,[]]]){const started=performance.now(),result=await run(`EXPLAIN (ANALYZE, BUFFERS, FORMAT JSON) ${text}`,values),roundTrip=performance.now()-started,report=result.rows[0]["QUERY PLAN"][0],root=report.Plan,nodes=[];const walk=node=>{nodes.push(`${node["Node Type"]}${node["Index Name"]?`:${node["Index Name"]}`:""}`);for(const child of node.Plans||[])walk(child);};walk(root);planReports.push(`${name}: server ${Number(report["Execution Time"]).toFixed(3)}ms, planning ${Number(report["Planning Time"]).toFixed(3)}ms, client ${roundTrip.toFixed(1)}ms, ${nodes.join(" > ")}, rows ${root["Actual Rows"]}`);}});

for(const item of checks)console.log(`${item.ok?"PASS":"FAIL"} ${item.name} ${item.ms.toFixed(1)}ms${item.error?` — ${item.error}`:""}`);
for(const plan of planReports)console.log(`PERF ${plan}`);
if(checks.some(item=>!item.ok))process.exitCode=1;
