/** ZEVENRA temporary data API. Set APPS_SCRIPT_SECRET in Script Properties before deployment. */
const SCHEMA={Products:['id','slug','name','shortDescription','description','price','compareAtPrice','categoryId','subcategory','mediaJson','sizeChartId','material','fit','care','tags','featured','newArrival','status','sortOrder','createdAt','updatedAt'],Variants:['id','productId','sku','color','size','stock','lowStockThreshold','active'],Categories:['id','name','slug','description','imageUrl','mobileImageUrl','videoUrl','active','featured','showInNavigation','showOnHomepage','parentId','sortOrder'],Collections:['id','name','slug','description','heroImage','mobileImage','videoUrl','ctaLabel','active','showInNavigation','showOnHomepage','startDate','endDate','sortOrder'],ProductCollections:['productId','collectionId'],SizeCharts:['id','name','unit','columnsJson','rowsJson','imageUrl','notes'],Navigation:['id','label','linkType','target','visible','sortOrder'],HomepageSections:['id','type','enabled','title','subtitle','desktopMedia','mobileMedia','ctaLabel','ctaLink','referenceId','textPosition','overlay','spacing','sortOrder'],Orders:['orderId','createdAt','customerId','customerName','phone','whatsapp','email','address1','address2','city','district','postalCode','deliveryNotes','paymentMethod','subtotal','deliveryFee','total','orderStatus','paymentStatus','source','stockDeducted','updatedAt'],OrderItems:['orderId','productId','variantId','sku','productName','color','size','quantity','unitPrice','lineTotal'],Customers:['id','firstName','lastName','email','mobile','passwordHash','passwordSalt','status','createdAt','updatedAt','lastLoginAt'],SiteSettings:['key','value'],DeliveryRates:['id','district','fee','active'],AuditLog:['timestamp','admin','action','entityType','entityId','details'],SchemaVersion:['version','appliedAt','description']};
function setup(){migrateDatabase();seedSettings_();return 'ZEVENRA sheets are ready.'}
function migrateDatabase(){const lock=LockService.getScriptLock();lock.waitLock(30000);try{const ss=SpreadsheetApp.getActive();Object.keys(SCHEMA).forEach(name=>{let sh=ss.getSheetByName(name);if(!sh){sh=ss.insertSheet(name);sh.appendRow(SCHEMA[name]);logMigration_('create-sheet','Created '+name);return}if(sh.getLastRow()===0)sh.appendRow(SCHEMA[name]);const existing=sh.getRange(1,1,1,Math.max(1,sh.getLastColumn())).getValues()[0].map(String);SCHEMA[name].forEach(column=>{if(existing.indexOf(column)<0){sh.getRange(1,sh.getLastColumn()+1).setValue(column);existing.push(column);logMigration_('add-column','Added '+name+'.'+column)}});sh.setFrozenRows(1);sh.getRange(1,1,1,sh.getLastColumn()).setFontWeight('bold').setBackground('#171613').setFontColor('#f4efe5')});backfillOrderCustomerIds_();const versions=read_('SchemaVersion');if(!versions.some(v=>String(v.version)==='2'))append_('SchemaVersion',{version:2,appliedAt:new Date().toISOString(),description:'Dynamic storefront, navigation and homepage schema'});return 'Database is at schema version 2. Existing rows were preserved.'}finally{lock.releaseLock()}}
function backfillOrderCustomerIds_(){const customers=read_('Customers'),byEmail={};customers.forEach(customer=>{const email=String(customer.email||'').trim().toLowerCase();if(email)byEmail[email]=String(customer.id)});const sh=sheet_('Orders'),data=sh.getDataRange().getValues(),headers=data[0],customerIdIndex=headers.indexOf('customerId'),emailIndex=headers.indexOf('email');if(customerIdIndex<0||emailIndex<0)return;for(let row=1;row<data.length;row++){if(String(data[row][customerIdIndex]||''))continue;const customerId=byEmail[String(data[row][emailIndex]||'').trim().toLowerCase()];if(customerId)sh.getRange(row+1,customerIdIndex+1).setValue(customerId)}}
function logMigration_(action,description){const ss=SpreadsheetApp.getActive(),sh=ss.getSheetByName('AuditLog');if(sh&&sh.getLastRow()>0)append_('AuditLog',{timestamp:new Date().toISOString(),admin:'migration',action,entityType:'schema',entityId:'v2',details:description})}
function seedSettings_(){const sh=sheet_('SiteSettings');if(sh.getLastRow()>1)return;[['announcement','Islandwide Delivery'],['deliveryFlatFee','450'],['freeDeliveryThreshold','15000'],['deliveryEnabled','true'],['codEnabled','true'],['bankTransferEnabled','true'],['whatsapp',''],['bankName',''],['bankAccountName',''],['bankAccountNumber',''],['bankBranch','']].forEach(r=>sh.appendRow(r))}
function doPost(e){try{const req=JSON.parse(e.postData.contents||'{}');const secret=PropertiesService.getScriptProperties().getProperty('APPS_SCRIPT_SECRET');if(!secret||req.token!==secret)return out_({ok:false,error:'Unauthorized'});const actions={listPublishedProducts:listPublishedProducts_,getProduct:getProduct_,createOrder:createOrder_,createCustomer:createCustomer_,getCustomerByEmail:getCustomerByEmail_,getCustomerById:getCustomerById_,updateCustomerLastLogin:updateCustomerLastLogin_,listCustomerOrders:listCustomerOrders_,dashboard:dashboard_,listProducts:listProducts_,saveProduct:saveProduct_,archiveProduct:p=>patch_('Products','id',p.id,{status:'archived',updatedAt:new Date().toISOString()}),deleteProduct:deleteProduct_,listCategories:()=>read_('Categories'),saveCategory:p=>upsert_('Categories','id',p),deleteCategory:p=>remove_('Categories','id',p.id),listCollections:()=>read_('Collections'),saveCollection:p=>upsert_('Collections','id',p),deleteCollection:p=>remove_('Collections','id',p.id),listSizeCharts:()=>read_('SizeCharts'),saveSizeChart:saveSizeChart_,deleteSizeChart:p=>remove_('SizeCharts','id',p.id),listNavigation:()=>read_('Navigation'),saveNavigation:p=>upsert_('Navigation','id',p),deleteNavigation:p=>remove_('Navigation','id',p.id),listHomepageSections:()=>read_('HomepageSections'),saveHomepageSection:p=>upsert_('HomepageSections','id',p),deleteHomepageSection:p=>remove_('HomepageSections','id',p.id),listOrders:listOrders_,getOrder:getOrder_,updateOrder:updateOrder_,getSettings:()=>read_('SiteSettings'),saveSettings:saveSettings_,listDeliveryRates:()=>read_('DeliveryRates'),saveDeliveryRates:saveDeliveryRates_};if(!actions[req.action])throw new Error('Unknown action');return out_({ok:true,data:actions[req.action](req.payload||{})})}catch(err){return out_({ok:false,error:String(err.message||err)})}}
function listPublishedProducts_(){return joinProducts_(read_('Products').filter(p=>p.status==='published'))}
function listProducts_(){return joinProducts_(read_('Products'))}
function getProduct_(p){return listPublishedProducts_().find(x=>x.slug===p.slug)||null}
function joinProducts_(products){const variants=read_('Variants'),links=read_('ProductCollections');return products.map(p=>Object.assign({},p,{media:safeJson_(p.mediaJson,[]),tags:String(p.tags||'').split(',').filter(Boolean),collectionIds:links.filter(x=>x.productId===p.id).map(x=>x.collectionId),featured:bool_(p.featured),newArrival:bool_(p.newArrival),variants:variants.filter(v=>v.productId===p.id).map(v=>Object.assign({},v,{stock:Number(v.stock),lowStockThreshold:Number(v.lowStockThreshold),active:bool_(v.active)}))}))}
function createOrder_(payload){const lock=LockService.getScriptLock();lock.waitLock(30000);try{const variants=read_('Variants'),products=read_('Products');let subtotal=0;const lines=payload.items.map(item=>{const v=variants.find(x=>x.id===item.variantId&&x.productId===item.productId&&bool_(x.active));const p=products.find(x=>x.id===item.productId&&x.status==='published');if(!v||!p||Number(v.stock)<Number(item.quantity))throw new Error('One or more selected items are no longer available.');const price=Number(p.price);subtotal+=price*item.quantity;return{orderId:'',productId:p.id,variantId:v.id,sku:v.sku,productName:p.name,color:v.color,size:v.size,quantity:item.quantity,unitPrice:price,lineTotal:price*item.quantity}});const settings=settings_();const districtRate=read_('DeliveryRates').find(r=>String(r.district).toLowerCase()===String(payload.district).toLowerCase()&&bool_(r.active));let fee=bool_(settings.deliveryEnabled)?Number(districtRate?districtRate.fee:settings.deliveryFlatFee||0):0;if(Number(settings.freeDeliveryThreshold)>0&&subtotal>=Number(settings.freeDeliveryThreshold))fee=0;const orderId=nextOrderId_();const now=new Date().toISOString();const order=Object.assign({orderId,createdAt:now},payload,{subtotal,deliveryFee:fee,total:subtotal+fee,orderStatus:'pending',paymentStatus:payload.paymentMethod==='cod'?'COD':'verification required',source:'web',stockDeducted:false,updatedAt:now});delete order.items;append_('Orders',order);lines.forEach(x=>{x.orderId=orderId;append_('OrderItems',x)});audit_('system','create','order',orderId,{total:order.total});return Object.assign(order,{items:lines})}finally{lock.releaseLock()}}
function createCustomer_(p){const lock=LockService.getScriptLock();lock.waitLock(30000);try{p=Object.assign({},p,{email:String(p.email||'').trim().toLowerCase(),status:'active'});if(!p.id||!p.email||!p.passwordHash||!p.passwordSalt)throw new Error('Invalid customer');if(read_('Customers').some(c=>String(c.email||'').trim().toLowerCase()===p.email))throw new Error('CUSTOMER_EXISTS');append_('Customers',p);audit_('system','create','customer',p.id,{email:p.email});return p}finally{lock.releaseLock()}}
function getCustomerByEmail_(p){const email=String(p.email||'').trim().toLowerCase();return read_('Customers').find(c=>String(c.email||'').trim().toLowerCase()===email)||null}
function getCustomerById_(p){return read_('Customers').find(c=>String(c.id)===String(p.id))||null}
function updateCustomerLastLogin_(p){const now=String(p.lastLoginAt||new Date().toISOString());patch_('Customers','id',p.id,{lastLoginAt:now,updatedAt:now});return{updated:true}}
function listCustomerOrders_(p){const email=String(p.email||'').trim().toLowerCase(),customer=getCustomerById_({id:p.customerId});if(!customer||String(customer.email||'').trim().toLowerCase()!==email)throw new Error('Customer mismatch');const items=read_('OrderItems');return read_('Orders').filter(o=>String(o.customerId||'')===String(customer.id)).reverse().map(o=>Object.assign({},o,{items:items.filter(i=>i.orderId===o.orderId)}))}
function nextOrderId_(){const tz=Session.getScriptTimeZone()||'Asia/Colombo',date=Utilities.formatDate(new Date(),tz,'yyMMdd'),prefix='ZEV-'+date+'-';const ids=read_('Orders').map(o=>String(o.orderId)).filter(x=>x.indexOf(prefix)===0);const max=ids.reduce((n,x)=>Math.max(n,Number(x.slice(-4))||0),0);return prefix+String(max+1).padStart(4,'0')}
function updateOrder_(p){const lock=LockService.getScriptLock();lock.waitLock(30000);try{const order=read_('Orders').find(o=>o.orderId===p.orderId);if(!order)throw new Error('Order not found');const was=bool_(order.stockDeducted),confirming=p.orderStatus==='confirmed'&&!was,cancelling=p.orderStatus==='cancelled'&&was;if(confirming||cancelling){const items=read_('OrderItems').filter(i=>i.orderId===p.orderId);items.forEach(i=>{const v=read_('Variants').find(x=>x.id===i.variantId);if(!v)throw new Error('Variant missing');const next=Number(v.stock)+(cancelling?Number(i.quantity):-Number(i.quantity));if(next<0)throw new Error('Insufficient stock');patch_('Variants','id',v.id,{stock:next})});p.stockDeducted=confirming}p.updatedAt=new Date().toISOString();patch_('Orders','orderId',p.orderId,p);audit_('owner','update','order',p.orderId,p);return getOrder_(p)}finally{lock.releaseLock()}}
function saveProduct_(input){const lock=LockService.getScriptLock();lock.waitLock(30000);try{const p=Object.assign({},input),variants=p.variants||[],collections=p.collectionIds||[],media=p.media||[];delete p.variants;delete p.collectionIds;delete p.media;p.mediaJson=JSON.stringify(media);p.tags=Array.isArray(p.tags)?p.tags.join(','):p.tags;p.updatedAt=new Date().toISOString();if(!p.id){p.id=Utilities.getUuid();p.createdAt=p.updatedAt}upsert_('Products','id',p);const kept={};variants.forEach(v=>{v=Object.assign({},v,{productId:p.id});if(!v.id)v.id=Utilities.getUuid();kept[v.id]=true;upsert_('Variants','id',v)});read_('Variants').filter(v=>v.productId===p.id&&!kept[v.id]).forEach(v=>remove_('Variants','id',v.id));remove_('ProductCollections','productId',p.id);collections.forEach(collectionId=>append_('ProductCollections',{productId:p.id,collectionId}));audit_('owner','save','product',p.id,{name:p.name});return listProducts_().find(x=>x.id===p.id)}finally{lock.releaseLock()}}
function saveSizeChart_(input){const p=Object.assign({},input,{columnsJson:JSON.stringify(input.columns||[]),rowsJson:JSON.stringify(input.rows||[])});delete p.columns;delete p.rows;return upsert_('SizeCharts','id',p)}
function deleteProduct_(p){const hasOrders=read_('OrderItems').some(i=>i.productId===p.id);if(hasOrders)throw new Error('Archive products that are referenced by orders.');remove_('Variants','productId',p.id);remove_('Products','id',p.id);audit_('owner','delete','product',p.id,{});return{deleted:true}}
function dashboard_(){const orders=read_('Orders'),today=Utilities.formatDate(new Date(),Session.getScriptTimeZone()||'Asia/Colombo','yyyy-MM-dd');const count=s=>orders.filter(o=>o.orderStatus===s).length;return{ordersToday:orders.filter(o=>String(o.createdAt).slice(0,10)===today).length,pending:count('pending'),confirmed:count('confirmed'),packed:count('packed'),shipped:count('shipped'),delivered:count('delivered'),cancelled:count('cancelled'),revenue:orders.filter(o=>o.orderStatus==='delivered').reduce((n,o)=>n+Number(o.total),0),recent:orders.slice(-10).reverse()}}
function listOrders_(p){let rows=read_('Orders').reverse();if(p.status)rows=rows.filter(o=>o.orderStatus===p.status);if(p.q){const q=String(p.q).toLowerCase();rows=rows.filter(o=>[o.orderId,o.customerName,o.phone].some(v=>String(v).toLowerCase().indexOf(q)>=0))}return rows}
function getOrder_(p){const o=read_('Orders').find(x=>x.orderId===p.orderId);return o?Object.assign({},o,{items:read_('OrderItems').filter(i=>i.orderId===p.orderId)}):null}
function saveSettings_(p){Object.keys(p).forEach(k=>upsert_('SiteSettings','key',{key:k,value:p[k]}));audit_('owner','save','settings','site',Object.keys(p));return settings_()}
function saveDeliveryRates_(p){(p.rates||[]).forEach(r=>{if(!r.id)r.id=Utilities.getUuid();upsert_('DeliveryRates','id',r)});return read_('DeliveryRates')}
function settings_(){return read_('SiteSettings').reduce((o,r)=>(o[r.key]=r.value,o),{})}
function sheet_(n){const s=SpreadsheetApp.getActive().getSheetByName(n);if(!s)throw new Error('Run setup() first: '+n);return s}
function read_(n){const sh=sheet_(n),values=sh.getDataRange().getValues();if(values.length<2)return[];const h=values[0];return values.slice(1).filter(r=>r.some(v=>v!=='' )).map(r=>h.reduce((o,k,i)=>(o[k]=r[i],o),{}))}
function append_(n,obj){const h=SCHEMA[n];sheet_(n).appendRow(h.map(k=>obj[k]===undefined?'':typeof obj[k]==='object'?JSON.stringify(obj[k]):obj[k]))}
function upsert_(n,key,obj){const rows=read_(n),i=rows.findIndex(r=>String(r[key])===String(obj[key]));if(i<0)return append_(n,obj);return patch_(n,key,obj[key],obj)}
function patch_(n,key,value,changes){const sh=sheet_(n),data=sh.getDataRange().getValues(),h=data[0],ki=h.indexOf(key);for(let r=1;r<data.length;r++)if(String(data[r][ki])===String(value)){Object.keys(changes).forEach(k=>{const c=h.indexOf(k);if(c>=0)sh.getRange(r+1,c+1).setValue(typeof changes[k]==='object'?JSON.stringify(changes[k]):changes[k])});return changes}throw new Error(n+' row not found')}
function remove_(n,key,value){const sh=sheet_(n),data=sh.getDataRange().getValues(),ki=data[0].indexOf(key);for(let r=data.length-1;r>=1;r--)if(String(data[r][ki])===String(value))sh.deleteRow(r+1)}
function audit_(admin,action,type,id,details){append_('AuditLog',{timestamp:new Date().toISOString(),admin,action,entityType:type,entityId:id,details:JSON.stringify(details)})}
function safeJson_(v,fallback){try{return JSON.parse(v||'')}catch(e){return fallback}}
function bool_(v){return v===true||String(v).toLowerCase()==='true'}
function out_(data){return ContentService.createTextOutput(JSON.stringify(data)).setMimeType(ContentService.MimeType.JSON)}
