/* eslint-disable react-hooks/exhaustive-deps -- loadAdmin is stable in the store provider. */
import {NavLink,Outlet,useNavigate} from 'react-router-dom';
import {BarChart3,Boxes,FolderKanban,Gauge,Home,Image,LogOut,Menu,Ruler,Settings,Truck,X} from 'lucide-react';
import {useEffect,useState} from 'react';
import {useStore} from '../features/store/StoreContext';

const links=[['/admin',Gauge,'Dashboard'],['/admin/products',Boxes,'Products'],['/admin/categories',FolderKanban,'Categories'],['/admin/orders',BarChart3,'Orders'],['/admin/homepage',Home,'Homepage'],['/admin/media',Image,'Media'],['/admin/size-charts',Ruler,'Size Charts'],['/admin/delivery',Truck,'Delivery'],['/admin/settings',Settings,'Settings']] as const;

export function AdminLayout(){const[open,setOpen]=useState(false),nav=useNavigate(),store=useStore();useEffect(()=>{void store.loadAdmin()},[store.loadAdmin]);async function logout(){if(store.live)await fetch('/api/admin/logout',{method:'POST'}).catch(()=>undefined);sessionStorage.removeItem('admin-demo');nav('/admin/login')}const sidebar=<><div className="flex items-center justify-between"><img src="/brand/logo-light.svg" alt="ZEVENRA" className="w-40"/><button className="grid min-h-11 min-w-11 place-items-center md:hidden" onClick={()=>setOpen(false)}><X/></button></div><nav className="mt-8 grid gap-1 overflow-y-auto">{links.map(([to,Icon,label])=><NavLink end={to==='/admin'} key={to} to={to} onClick={()=>setOpen(false)} className={({isActive})=>`flex min-h-12 items-center gap-3 px-3 text-sm ${isActive?'bg-white/10 text-white':'text-white/55 hover:text-white'}`}><Icon size={17}/>{label}</NavLink>)}</nav><button onClick={()=>void logout()} className="mt-auto flex min-h-12 items-center gap-3 px-3 text-sm text-white/55"><LogOut size={17}/> Sign out</button></>;return <div className="min-h-dvh bg-[#e9e5de]"><aside className="fixed inset-y-0 left-0 z-40 hidden w-64 flex-col bg-[#11110f] p-5 md:flex">{sidebar}</aside>{open&&<aside className="fixed inset-0 z-50 flex flex-col bg-[#11110f] p-5 md:hidden">{sidebar}</aside>}<div className="md:pl-64"><header className="flex h-16 items-center justify-between border-b border-black/10 bg-[#f4f1eb] px-4 sm:px-6"><button className="grid min-h-11 min-w-11 place-items-center md:hidden" onClick={()=>setOpen(true)}><Menu/></button><p className="eyebrow hidden sm:block">ZEVENRA / CONTROL ROOM</p><span className={`rounded-full px-3 py-1 text-[9px] tracking-widest ${store.live?'bg-emerald-900/10 text-emerald-900':'bg-amber-900/10 text-amber-900'}`}>{store.live?'LIVE DATA':'LOCAL DATA'}</span></header><main className="p-4 sm:p-7 lg:p-10">{store.adminLoading?<div className="grid min-h-[60vh] place-content-center"><p className="eyebrow">Loading admin data…</p></div>:store.adminError?<div className="border border-red-900/20 bg-red-950 p-4 text-sm text-white" role="alert"><div className="flex flex-wrap items-center justify-between gap-3"><span>{store.adminError}</span><button className="underline" onClick={()=>void store.loadAdmin()}>Retry</button></div></div>:<Outlet/>}</main></div></div>}
