/* eslint-disable react-hooks/exhaustive-deps -- loadAdmin is stable in the store provider. */
import {useEffect,useState} from 'react';
import {NavLink,Outlet,useNavigate} from 'react-router-dom';
import {BarChart3,Boxes,FolderKanban,Gauge,Home,Image,LogOut,Menu,Ruler,Settings,Truck,X} from 'lucide-react';
import {useStore} from '../features/store/StoreContext';

const links=[['/admin',Gauge,'Dashboard'],['/admin/products',Boxes,'Products'],['/admin/categories',FolderKanban,'Categories'],['/admin/orders',BarChart3,'Orders'],['/admin/homepage',Home,'Homepage'],['/admin/media',Image,'Media'],['/admin/size-charts',Ruler,'Size Charts'],['/admin/delivery',Truck,'Delivery'],['/admin/settings',Settings,'Settings']] as const;

export function AdminLayout(){
 const[open,setOpen]=useState(false),navigate=useNavigate(),store=useStore();
 useEffect(()=>{void store.loadAdmin()},[store.loadAdmin]);
 async function logout(){if(store.live)await fetch('/api/admin/logout',{method:'POST'}).catch(()=>undefined);sessionStorage.removeItem('admin-demo');navigate('/admin/login')}
 const sidebar=<><div className="flex items-center justify-between border-b border-white/10 pb-6"><img src="/brand/logo-light.svg" alt="ZEVENRA" className="w-36"/><button className="grid min-h-11 min-w-11 place-items-center text-white/70 md:hidden" onClick={()=>setOpen(false)} aria-label="Close navigation"><X size={19}/></button></div><p className="mt-7 text-[8px] font-medium tracking-[.25em] text-[#b58c62]">CONTROL ROOM</p><nav className="mt-5 grid gap-1 overflow-y-auto">{links.map(([to,Icon,label])=><NavLink end={to==='/admin'} key={to} to={to} onClick={()=>setOpen(false)} className={({isActive})=>`group flex min-h-12 items-center gap-3 border-l px-4 text-[13px] transition ${isActive?'border-[#b58c62] bg-white/[.07] text-white':'border-transparent text-white/50 hover:bg-white/[.04] hover:text-white'}`}><Icon size={16} strokeWidth={1.6}/><span>{label}</span></NavLink>)}</nav><button onClick={()=>void logout()} className="mt-auto flex min-h-12 items-center gap-3 border-t border-white/10 px-4 pt-5 text-[13px] text-white/50 transition hover:text-white"><LogOut size={16}/> Sign out</button></>;
 return <div className="admin-shell min-h-dvh"><aside className="fixed inset-y-0 left-0 z-40 hidden w-64 flex-col bg-[#10100f] p-6 md:flex">{sidebar}</aside>{open&&<aside className="fixed inset-0 z-50 flex flex-col bg-[#10100f] p-6 md:hidden">{sidebar}</aside>}<div className="md:pl-64"><header className="sticky top-0 z-30 flex h-16 items-center justify-between border-b border-black/10 bg-[#f4f1eb]/95 px-4 backdrop-blur-md sm:px-7"><button className="grid min-h-11 min-w-11 place-items-center md:hidden" onClick={()=>setOpen(true)} aria-label="Open navigation"><Menu size={19}/></button><div className="hidden items-center gap-3 sm:flex"><span className="h-1.5 w-1.5 rounded-full bg-[#96724f]"/><p className="eyebrow text-black/50">ZEVENRA / OPERATIONS</p></div><span className={`rounded-full border px-3 py-1.5 text-[8px] font-medium tracking-[.18em] ${store.live?'border-emerald-900/15 bg-emerald-900/[.06] text-emerald-950':'border-amber-900/15 bg-amber-900/[.06] text-amber-950'}`}>{store.live?'LIVE DATA':'DEMO MODE'}</span></header><main className="p-4 sm:p-8 lg:p-12 xl:p-14">{store.adminLoading?<div className="grid min-h-[65vh] place-content-center text-center"><span className="mx-auto mb-5 h-6 w-6 animate-spin rounded-full border border-black/15 border-t-black"/><p className="eyebrow text-black/45">Loading control room…</p></div>:store.adminError?<div className="mx-auto mt-10 max-w-xl border border-red-900/15 bg-[#301515] p-6 text-sm text-white" role="alert"><p className="display text-2xl">Admin data unavailable.</p><div className="mt-3 flex flex-wrap items-center justify-between gap-4 text-white/70"><span>{store.adminError}</span><button className="border-b border-white/50 pb-1 text-[10px] tracking-[.18em]" onClick={()=>void store.loadAdmin()}>RETRY</button></div></div>:<Outlet/>}</main></div></div>
}
