import {useEffect,useState} from 'react';
import {Link,NavLink,Outlet,useLocation} from 'react-router-dom';
import {AnimatePresence,motion} from 'framer-motion';
import {ArrowRight,ArrowUpRight,ChevronDown,Instagram,Menu,MessageCircle,PackageCheck,Search,ShoppingBag,Truck,UserRound,X} from 'lucide-react';
import {CartDrawer} from '../components/CartDrawer';
import {useCart} from '../features/cart/CartContext';
import {useStore} from '../features/store/StoreContext';
import {getNavigationCategories,type NavigationCategory} from '../services/navigation';

export function StoreLayout(){const cart=useCart(),{data}=useStore(),location=useLocation(),[menu,setMenu]=useState(false),[solid,setSolid]=useState(location.pathname!=='/');useEffect(()=>{setMenu(false);const update=()=>setSolid(location.pathname!=='/'||scrollY>48);update();addEventListener('scroll',update,{passive:true});return()=>removeEventListener('scroll',update)},[location.pathname]);const categories=getNavigationCategories(data.categories,data.products);return <div><div className="announcement">{data.settings.announcement}</div><header className={`site-header ${solid?'site-header--solid':'site-header--hero'}`}><div className="site-header__inner"><button onClick={()=>setMenu(true)} aria-label="Open menu" className="nav-icon lg:hidden"><Menu size={20}/></button><Link to="/" className="site-logo" aria-label="ZEVENRA home"><img src="/brand/zevenraname-nav.png" alt="ZEVENRA"/></Link><DesktopNavigation categories={categories}/><div className="header-actions"><Link to="/shop" aria-label="Search" className="nav-icon"><Search size={19}/></Link><Link to="/account" aria-label="Your profile" className="nav-icon"><UserRound size={19}/></Link><button onClick={()=>cart.setOpen(true)} aria-label={`Bag with ${cart.count} items`} className="nav-icon"><ShoppingBag size={19}/><span className="bag-count">{cart.count}</span></button></div></div></header><AnimatePresence>{menu&&<MobileMenu categories={categories} close={()=>setMenu(false)} logo="/brand/zevenraname-nav.png" instagram={data.settings.instagram} tiktok={data.settings.tiktok}/>}</AnimatePresence><main><Outlet/></main><Footer/><CartDrawer/></div>}

function DesktopNavigation({categories}:{categories:NavigationCategory[]}){return <nav className="desktop-nav" aria-label="Primary navigation"><NavLink to="/shop?new=true">NEW</NavLink><NavLink to="/shop">SHOP</NavLink>{categories.map(category=><div className="desktop-category" key={category.id}><NavLink to={`/category/${category.slug}`}>{category.name.toUpperCase()}{category.children.length>0&&<ChevronDown size={12}/>}</NavLink>{category.children.length>0&&<div className="category-menu"><Link className="category-menu__all" to={`/category/${category.slug}`}>SHOP ALL {category.name.toUpperCase()}</Link>{category.children.map(child=><Link key={child.id} to={`/category/${child.slug}`}>{child.name.toUpperCase()}</Link>)}</div>}</div>)}<NavLink to="/about">ABOUT</NavLink></nav>}

function MobileMenu({categories,close,logo,instagram,tiktok}:{categories:NavigationCategory[];close:()=>void;logo:string;instagram:string;tiktok:string}){const items=[{id:'new',label:'NEW',to:'/shop?new=true'},{id:'shop',label:'SHOP',to:'/shop'},...categories.map(category=>({id:category.id,label:category.name.toUpperCase(),to:`/category/${category.slug}`,children:category.children})),{id:'about',label:'ABOUT',to:'/about'}];return <motion.div className="mobile-menu" initial={{clipPath:'inset(0 0 100% 0)'}} animate={{clipPath:'inset(0 0 0% 0)'}} exit={{clipPath:'inset(0 0 100% 0)'}} transition={{duration:.55,ease:[.76,0,.24,1]}}><div className="mobile-menu__top"><img src={logo} alt="ZEVENRA"/><button onClick={close} aria-label="Close menu"><X/></button></div><nav>{items.map((item,index)=><motion.div key={item.id} initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} transition={{delay:.15+index*.045}}><Link to={item.to}><span>0{index+1}</span>{item.label}<ArrowUpRight/></Link>{'children'in item&&item.children&&item.children.length>0&&<div className="mobile-subcategories">{item.children.map(child=><Link key={child.id} to={`/category/${child.slug}`}>{child.name.toUpperCase()}</Link>)}</div>}</motion.div>)}</nav><div className="mobile-menu__foot"><a href={instagram} target="_blank" rel="noreferrer">INSTAGRAM</a><a href={tiktok} target="_blank" rel="noreferrer">TIKTOK</a><Link to="/contact">CONTACT</Link></div></motion.div>}

function validExternalUrl(value:string){try{const url=new URL(value.trim());return url.protocol==='https:'||url.protocol==='http:'?url.toString():''}catch{return''}}
function whatsappUrl(value:string){const digits=value.replace(/\D/g,'');return digits.length>=8?`https://wa.me/${digits}`:''}

function Footer(){
 const{data}=useStore(),settings=data.settings;
 const instagram=validExternalUrl(settings.instagram||''),tiktok=validExternalUrl(settings.tiktok||''),whatsapp=whatsappUrl(settings.whatsapp||'');
 const topCategories=data.categories.filter(category=>category.active&&!category.parentId).sort((a,b)=>a.sortOrder-b.sortOrder);
 const supportContent=<><MessageCircle/><span><b>WhatsApp support</b><small>Need help before ordering? Talk to us.</small></span></>;
 return <>
  <section className="footer-assurances" aria-label="Shopping assurances"><div className="container">
   <div><Truck/><span><b>Islandwide delivery</b><small>Delivery across Sri Lanka.</small></span></div>
   <div><PackageCheck/><span><b>Sourced with care</b><small>Selected pieces from trusted sources.</small></span></div>
   {whatsapp?<a href={whatsapp} target="_blank" rel="noreferrer noopener">{supportContent}</a>:<div>{supportContent}</div>}
  </div></section>
  <footer className="site-footer"><div className="container footer-main">
   <div className="footer-brand"><img src={settings.logoLight} alt={settings.brandName||'ZEVENRA'} className="footer-logo"/><p className="footer-tagline">THE ART OF BECOMING.</p><span className="footer-rule"/><p className="footer-title">The art of<br/><em>becoming.</em></p><p className="footer-description">Selected beyond borders.<br/>Curated for here.</p><p className="footer-supporting">Fashion, people, stories — always becoming.</p></div>
   <div className="footer-column footer-shop"><p className="footer-label">Shop</p><Link to="/shop">Shop All</Link><Link to="/shop?new=true">New Arrivals</Link>{topCategories.map(category=><Link key={category.id} to={`/category/${category.slug}`}>{category.name}</Link>)}<Link to="/about">About</Link></div>
   <div className="footer-column footer-care"><p className="footer-label">Customer Care</p><Link to="/delivery">Delivery</Link><Link to="/returns">Returns &amp; Exchanges</Link><Link to="/contact">Contact</Link></div>
   {whatsapp&&<div className="footer-column footer-order-support"><p className="footer-label">Order Support</p><strong>WhatsApp Us</strong><p>Questions about sizing, availability or delivery?<br/>Message us before placing your order.</p><a className="footer-whatsapp" href={whatsapp} target="_blank" rel="noreferrer noopener">Chat on WhatsApp <ArrowUpRight size={14}/></a></div>}
   {(instagram||tiktok||whatsapp)&&<div className="footer-column footer-follow"><p className="footer-label">Follow ZEVENRA</p>{instagram&&<a href={instagram} target="_blank" rel="noreferrer noopener"><Instagram size={16}/>Instagram <ArrowUpRight size={12}/></a>}{tiktok&&<a href={tiktok} target="_blank" rel="noreferrer noopener">TikTok <ArrowUpRight size={12}/></a>}{whatsapp&&<a href={whatsapp} target="_blank" rel="noreferrer noopener"><MessageCircle size={16}/>WhatsApp <ArrowUpRight size={12}/></a>}</div>}
   <div className="footer-column footer-legal"><p className="footer-label">Legal</p><Link to="/privacy">Privacy</Link><Link to="/terms">Terms &amp; Conditions</Link></div>
   <div className="footer-cta"><Link to="/shop">Explore the collection <ArrowRight size={16}/></Link></div>
  </div><div className="container footer-bottom"><span>© {new Date().getFullYear()} ZEVENRA. ALL RIGHTS RESERVED.</span><span>SRI LANKA</span><span><Link to="/privacy">PRIVACY</Link><Link to="/terms">TERMS</Link></span></div></footer>
 </>
}
