import { useEffect, useMemo, useState } from "react";
import { Plus, Save, Search } from "lucide-react";
import { adminApi } from "../../services/adminApi";

type Method={type:"flat"|"area_group"|"pickup";displayName:string;active:boolean;fee:number|null;minimumDeliveryDays:number|null;maximumDeliveryDays:number|null;sortOrder:number};
type Group={id:string;name:string;fee:number|null;active:boolean;fallback:boolean;sortOrder:number};
type Location={id:string;groupId:string;district:string;town:string;postcode?:string;aliases:string[];active:boolean};
type Pickup={id:string;name:string;address:string;instructions:string;active:boolean;sortOrder:number};
type Config={methods:Method[];groups:Group[];locations:Location[];districtDefaults:Array<{district:string;groupId:string}>;pickupLocations:Pickup[]};
const districts=["Ampara","Anuradhapura","Badulla","Batticaloa","Colombo","Galle","Gampaha","Hambantota","Jaffna","Kalutara","Kandy","Kegalle","Kilinochchi","Kurunegala","Mannar","Matale","Matara","Monaragala","Mullaitivu","Nuwara Eliya","Polonnaruwa","Puttalam","Ratnapura","Trincomalee","Vavuniya"];
const titles={flat:"Flat Rate Delivery",area_group:"Area Group Delivery",pickup:"Collect From Branch"};

export default function DeliveryAdminPage(){
 const [config,setConfig]=useState<Config|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[search,setSearch]=useState(""),[manage,setManage]=useState(false);
 useEffect(()=>{void adminApi.get<Config>("getFulfillmentConfig").then(setConfig).catch(e=>setMessage(e instanceof Error?e.message:"Could not load delivery settings."));},[]);
 const filtered=useMemo(()=>{const q=search.toLocaleLowerCase();return(config?.locations||[]).filter(l=>!q||`${l.town} ${l.district} ${l.postcode||""}`.toLocaleLowerCase().includes(q));},[config,search]);
 if(!config)return <div className="admin-card p-5">{message||"Loading delivery settings…"}</div>;
 const updateMethod=(type:Method["type"],patch:Partial<Method>)=>setConfig({...config,methods:config.methods.map(m=>m.type===type?{...m,...patch}:m)});
 const updateGroup=(id:string,patch:Partial<Group>)=>setConfig({...config,groups:config.groups.map(g=>g.id===id?{...g,...patch}:g)});
 const updatePickup=(id:string,patch:Partial<Pickup>)=>setConfig({...config,pickupLocations:config.pickupLocations.map(p=>p.id===id?{...p,...patch}:p)});
 async function save(){setBusy(true);setMessage("");try{setConfig(await adminApi.post<Config>("saveFulfillmentConfig",config));setMessage("Delivery settings saved.");}catch(e){setMessage(e instanceof Error?e.message:"Could not save delivery settings.");}finally{setBusy(false);}}
 return <div className="space-y-5 pb-24">
  <header><p className="admin-kicker">Delivery methods</p><h1 className="text-2xl font-semibold">Simple fulfilment</h1><p className="mt-2 max-w-2xl text-sm text-black/55">Enable any combination. Checkout shows only active methods and the server calculates the final fee.</p></header>
  {message?<p className="border border-amber-300 bg-amber-50 p-3 text-sm">{message}</p>:null}
  <section className="grid gap-3 lg:grid-cols-3">{config.methods.map(m=><article key={m.type} className="admin-card p-4"><label className="flex items-center justify-between gap-3"><b>{titles[m.type]}</b><input type="checkbox" checked={m.active} onChange={e=>updateMethod(m.type,{active:e.target.checked})}/></label><label className="label mt-4 block">Display name<input className="field mt-1" value={m.displayName} onChange={e=>updateMethod(m.type,{displayName:e.target.value})}/></label>{m.type==="flat"?<label className="label mt-3 block">Flat fee (LKR)<input className="field mt-1" type="number" min="0" placeholder="Required before enabling" value={m.fee??""} onChange={e=>updateMethod("flat",{fee:e.target.value===""?null:Number(e.target.value)})}/></label>:null}{m.type!=="pickup"?<div className="mt-3 grid grid-cols-2 gap-2"><label className="label">Min days<input className="field mt-1" type="number" min="1" value={m.minimumDeliveryDays??""} onChange={e=>updateMethod(m.type,{minimumDeliveryDays:e.target.value===""?null:Number(e.target.value)})}/></label><label className="label">Max days<input className="field mt-1" type="number" min="1" value={m.maximumDeliveryDays??""} onChange={e=>updateMethod(m.type,{maximumDeliveryDays:e.target.value===""?null:Number(e.target.value)})}/></label></div>:null}</article>)}</section>
  <section className="admin-card p-4 sm:p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="admin-kicker">Area Group Delivery</p><h2 className="text-lg font-semibold">Five pricing groups</h2></div><button className="btn" type="button" onClick={()=>setManage(v=>!v)}>{manage?"Close areas":"Manage areas"}</button></div>
   <div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-5">{config.groups.map(g=><article className="border border-black/10 p-3" key={g.id}><label className="label block">Group name<input className="field mt-1" value={g.name} onChange={e=>updateGroup(g.id,{name:e.target.value})}/></label><label className="label mt-3 block">Fee (LKR)<input className="field mt-1" type="number" min="0" value={g.fee??""} onChange={e=>updateGroup(g.id,{fee:e.target.value===""?null:Number(e.target.value)})}/></label><div className="mt-3 flex items-center justify-between text-xs"><label><input type="checkbox" checked={g.active} onChange={e=>updateGroup(g.id,{active:e.target.checked})}/> Active</label><span>{config.locations.filter(l=>l.groupId===g.id&&l.active).length} towns</span></div>{g.fallback?<p className="mt-2 text-xs font-semibold text-bronze">Final fallback</p>:null}</article>)}</div>
   {manage?<div className="mt-5 border-t pt-5"><label className="relative block"><Search className="absolute left-3 top-3.5" size={16}/><input className="field pl-10" placeholder="Search town, district or postcode" value={search} onChange={e=>setSearch(e.target.value)}/></label><div className="mt-3 max-h-[28rem] space-y-2 overflow-auto">{filtered.map(l=><div key={l.id} className="grid gap-2 border p-3 text-sm sm:grid-cols-[minmax(0,1fr)_minmax(10rem,14rem)_auto]"><span><input className="field" value={l.town} placeholder="Town" onChange={e=>setConfig({...config,locations:config.locations.map(x=>x.id===l.id?{...x,town:e.target.value}:x)})}/><small className="block text-black/50">{l.district}{l.postcode?` · ${l.postcode}`:""}</small></span><select className="field" value={l.groupId} onChange={e=>setConfig({...config,locations:config.locations.map(x=>x.id===l.id?{...x,groupId:e.target.value}:x)})}>{config.groups.map(g=><option key={g.id} value={g.id}>{g.name}</option>)}</select><label className="self-center"><input type="checkbox" checked={l.active} onChange={e=>setConfig({...config,locations:config.locations.map(x=>x.id===l.id?{...x,active:e.target.checked}:x)})}/> Active</label></div>)}</div><button className="btn mt-3" type="button" onClick={()=>setConfig({...config,locations:[...config.locations,{id:`new-${crypto.randomUUID()}`,groupId:config.groups[4].id,district:"Colombo",town:"",aliases:[],active:true}]})}><Plus size={14}/> Add location</button></div>:null}
   <details className="mt-5 border-t pt-4"><summary className="cursor-pointer text-sm font-semibold">District defaults</summary><div className="mt-3 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{districts.map(d=>{const current=config.districtDefaults.find(x=>x.district===d);return <label className="label" key={d}>{d}<select className="field mt-1" value={current?.groupId||""} onChange={e=>setConfig({...config,districtDefaults:[...config.districtDefaults.filter(x=>x.district!==d),...(e.target.value?[{district:d,groupId:e.target.value}]:[])]})}><option value="">Use fallback</option>{config.groups.map(g=><option key={g.id} value={g.id}>{g.name}</option>)}</select></label>})}</div></details>
  </section>
  <section className="admin-card p-4 sm:p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="admin-kicker">Collect From Branch</p><h2 className="text-lg font-semibold">Pickup branches</h2></div><button className="btn" type="button" onClick={()=>setConfig({...config,pickupLocations:[...config.pickupLocations,{id:`new-${crypto.randomUUID()}`,name:"",address:"",instructions:"",active:false,sortOrder:config.pickupLocations.length+1}]})}><Plus size={14}/> Add branch</button></div><div className="mt-4 grid gap-3 lg:grid-cols-2">{config.pickupLocations.map(p=><article className="border p-3" key={p.id}><label className="label block">Branch name<input className="field mt-1" value={p.name} onChange={e=>updatePickup(p.id,{name:e.target.value})}/></label><label className="label mt-3 block">Address<textarea className="field mt-1 min-h-20" value={p.address} onChange={e=>updatePickup(p.id,{address:e.target.value})}/></label><label className="label mt-3 block">Customer instructions<textarea className="field mt-1 min-h-16" value={p.instructions} onChange={e=>updatePickup(p.id,{instructions:e.target.value})}/></label><label className="mt-3 block text-sm"><input type="checkbox" checked={p.active} onChange={e=>updatePickup(p.id,{active:e.target.checked})}/> Active</label></article>)}</div>{!config.pickupLocations.length?<p className="mt-4 text-sm text-black/50">No branches entered. Add exact branch details before enabling pickup.</p>:null}</section>
  <div className="sticky bottom-3 flex justify-end"><button type="button" className="btn btn-dark shadow-lg" disabled={busy} onClick={()=>void save()}><Save size={15}/>{busy?"Saving…":"Save delivery settings"}</button></div>
 </div>;
}
