import {useState,type FormEvent} from 'react';
import {useNavigate} from 'react-router-dom';
import {ArrowUpRight,Eye,EyeOff,LockKeyhole,ShieldCheck,UserRound} from 'lucide-react';

export default function LoginPage(){
 const navigate=useNavigate(),[error,setError]=useState(''),[busy,setBusy]=useState(false),[showPassword,setShowPassword]=useState(false);
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setError('');setBusy(true);const credentials=Object.fromEntries(new FormData(event.currentTarget));try{if(import.meta.env.VITE_DEMO_MODE==='true'){if(!credentials.username||!credentials.password)throw new Error('Enter your username and password.');sessionStorage.setItem('admin-demo','1');navigate('/admin');return}const response=await fetch('/api/admin/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(credentials)}),payload=await response.json().catch(()=>({error:''})) as{error?:string};if(!response.ok)throw new Error(response.status>=500?(payload.error||'Admin login is temporarily unavailable.'):'Invalid credentials. Please try again.');navigate('/admin')}catch(reason){setError(reason instanceof Error?reason.message:'Admin login is temporarily unavailable.')}finally{setBusy(false)}}
 return <main className="admin-login">
  <section className="admin-login__visual" aria-hidden="true"><img src="/brand/hero.jpg" alt=""/><div className="admin-login__visual-copy"><span>Private studio</span><p className="display">The art of<br/><em>becoming.</em></p></div><div className="admin-login__visual-foot"><span>EST. 2026</span><span>COLOMBO — LK</span></div></section>
  <section className="admin-login__content"><div className="admin-login__ambient" aria-hidden="true"/><header className="admin-login__top"><img src="/brand/logo-light.svg" alt="ZEVENRA"/><span><i/> Secure portal</span></header>
   <form onSubmit={submit} className="admin-login__form"><div className="admin-login__index"><span>OWNER ACCESS</span><span>01 / 01</span></div><div className="admin-login__heading"><h1 className="display">Welcome<br/><em>back.</em></h1><p>Enter the private workspace for managing products, orders, and the ZEVENRA story.</p></div>
    <div className="admin-login__fields"><label><span>Username</span><div className="admin-login__field"><UserRound/><input name="username" autoComplete="username" placeholder="Enter your username" required/></div></label><label><span>Password</span><div className="admin-login__field"><LockKeyhole/><input name="password" type={showPassword?'text':'password'} autoComplete="current-password" placeholder="Enter your password" required/><button type="button" onClick={()=>setShowPassword(value=>!value)} aria-label={showPassword?'Hide password':'Show password'}>{showPassword?<EyeOff/>:<Eye/>}</button></div></label></div>
    {error&&<p role="alert" className="admin-login__error">{error}</p>}<button disabled={busy} className="admin-login__submit"><span>{busy?'Signing in…':'Enter control room'}</span><ArrowUpRight/></button><p className="admin-login__note"><ShieldCheck/> Protected by an encrypted server session</p>
   </form><footer className="admin-login__footer"><span>© 2026 ZEVENRA</span><span>AUTHORISED PERSONNEL ONLY</span></footer></section>
 </main>
}
