import {useMemo,useState} from 'react';
import {ArrowLeft,Plus,Trash2} from 'lucide-react';
import {Link,useSearchParams} from 'react-router-dom';
import {money} from '../../config/site';
import {useStore} from '../../features/store/StoreContext';
import type {OrderSource,PaymentMethod} from '../../types';

const districts=['Ampara','Anuradhapura','Badulla','Batticaloa','Colombo','Galle','Gampaha','Hambantota','Jaffna','Kalutara','Kandy','Kegalle','Kilinochchi','Kurunegala','Mannar','Matale','Matara','Monaragala','Mullaitivu','Nuwara Eliya','Polonnaruwa','Puttalam','Ratnapura','Trincomalee','Vavuniya'];
type Line={key:string;productId:string;variantId:string;quantity:number;unitPrice?:number};
const newLine=():Line=>({key:crypto.randomUUID(),productId:'',variantId:'',quantity:1});

export default function ManualOrderPage(){
 const store=useStore(),[params]=useSearchParams(),preId=params.get('pre')||'',pre=store.admin.preorders.find(r=>r.requestId===preId);
 const initialLine=pre?{key:crypto.randomUUID(),productId:pre.productId,variantId:pre.variantId,quantity:pre.quantity,unitPrice:Number(pre.confirmedPrice||pre.requestedPrice)}:newLine();
 const[customerName,setCustomerName]=useState(pre?.customerName||''),[phone,setPhone]=useState(pre?.phone||''),[whatsapp,setWhatsapp]=useState(pre?.whatsapp||''),[email,setEmail]=useState(pre?.email||''),[address1,setAddress1]=useState(''),[address2,setAddress2]=useState(''),[city,setCity]=useState(pre?.city||''),[district,setDistrict]=useState(pre?.district||''),[postalCode,setPostalCode]=useState(''),[notes,setNotes]=useState(''),[source,setSource]=useState<OrderSource>(pre?'preorder':'instagram'),[paymentMethod,setPaymentMethod]=useState<PaymentMethod>('cod'),[paymentStatus,setPaymentStatus]=useState('COD'),[orderStatus,setOrderStatus]=useState('pending'),[lines,setLines]=useState<Line[]>([initialLine]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[created,setCreated]=useState('');
 const products=useMemo(()=>store.data.products.filter(p=>p.status!=='archived').sort((a,b)=>a.name.localeCompare(b.name)),[store.data.products]);
 const previewSubtotal=lines.reduce((sum,line)=>{const p=products.find(x=>x.id===line.productId);return sum+Number(line.unitPrice||p?.price||0)*line.quantity},0);
 function patchLine(key:string,patch:Partial<Line>){setLines(current=>current.map(line=>line.key===key?{...line,...patch}:line))}
 function chooseProduct(line:Line,productId:string){const product=products.find(p=>p.id===productId),variant=product?.variants.find(v=>v.active&&v.stock>0);patchLine(line.key,{productId,variantId:variant?.id||'',unitPrice:product?.price})}
 async function submit(){
  setError('');
  if(customerName.trim().length<2||phone.trim().length<9||address1.trim().length<5||city.trim().length<2||!district){setError('Complete the customer and delivery details.');return}
  if(lines.some(line=>!line.productId||!line.variantId||line.quantity<1)){setError('Choose a product, size/colour and quantity for every item.');return}
  setBusy(true);
  try{
   const order=await store.createManualOrder({customerName,phone,whatsapp,email,address1,address2,city,district,postalCode,deliveryNotes:notes,paymentMethod,paymentStatus,orderStatus,source,preorderRequestId:pre?.requestId||undefined,items:lines.map(({productId,variantId,quantity,unitPrice})=>({productId,variantId,quantity,unitPrice}))});
   setCreated(order.orderId);
  }catch(reason){setError(reason instanceof Error?reason.message:'Could not create the order.')}
  finally{setBusy(false)}
 }
 if(created)return <div className="mx-auto max-w-xl py-10 text-center"><p className="eyebrow text-emerald-800">Order created</p><h1 className="display mt-3 text-5xl">{created}</h1><p className="mt-4 text-sm leading-7 text-black/55">Stock was reserved immediately. The order is now managed with all other sales.</p><div className="mt-7 flex flex-wrap justify-center gap-3"><Link to="/admin/orders" className="btn btn-dark">View orders</Link><Link to="/admin/orders/new" className="btn">Create another</Link></div></div>;
 return <div className="mx-auto max-w-6xl"><Link to="/admin/orders" className="mb-6 inline-flex min-h-11 items-center gap-2 text-xs underline"><ArrowLeft size={15}/> Back to orders</Link><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="eyebrow text-black/45">{pre?'Convert pre-order':'Instagram / WhatsApp / admin sale'}</p><h1 className="display mt-2 text-4xl md:text-5xl">New manual order</h1></div>{pre&&<span className="border border-[#96724f]/25 bg-[#96724f]/5 px-3 py-2 text-xs">{pre.requestId}</span>}</div><p className="mt-4 max-w-3xl text-sm leading-7 text-black/55">Use this when a customer buys through Instagram or WhatsApp, or when an arrived pre-order is ready for delivery. Creating the order reserves stock immediately.</p>

  <div className="mt-7 grid gap-5 lg:grid-cols-[1fr_.85fr]">
   <section className="space-y-5 bg-[#f6f3ed] p-4 sm:p-6"><p className="eyebrow">Customer & delivery</p><div className="grid gap-3 sm:grid-cols-2"><F label="Full name *" value={customerName} set={setCustomerName}/><F label="Mobile *" value={phone} set={setPhone} type="tel"/><F label="WhatsApp" value={whatsapp} set={setWhatsapp} type="tel"/><F label="Email" value={email} set={setEmail} type="email"/><div className="sm:col-span-2"><F label="Address line 1 *" value={address1} set={setAddress1}/></div><div className="sm:col-span-2"><F label="Address line 2" value={address2} set={setAddress2}/></div><F label="City *" value={city} set={setCity}/><label className="text-xs">District *<select className="field mt-2" value={district} onChange={e=>setDistrict(e.target.value)}><option value="">Select district</option>{districts.map(d=><option key={d}>{d}</option>)}</select></label><F label="Postal code" value={postalCode} set={setPostalCode}/><label className="text-xs">Source<select className="field mt-2" value={source} onChange={e=>setSource(e.target.value as OrderSource)}><option value="instagram">Instagram</option><option value="whatsapp">WhatsApp</option><option value="admin">Admin / phone</option><option value="preorder">Pre-order</option></select></label></div><label className="block text-xs">Delivery notes<textarea className="field mt-2 min-h-20 resize-none" value={notes} onChange={e=>setNotes(e.target.value)}/></label></section>

   <section className="space-y-5 bg-[#f6f3ed] p-4 sm:p-6"><p className="eyebrow">Payment & status</p><label className="block text-xs">Payment method<select className="field mt-2" value={paymentMethod} onChange={e=>{const value=e.target.value as PaymentMethod;setPaymentMethod(value);setPaymentStatus(value==='cod'?'COD':'verification required')}}><option value="cod">Cash on delivery</option><option value="bank">Bank transfer</option></select></label><label className="block text-xs">Payment status<select className="field mt-2" value={paymentStatus} onChange={e=>setPaymentStatus(e.target.value)}>{(paymentMethod==='cod'?['COD','paid','refunded']:['verification required','paid','verified','refunded']).map(value=><option key={value}>{value}</option>)}</select></label><label className="block text-xs">Order status<select className="field mt-2" value={orderStatus} onChange={e=>setOrderStatus(e.target.value)}>{['pending','confirmed','sourcing','packed','shipped','delivered'].map(value=><option key={value}>{value}</option>)}</select></label><div className="border-t border-black/10 pt-4 text-sm"><div className="flex justify-between"><span>Item subtotal preview</span><b>{money(previewSubtotal)}</b></div><p className="mt-2 text-xs leading-5 text-black/45">Delivery is calculated by the backend using the customer district. Final totals appear after order creation.</p></div></section>
  </div>

  <section className="mt-5 bg-[#f6f3ed] p-4 sm:p-6"><div className="flex flex-wrap items-center justify-between gap-3"><p className="eyebrow">Items</p><button className="btn" onClick={()=>setLines(current=>[...current,newLine()])}><Plus size={14}/> Add item</button></div><div className="mt-4 grid gap-3">{lines.map((line,index)=>{const product=products.find(p=>p.id===line.productId),variants=product?.variants.filter(v=>v.active)||[],variant=variants.find(v=>v.id===line.variantId);return <div key={line.key} className="grid gap-3 border border-black/10 bg-white/45 p-4 md:grid-cols-[1.4fr_1fr_100px_120px_auto] md:items-end"><label className="text-xs">Product<select className="field mt-2" value={line.productId} onChange={e=>chooseProduct(line,e.target.value)}><option value="">Select product</option>{products.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label className="text-xs">Variant<select className="field mt-2" value={line.variantId} onChange={e=>patchLine(line.key,{variantId:e.target.value})}><option value="">Select size / colour</option>{variants.map(v=><option key={v.id} value={v.id} disabled={v.stock<1}>{v.color} / {v.size} · stock {v.stock}</option>)}</select></label><label className="text-xs">Qty<input className="field mt-2" type="number" min="1" max={Math.max(1,variant?.stock||1)} value={line.quantity} onChange={e=>patchLine(line.key,{quantity:Math.max(1,Number(e.target.value)||1)})}/></label><label className="text-xs">Selling price<input className="field mt-2" type="number" min="1" value={line.unitPrice||product?.price||''} onChange={e=>patchLine(line.key,{unitPrice:Number(e.target.value)||undefined})}/></label><button disabled={lines.length===1} onClick={()=>setLines(current=>current.filter(x=>x.key!==line.key))} className="btn border-red-800 text-red-800 disabled:opacity-25" aria-label={'Remove item '+(index+1)}><Trash2 size={14}/></button></div>})}</div></section>

  {error&&<p className="mt-5 bg-red-950 p-3 text-xs text-white">{error}</p>}<div className="sticky bottom-3 z-10 mt-5 flex justify-end bg-[#e9e5de]/95 p-3 backdrop-blur"><button disabled={busy} onClick={()=>void submit()} className="btn btn-dark min-w-48 justify-center disabled:opacity-50">{busy?'Creating order…':'Create order'}</button></div>
 </div>
}
function F({label,value,set,type='text'}:{label:string;value:string;set:(value:string)=>void;type?:string}){return <label className="text-xs">{label}<input className="field mt-2" value={value} type={type} inputMode={type==='tel'?'tel':undefined} onChange={e=>set(e.target.value)}/></label>}
