import type {VercelRequest,VercelResponse} from '@vercel/node';
import {createHmac,timingSafeEqual} from 'node:crypto';
import {z} from 'zod';

export type Env={APPS_SCRIPT_URL:string;APPS_SCRIPT_SECRET:string;SESSION_SECRET:string;ADMIN_USERNAME:string;ADMIN_PASSWORD_HASH:string;CLOUDINARY_CLOUD_NAME:string;CLOUDINARY_API_KEY:string;CLOUDINARY_API_SECRET:string;ALLOWED_ORIGIN:string};

export function env():Env{return{APPS_SCRIPT_URL:required('APPS_SCRIPT_URL'),APPS_SCRIPT_SECRET:required('APPS_SCRIPT_SECRET'),SESSION_SECRET:required('SESSION_SECRET'),ADMIN_USERNAME:required('ADMIN_USERNAME'),ADMIN_PASSWORD_HASH:required('ADMIN_PASSWORD_HASH'),CLOUDINARY_CLOUD_NAME:required('CLOUDINARY_CLOUD_NAME'),CLOUDINARY_API_KEY:required('CLOUDINARY_API_KEY'),CLOUDINARY_API_SECRET:required('CLOUDINARY_API_SECRET'),ALLOWED_ORIGIN:required('ALLOWED_ORIGIN')}}
function required(name:keyof Env){const value=process.env[name];if(!value)throw new Error(`Missing environment variable: ${name}`);return value}

export function json(res:VercelResponse,data:unknown,status=200,headers:Record<string,string>={}){res.status(status);res.setHeader('Content-Type','application/json; charset=utf-8');res.setHeader('Cache-Control','no-store');for(const [name,value] of Object.entries(headers))res.setHeader(name,value);return res.json(data)}
export function methodNotAllowed(res:VercelResponse,allowed:string[]){res.setHeader('Allow',allowed.join(', '));return json(res,{error:'Method not allowed'},405)}
export function body(request:VercelRequest):unknown{if(typeof request.body==='string')return JSON.parse(request.body);if(Buffer.isBuffer(request.body))return JSON.parse(request.body.toString('utf8'));return request.body}

const b64=(value:Buffer|string)=>Buffer.from(value).toString('base64url');
function signature(value:string,secret:string){return createHmac('sha256',secret).update(value).digest('base64url')}
export function makeSession(secret:string){const payload=b64(JSON.stringify({sub:'owner',exp:Date.now()+1000*60*60*8}));return `${payload}.${signature(payload,secret)}`}
export function validSession(request:VercelRequest,secret:string){const header=request.headers.cookie;const cookie=(Array.isArray(header)?header.join('; '):header||'').match(/(?:^|; )zevenra_session=([^;]+)/)?.[1];if(!cookie)return false;const [payload,sig]=cookie.split('.');if(!payload||!sig)return false;const expected=Buffer.from(signature(payload,secret));const actual=Buffer.from(sig);if(expected.length!==actual.length||!timingSafeEqual(expected,actual))return false;try{const data=JSON.parse(Buffer.from(payload,'base64url').toString('utf8')) as {sub?:string;exp?:number};return data.sub==='owner'&&typeof data.exp==='number'&&data.exp>Date.now()}catch{return false}}
export function validOrigin(request:VercelRequest,config:Env){if(['GET','HEAD','OPTIONS'].includes(request.method||''))return true;const value=request.headers.origin;const origin=Array.isArray(value)?value[0]:value;if(!origin)return true;const host=request.headers['x-forwarded-host']||request.headers.host;const protocol=request.headers['x-forwarded-proto']||'https';const requestOrigin=host?`${Array.isArray(protocol)?protocol[0]:protocol}://${Array.isArray(host)?host[0]:host}`:'';return origin===config.ALLOWED_ORIGIN||origin===requestOrigin}
export async function callScript(config:Env,action:string,payload:unknown){const response=await fetch(config.APPS_SCRIPT_URL,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({token:config.APPS_SCRIPT_SECRET,action,payload})});if(!response.ok)throw new Error('Upstream unavailable');const data=await response.json() as {ok:boolean;data?:unknown;error?:string};if(!data.ok)throw new Error(data.error||'Upstream rejected request');return data.data}
export const orderSchema=z.object({customerName:z.string().min(2).max(100),phone:z.string().regex(/^[+\d][\d\s-]{8,14}$/),whatsapp:z.string().max(20).optional(),email:z.string().email().or(z.literal('')).optional(),address1:z.string().min(5).max(180),address2:z.string().max(180).optional(),city:z.string().min(2).max(80),district:z.string().min(2).max(80),postalCode:z.string().max(12).optional(),deliveryNotes:z.string().max(300).optional(),paymentMethod:z.enum(['cod','bank']),items:z.array(z.object({productId:z.string().min(1),variantId:z.string().min(1),quantity:z.number().int().min(1).max(10)})).min(1).max(30)}).strict();
export const adminLoginSchema=z.object({username:z.string().min(1).max(100),password:z.string().min(8).max(200)}).strict();
export async function sha256(value:string){return Buffer.from(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value))).toString('base64url')}
